Repository fossology/fossology, pull requests merged in 2018-04, with the labels that each got.

#992 fix(browseView): change style of checkbox button whole folder | Marke…
  src/readmeoss/ui/ReadMeOssPlugin.php
  src/spdx2/ui/SpdxTwoGeneratorUi.php
  src/www/ui/ajax-showjobs.php
  src/www/ui/css/fossology.css
  src/www/ui/template/ui-browse.html.twig
  src/www/ui/template/ui-browse.js.twig
Labels: needs code review, needs test

#1001 fix(reuser): remove warnings and errors with testcases for reuse
  src/composer.json
  src/lib/php/Dao/UploadDao.php
  src/reuser/agent/ReuserAgent.php
  src/reuser/agent/reuser.php
  src/reuser/agent_tests/Functional/schedulerTest.php
  src/reuser/ui/agent-reuser.php
  src/reuser/ui/reuser-plugin.php
Labels: needs code review, needs test

#984 feat(nomos): extend unclassified license detection
  src/nomos/agent/STRINGS.in
  src/nomos/agent/parse.c
  src/nomos/agent_tests/testdata/LastGoodNomosTestfilesScan
  src/nomos/agent_tests/testdata/NomosTestfiles/UnclassifiedLicense/cygwinRef.txt
Labels: needs code review, needs test

#968 feat(treeView): add select all checkbox for mass operations irrelevant
  src/www/ui/template/browse_file.js.twig
Labels: needs code review, needs test

#980 feat(licenses): update GPL-3.0+ license text
  install/db/licenseref.sql
Labels: needs code review, needs test

#978 feat(license): add acknowledgements to license clearing
  src/lib/php/Dao/ClearingDao.php
  src/lib/php/Data/Clearing/AgentClearingEvent.php
  src/lib/php/Data/Clearing/ClearingEvent.php
  src/lib/php/Data/Clearing/ClearingEventBuilder.php
  src/lib/php/Data/Clearing/ClearingLicense.php
  src/lib/php/Data/Clearing/ClearingResult.php
  src/lib/php/Data/Clearing/test/AgentClearingEventTest.php
  src/lib/php/Data/Clearing/test/ClearingResultTest.php
  src/lib/php/Data/ClearingDecision.php
  src/lib/php/Data/ClearingDecisionBuilder.php
  src/lib/php/Data/test/ClearingDecisionBuilderTest.php
  src/readmeoss/agent/readmeoss.php
  src/spdx2/agent_tests/Functional/fo_report.sql
  src/unifiedreport/agent/unifiedreport.php
  src/www/ui/ajax-clearing-view.php
  src/www/ui/change-license-processPost.php
  src/www/ui/core-schema.dat
  src/www/ui/template/ui-clearing-view.js.twig
Labels: needs code review

#1063 fix(schema): check for inherits when drop indexes
  src/lib/php/libschema.php
Labels: needs review

#1053 feat(licenses): add license text to fossology database from SPDX
  install/db/licenseref.sql
  src/nomos/agent/parse.c
  src/nomos/agent_tests/testdata/LastGoodNomosTestfilesScan
  src/nomos/agent_tests/testdata/NomosTestfiles/Intel/Intel-ACPI.txt
Labels: needs test

#1000 fix(delagent): change query which deletes all files with same pfile
  src/delagent/agent/util.c
Labels: needs code review

#928 feat(ui): Colour mapping for risk level in the ui.
  src/www/ui/admin-license-file.php
  src/www/ui/css/fossology.css
  src/www/ui/popup-license.php
  src/www/ui/template/admin_license-upload_form.html.twig
  src/www/ui/template/advice_license-edit.html.twig
  src/www/ui/template/popup_license.html.twig
  src/www/ui/template/riskLevel_select.js.twig
Labels: needs code review, needs test

#1004 fix(search.php): Fix the number of files matching the search criteria
  src/www/ui/search.php
Labels: needs code review, needs test

#1043 fix(perm): reading license information and browsing should be allowed with annonymous user
  src/copyright/ui/ajax-copyright-hist.php
  src/www/ui/async/AjaxExplorer.php
  src/www/ui/async/AjaxFileBrowser.php
  src/www/ui/ui-browse-license.php
  src/www/ui/ui-file-browse.php
Labels: needs code review, needs test

#1049 fix(unifiedreport): Global license appears twice in Main license section
  src/unifiedreport/agent/unifiedreport.php
Labels: needs test

#1068 fix(monkbulk): check the job status when scheduling multiple monkbulks
  src/decider/agent/BulkReuser.php
  src/decider/agent/DeciderAgent.php
  src/decider/agent_tests/Functional/SchedulerTestRunnerMock.php
  src/decider/agent_tests/Functional/schedulerTest.php
  src/decider/ui/DeciderAgentPlugin.php
  src/lib/php/Dao/ClearingDao.php
  src/lib/php/Dao/ShowJobsDao.php
  src/www/ui/ajax-showjobs.php
  src/www/ui/template/ui-showjobs-jobqueue-row.html.twig
Labels: needs code review, needs test

#1055 fix(nonzipUpload): Fixed the query to select every upload
  src/lib/php/Dao/FolderDao.php
  src/www/ui/async/AjaxFolderContents.php
  src/www/ui/template/admin_content_delete.html.twig
  src/www/ui/template/admin_content_move.js.twig
Labels: needs test

#1078 docs(README): Show only master build status
  README.md
Labels: ready

#1074 feat(serverUpload): Check for wildchar during upload
  src/www/ui/page/UploadSrvPage.php
  src/www/ui/template/upload_srv.html.twig
  src/www/ui/template/upload_srv.js.twig
Labels: enhancement, needs code review

#1051 fix(upload-file): get distinct of groupid to insert in perm upload table
  src/lib/php/Dao/UploadPermissionDao.php
Labels: needs code review, needs test
