Repository fossology/fossology, pull requests merged in 2018-12, with the labels that each got.

#1247 feat(info): change general assessment tag from text to textarea
  src/unifiedreport/agent/reportStatic.php
  src/www/ui/ui-view-info.php
Labels: ready

#1252 fix(agent): Reschedule failed agents
  src/lib/php/common-agents.php
  src/lib/php/common-job.php
  src/www/ui/async/ScheduleAgent.php
Labels: needs code review, needs test

#1254 chore(README): add best practices badge
  README.md
Labels: needs code review

#1244 test(monk): Remove unwanted echo from test script
  src/monk/agent_tests/Functional/cliTest.php
Labels: needs code review
