Repository fossology/fossology, pull requests merged in 2018-11, with the labels that each got.

#1234 fix(dashboard): change comparison statements for postgres version
  src/www/ui/admin-dashboard.php
Labels: needs code review, needs test

#1235 fix(debian): Add php7.2 dependencies for Ubuntu Bionic
  debian/control
  debian/fossology-web.postinst
  debian/rules
  utils/fo-installdeps
Labels: WIP, needs code review

#1241 fix(constraints): Remove more faulty constraints
  install/db/dbmigrate_3.3-3.4.php
  src/www/ui/core-schema.dat
Labels: needs code review, needs test

#1242 fix(installdeps): Run child terminals interactively
  utils/fo-installdeps
Labels: needs code review, needs test

#1250 docs(changelog): updating changelog files for 340
  CHANGELOG.md
  debian/changelog
Labels: needs code review
