Repository fossology/fossology, pull requests merged in 2018-08, with the labels that each got.

#1153 feat(fo-installdeps): Drop support for End-of-Life distributions.
  utils/fo-installdeps
Labels: needs code review

#1145 chore(deps): Implemented best practices for bash scripts.
  install/docker-compose.Dockerfile
  src/adj2nest/mod_deps
  src/buckets/mod_deps
  src/delagent/mod_deps
  src/demomod/mod_deps
  src/maintagent/mod_deps
  src/mimetype/mod_deps
  src/nomos/mod_deps
  src/pkgagent/mod_deps
  src/regexscan/mod_deps
  src/scheduler/mod_deps
  src/ununpack/mod_deps
  src/wget_agent/mod_deps
  utils/fo-installdeps
  utils/install_composer.sh
  utils/utils.sh
Labels: needs code review

#1156 fix(wget_agent): Ignore test_proxy_ftp, because it is flaky on travis.
  src/wget_agent/agent_tests/Functional/cliParamsTest4WgetAgent.php
Labels: needs code review

#1096 fix(user): Update user's current group while removing from group
  src/lib/php/Dao/UserDao.php
  src/www/ui/page/AdminGroupUsers.php
Labels: needs code review, needs test

#1154 feat(fo-postinstall): Implemented best practices for bash scripts.
  install/docker-compose.Dockerfile
  install/fo-postinstall.in
Labels: needs code review

#1092 fix(testCases): Fix scheduler and ununpack test cases
  .travis.yml
  Makefile
  src/copyright/agent/copyrightUtils.cc
  src/copyright/agent_tests/Functional/Makefile
  src/copyright/agent_tests/Unit/test_regexConfProvider.cc
  src/decider/agent/BulkReuser.php
  src/decider/agent_tests/Functional/HelperPluginMock.php
  src/delagent/agent_tests/Unit/testRun.c
  src/ninka/Makefile
  src/scheduler/agent_tests/Unit/testDatabase.c
  src/scheduler/agent_tests/Unit/testRun.c
  src/scheduler/agent_tests/Unit/testScheduler.c
  src/scheduler/agent_tests/agents/Makefile
  src/scheduler/agent_tests/agents/fossology.conf.in
  src/testing/db/create_test_database.php
  src/ununpack/agent_tests/Functional/Makefile
  src/ununpack/agent_tests/Functional/cliParamsTest4UnunpackNormal.php
  src/ununpack/agent_tests/Unit/Makefile
  src/ununpack/agent_tests/testdata/testdata.tar.bz2
  src/wget_agent/agent/main.c
  src/wget_agent/agent_tests/Functional/cliParamsTest4WgetAgent.php
  utils/prepare-test
Labels: in review, needs test

#1109 feat(wget_agent): Mask password in log
  src/wget_agent/agent/wget_agent.c
  src/wget_agent/agent/wget_agent.h
Labels: needs code review, needs test

#1157 feat(docker): Merged dockerfiles into one.
  .dockerignore
  Dockerfile
  README.md
  docker-compose.yml
  docker-entrypoint.sh
  install/docker-compose.Dockerfile
  install/docker-compose.docker-entrypoint.sh
  src/testing/docker/default-docker-test.sh
  src/testing/docker/docker-compose-test.sh
Labels: needs code review

#1151 feat(jquery): update jquery, datatable and select2 to latest versions
  src/www/ui/css/jquery.dataTables.css
  src/www/ui/scripts/jquery-3.2.0.min.js
  src/www/ui/scripts/jquery-3.3.1.min.js
  src/www/ui/scripts/jquery.dataTables.min.js
  src/www/ui/scripts/select2.full.min.js
  src/www/ui/template/include/foot.html.twig
Labels: needs code review, needs test

#1173 Fix/test recipie prepare
  .travis.yml
  Makefile
  src/wget_agent/agent_tests/Functional/cliParamsTest4WgetAgent.php
  utils/prepare-test
Labels: needs code review

#1167 chore(travis): Simplified travis.yml
  .travis.yml
Labels: needs code review

#1142 docs(contributing): Added steps to create PR
  CONTRIBUTING.md
Labels: Category: Documentation, needs code review, needs review

#1168 chore(tests): Removed dummy directories for testing.
  src/adj2nest/Makefile
  src/adj2nest/agent_tests/Functional/Makefile
  src/adj2nest/agent_tests/Makefile
  src/adj2nest/agent_tests/Unit/Makefile
  src/buckets/Makefile
  src/buckets/agent_tests/Functional/Makefile
  src/buckets/agent_tests/Makefile
  src/buckets/agent_tests/Unit/Makefile
  src/buckets/ui_tests/Makefile
  src/debug/Makefile
  src/debug/agent_tests/Functional/Makefile
  src/debug/agent_tests/Makefile
  src/debug/agent_tests/Unit/Makefile
  src/debug/ui_tests/Makefile
  src/delagent/ui_tests/Makefile
  src/maintagent/Makefile
  src/maintagent/agent_tests/Functional/Makefile
  src/maintagent/agent_tests/Makefile
  src/maintagent/agent_tests/Unit/Makefile
  src/maintagent/ui_tests/Makefile
  src/mimetype/ui_tests/Makefile
  src/pkgagent/ui_tests/Makefile
  src/readmeoss/Makefile
  src/reportImport/Makefile
  src/reportImport/agent_tests/Makefile
  src/wget_agent/ui_tests/Makefile
Labels: needs code review

#1192 fix(ecc-view): Update ecc_decision table to match other schema
  install/db/dbmigrate_multiple_copyright_decisions.php
  src/lib/php/Dao/CopyrightDao.php
  src/www/ui/core-schema.dat
Labels: needs code review, needs test

#1189 fix(fo-installdeps): Allow running without the option '-y'.
  src/delagent/mod_deps
  src/mimetype/mod_deps
  src/pkgagent/mod_deps
  src/scheduler/mod_deps
  src/ununpack/mod_deps
  src/wget_agent/mod_deps
  utils/fo-installdeps
  utils/prepare-test
Labels: needs code review
