Repository fossology/fossology, pull requests merged in 2018-03, with the labels that each got.

#970 CSV import from obligations: improve checks while associating Licenses
  src/lib/php/Application/ObligationCsvImport.php
  src/www/ui/admin-obligation-file.php
Labels: needs code review, needs test

#989 solved issue #988
  src/wget_agent/agent/wget_agent.c
Labels: needs test

#998 docs(vagrant): add vagrant setup documentation
  README.md
Labels: needs code review, needs test

#1047 fix(phptestcase): Remove PHP 5.5 test case from travis
  .travis.yml
Labels: needs review
