Repository fossology/fossology, pull requests merged in 2018-05, with the labels that each got.

#1067 fix(import-csv): syntax error in importing license-csv
  src/lib/php/Application/LicenseCsvImport.php
  src/www/ui/template/admin_license_from_csv.html.twig
Labels: needs code review, needs test

#1066 fix(licenseUpdate): update the license parameters with same shortname
  src/www/ui/admin-license-file.php
  src/www/ui/template/admin_license-upload_form.html.twig
Labels: needs code review, needs test

#1082 Fix regular expression regressions, similar to #879
  src/nomos/agent/STRINGS.in
Labels: needs test

#1005 feat(email): Added support for agent status in email
  debian/control
  install/defconf/fossology.conf.in
  install/defconf/samplefooter.txt
  install/defconf/sampleheader.txt
  src/lib/php/common-sysconfig.php
  src/scheduler/agent/Makefile
  src/scheduler/agent/database.c
  src/scheduler/agent/emailformatter.c
  src/scheduler/agent/emailformatter.h
  src/scheduler/agent/sqlstatements.h
  src/www/ui/admin-config.php
  src/www/ui/core-schema.dat
  utils/fo-installdeps
Labels: needs code review, needs test

#1072 fix(author): Fix multiple entries in author table
  install/db/Makefile
  install/db/dbmigrate_copyright-author.php
  install/db/resequence_author_table.php
  install/fossinit.php
  src/copyright/agent/copyright.cc
  src/copyright/agent/database.cc
  src/www/ui/core-schema.dat
Labels: ready

#1081 feat(copyright): New JSON hpp version
  install/scripts/install-json-hpp.sh
Labels: enhancement, needs code review, needs test

#1077 feat(addLicense): Retain previous request values
  src/www/ui/admin-license-file.php
Labels: needs code review

#1104 feat(readmeoss): add license shortname above the license text
  src/readmeoss/agent/readmeoss.php
Labels: needs code review

#1102 fix(schema): check with the table property for current scheme
  src/cli/schema-export.php
  src/lib/php/libschema.php
  src/www/ui/core-schema.dat
Labels: needs test
