Repository fossology/fossology, pull requests merged in 2018-10, with the labels that each got.

#1174 docs(nomos): Add doxygen comments for nomos
  src/dox.c
  src/nomos/agent/DMalloc.c
  src/nomos/agent/doctorBuffer_utils.c
  src/nomos/agent/encode.c
  src/nomos/agent/licenses.c
  src/nomos/agent/list.c
  src/nomos/agent/nomos.c
  src/nomos/agent/nomos.h
  src/nomos/agent/nomos_gap.c
  src/nomos/agent/nomos_regex.c
  src/nomos/agent/nomos_utils.c
  src/nomos/agent/nomos_utils.h
  src/nomos/agent/parse.c
  src/nomos/agent/process.c
  src/nomos/agent/standalone.c
  src/nomos/agent/standalone.h
  src/nomos/agent/util.c
  src/nomos/agent_tests/Functional/CommonCliTest.php
  src/nomos/agent_tests/Functional/Nomos-fun-test.php
  src/nomos/agent_tests/Functional/OneShot-JSON.php
  src/nomos/agent_tests/Functional/OneShot-Oracle-Berkeley-DB.php
  src/nomos/agent_tests/Functional/OneShot-affero.php
  src/nomos/agent_tests/Functional/OneShot-bsd.php
  src/nomos/agent_tests/Functional/OneShot-empty.php
  src/nomos/agent_tests/Functional/OneShot-gpl3.php
  src/nomos/agent_tests/Functional/OneShot-lgpl2.1.php
  src/nomos/agent_tests/Functional/OneShot-multiFile.php
  src/nomos/agent_tests/Functional/OneShot-none.php
  src/nomos/agent_tests/Unit/run_tests.c
  src/nomos/agent_tests/Unit/test_DoctoredBuffer.c
  src/nomos/agent_tests/Unit/test_nomos_gap.c
  src/nomos/ui/agent-nomos-once.php
  src/nomos/ui/agent-nomos.php
  src/nomos/ui/ajax-filelic.php
  src/nomos/ui/nomos-diff.php
  src/ununpack/agent_tests/Unit/test_FindCmd.c
  src/ununpack/agent_tests/Unit/test_TraverseStart.c
Labels: needs code review

#1181 Improved PHP 7.2 Support
  .travis.yml
  src/cli/tests/test_fo_copyright_list.php
  src/composer.json
  src/composer.lock
  src/nomos/agent_tests/Functional/tests.xml
  src/phpunit.xml
Labels: needs test

#1228 fix(core-schema): drop constraint from clearing_event and create migr…
  src/www/ui/core-schema.dat
Labels: ready

#1215 fix(tests): fix PHPCS and phpunit testcases for deciderjob and reuser
  .gitignore
  src/deciderjob/agent_tests/Functional/schedulerTest.php
  src/lib/php/Dao/FolderDao.php
  src/lib/php/Dao/LicenseDao.php
  src/lib/php/Dao/TreeDao.php
  src/lib/php/Db/DbManager.php
  src/lib/php/Proxy/LicenseViewProxy.php
  src/lib/php/UI/MenuRenderer.php
  src/monk/ui/admin-monk-revision.php
  src/phpunit.xml
  src/reuser/agent/Makefile
  src/reuser/agent_tests/Functional/schedulerTest.php
Labels: needs code review, needs test

#1230 fix(resequence): Check the column name from DB
  install/db/dbmigrate_3.3-3.4.php
  install/db/resequence_author_table.php
  install/fossinit.php
  src/www/ui/core-schema.dat
Labels: needs code review, needs test

#1226 feat(copyright): Use package based dependency for json
  .travis.yml
  Dockerfile
  fossology_doxygen.conf
  install/scripts/install-json-hpp.sh
  src/copyright/agent/.gitignore
  src/copyright/agent/Makefile
  src/copyright/agent/copyright.cc
  src/copyright/agent/copyrightUtils.cc
  src/copyright/agent/copyrightUtils.hpp
  src/copyright/mod_deps
Labels: needs code review, needs test

#1231 fix(postgresql): Fixed postgresql version to 9.6 and use a volume for its data.
  docker-compose.yml
Labels: needs code review
