Repository fossology/fossology, pull requests merged in 2018-07, with the labels that each got.

#1126 fix(sysconfig): Change structure of values
  src/lib/php/common-sysconfig.php
Labels: needs code review, needs test

#1135 docs(issue): Issue and PR template for new requests
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: needs code review, needs review, org

#1101 feat(licenses): add license test to licenseref.sql from SPDX
  install/db/licenseref.sql
Labels: needs code review

#1125 feat(bulk): inclusion of licensetext, acknowledgement and comment
  src/decider/agent/BulkReuser.php
  src/lib/php/Dao/LicenseDao.php
  src/monk/agent/monkbulk.c
  src/monk/agent/monkbulk.h
  src/readmeoss/agent/readmeoss.php
  src/unifiedreport/agent/unifiedreport.php
  src/www/ui/change-license-bulk.php
  src/www/ui/core-schema.dat
  src/www/ui/scripts/change-license-browse.js
  src/www/ui/scripts/change-license-common.js
  src/www/ui/scripts/change-license-view.js
  src/www/ui/scripts/jquery.plainmodal.min.js
  src/www/ui/scripts/ui-clearing-view_bulk.js
  src/www/ui/template/ui-clearing-view.html.twig
  src/www/ui/template/ui-clearing-view.js.twig
  src/www/ui/template/ui-clearing-view_bulk.html.twig
Labels: needs code review, needs test

#832 feat(license_administration): add sorting, update datatable
  src/www/ui/admin-license-file.php
  src/www/ui/css/fossology.css
  src/www/ui/css/jquery.dataTables.css
  src/www/ui/images/dataTable/back_disabled.png
  src/www/ui/images/dataTable/back_enabled.png
  src/www/ui/images/dataTable/back_enabled_hover.png
  src/www/ui/images/dataTable/forward_disabled.png
  src/www/ui/images/dataTable/forward_enabled.png
  src/www/ui/images/dataTable/forward_enabled_hover.png
  src/www/ui/images/dataTable/sort_asc.png
  src/www/ui/images/dataTable/sort_asc_disabled.png
  src/www/ui/images/dataTable/sort_both.png
  src/www/ui/images/dataTable/sort_desc.png
  src/www/ui/images/dataTable/sort_desc_disabled.png
  src/www/ui/scripts/jquery.dataTables.min.js
  src/www/ui/template/admin_license_file.html.twig
  src/www/ui/template/admin_license_file.js.twig
Labels: needs code review

#1132 fix typo for ninka script
  src/cli/fo_ninka_license_list.php
Labels: needs test

#1139 fix(pkgagent): Added support for RPM >= 4.14
  src/pkgagent/agent/Makefile
  src/pkgagent/agent/main.c
  src/pkgagent/agent/pkgagent.c
  src/pkgagent/agent_tests/Unit/Makefile
  src/pkgagent/agent_tests/Unit/testGetMetadata.c
Labels: needs code review

#1141 fix(dataTables): Update datatable objects to 1.10
  src/copyright/ui/template/histTable.js.twig
  src/www/ui/scripts/browse.js
  src/www/ui/template/browse_file.js.twig
  src/www/ui/template/file-browse.js.twig
  src/www/ui/template/ui-browse.js.twig
  src/www/ui/template/ui-clearing-view.js.twig
  src/www/ui/template/ui-job-show.js.twig
Labels: needs code review, needs test

#1118 feat(licenses): exceptions detection restructured
  src/nomos/agent/STRINGS.in
  src/nomos/agent/parse.c
  src/nomos/agent_tests/testdata/LastGoodNomosTestfilesScan
  src/nomos/agent_tests/testdata/NomosTestfiles/BSD/BSD-3-Clause-LBNL_a.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/CMU/Bellcore.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/Dual-license/Apache-2.0_or_CC0-1.0.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/GPL/GPL-3.0+_WITH_linking-exception.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/LGPL/LGPL-2.0+_WITH_GCC-exception.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/LGPL/LGPL-2.1+_WITH_linking-exception.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/MPL/LICENSE.TXT
  src/nomos/agent_tests/testdata/NomosTestfiles/Motorola/Motorola-Mobile-SLA.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/Motorola/Motorola.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/OFL/ubuntu-font-1.0.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/SPDX/Autoconf-exception-2.0.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/SPDX/Autoconf-exception-3.0.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/SPDX/Bison-exception-2.2.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/SPDX/Bootloader-exception.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/SPDX/CLISP-exception-2.0.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/SPDX/Classpath-exception-2.0.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/SPDX/DigiRule-FOSS-exception.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/SPDX/FLTK-exception.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/SPDX/Fawkes-Runtime-exception.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/SPDX/GCC-exception-2.0.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/SPDX/GCC-exception-3.1.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/SPDX/LLVM-exception
  src/nomos/agent_tests/testdata/NomosTestfiles/SPDX/LLVM-exception.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/SPDX/LZMA-exception.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/SPDX/Libtool-exception.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/SPDX/Linux-syscall-note.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/SPDX/Nokia-Qt-exception-1.1.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/SPDX/OCCT-exception-1.0.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/SPDX/OpenJDK-assembly-exception-1.0
  src/nomos/agent_tests/testdata/NomosTestfiles/SPDX/OpenJDK-assembly-exception-1.0.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/SPDX/Qhull.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/SPDX/Qwt-exception-1.0.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/SPDX/WxWindows-exception-3.1.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/SPDX/eCos-exception-2.0.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/SPDX/freertos-exception-2.0.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/SPDX/gnu-javamail-exception.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/SPDX/i2p-gpl-java-exception.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/SPDX/mif-exception.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/SPDX/openvpn-openssl-exception.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/SPDX/u-boot-exception-2.0.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/Zeus/Zeus.txt
Labels: needs code review

#1138 fix(copyright): match copyright statements in full
  src/copyright/agent/copyright.conf
Labels: needs code review, needs test

#1107 feat(keyword-agent) : new-keyword-agent
  .gitignore
  src/copyright/Makefile
  src/copyright/agent/Makefile
  src/copyright/agent/copyrightUtils.cc
  src/copyright/agent/identity.hpp
  src/copyright/agent/keyword.conf
  src/copyright/agent_tests/Functional/cli_test.sh
  src/copyright/agent_tests/Unit/test_scanners.cc
  src/copyright/keyword.conf
  src/copyright/ui/KeywordView.php
  src/copyright/ui/Makefile
  src/copyright/ui/agent-keyword.php
  src/copyright/ui/ajax-copyright-hist.php
  src/copyright/ui/keyword-hist.php
  src/copyright/ui/list.php
  src/lib/php/Dao/CopyrightDao.php
  src/lib/php/Data/Highlight.php
  src/www/ui/ajax-clearing-view.php
  src/www/ui/core-schema.dat
Labels: enhancement, needs code review
