Repository fossology/fossology, pull requests merged in 2019-11, with the labels that each got.

#1515 chore(unifiedReport): change phpword to a latest version
  src/composer.json
  src/composer.lock
Labels: needs test

#1521 Feat/spasht fix code
  .gitignore
  src/composer.lock
  src/lib/php/Dao/SpashtDao.php
  src/nomos/agent_tests/testdata/LastGoodNomosTestfilesScan
  src/nomos/agent_tests/testdata/NomosTestfiles/MPL/License-lowercase.txt
  src/spasht/agent/SpashtAgent.php
  src/spasht/ui/agent-spasht.php
  src/spasht/ui/ajax-spasht-copyright-hist.php
  src/spasht/ui/template/agent_spasht.js.twig
  src/spasht/ui/template/agent_spasht_advanceSearch_form.html.twig
  src/spasht/ui/template/agent_spasht_ui_content.html.twig
  src/spasht/ui/template/agent_spasht_ui_tabs.html.twig
  src/spasht/ui/template/show_definitions.html.twig
  src/spasht/ui/template/show_details_table.html.twig
  src/spasht/ui/template/show_uploads_table.html.twig
  src/spasht/ui/ui-spasht.php
  src/www/ui/core-schema.dat
  src/www/ui/css/spasht.css
Labels: ready

#1525 chore(installdeps): remove php-yaml from os level and add it to composer
  debian/control
  src/composer.json
  src/composer.lock
  src/www/ui/api/Controllers/VersionController.php
  src/www/ui/api/documentation/openapi.yaml
  utils/fo-installdeps
Labels: needs code review, needs test

#1413 fix(db): Optimize license browse queries
  src/lib/php/Dao/ClearingDao.php
  src/lib/php/Dao/HighlightDao.php
  src/lib/php/Proxy/UploadTreeProxy.php
  src/www/ui/ui-clearing-view.php
Labels: needs code review, needs test

#1508 chore(docker-compose): harmonize versions with sw360chores
  docker-compose.yml
Labels: needs test

#1531 chore(composer.json): updated symfony/dependency-injection version
  src/composer.json
  src/composer.lock
Labels: needs test
