Repository fossology/fossology, pull requests merged in 2019-05, with the labels that each got.

#1339 fix(nomos): nomos crash (#1337)
  src/nomos/agent/nomos.h
  src/nomos/agent/nomos_regex.c
Labels: ready

#1325 feat(ci): Run travis jobs on Xenial
  .travis.yml
  src/delagent/agent_tests/Unit/testRun.c
  src/scheduler/agent/job.c
  src/wget_agent/agent_tests/Unit/wget_agent/testDBLoadGold.c
Labels: WIP, needs code review

#1305 fix(scheduler): Respect max run limit of agents
  src/scheduler/agent/agent.c
  src/scheduler/agent/agent.h
  src/scheduler/agent/defconf/init.d/fossology.in
  src/scheduler/agent/scheduler.c
Labels: needs code review, needs test

#1352 chore(travis): Set pipefail in Travis CI PHPUnit on PHP 7.0
  .travis.yml
Labels: needs code review

#1354 fix(unifiedreport): fixed issue with irrelevant file display
  src/lib/php/Report/LicenseIrrelevantGetter.php
Labels: ready

#1349 feat(spdx2): SPDX output does not yet show license comments
  src/spdx2/agent/spdx2.php
  src/spdx2/agent/template/spdx2-file.xml.twig
  src/spdx2/agent/template/spdx2tv-file.twig
  src/www/ui/admin-upload-edit.php
  src/www/ui/core-schema.dat
  src/www/ui/template/admin_upload_edit.html.twig
  src/www/ui/template/ui-view-info.html.twig
  src/www/ui/ui-view-info.php
Labels: ready

#1312 fix(copyright): fix php notices in copyright hist view
  src/copyright/ui/ajax-copyright-hist.php
  src/copyright/ui/template/histTable.js.twig
  src/lib/php/Dao/UploadDao.php
Labels: ready

#1338 refac(showjobs): Refactor code to send JSON
  src/lib/php/Dao/ShowJobsDao.php
  src/lib/php/Dao/test/ShowJobsDaoTest.php
  src/lib/php/Report/tests/ClearedGetterCommonTest.php
  src/www/ui/Makefile
  src/www/ui/async/AjaxJobStatus.php
  src/www/ui/async/AjaxShowJobs.php
  src/www/ui/css/showjobs.css
  src/www/ui/template/ui-showjobs-jobqueue-row.html.twig
  src/www/ui/template/ui-showjobs.js.twig
Labels: enhancement, needs code review

#1360 feat(ui): Add user descripption of available user in group management page
  src/www/ui/page/AdminGroupUsers.php
Labels: ready

#1329 fix(obligations): fix UI and connected db to dropdown menu
  src/www/ui/admin-obligation-file.php
  src/www/ui/template/admin_obligation-upload_form.html.twig
  src/www/ui/template/include/foot.html.twig
Labels: ready
