Repository fossology/fossology, pull requests merged in 2019-03, with the labels that each got.

#1294 fix(Vagrantfile): Enable mod rewrite in vagrant for REST API
  Vagrantfile
Labels: needs code review

#1296 fix(trac.php): correct typo `fLAse` instead of `fALse`
  utils/freshmeat/trac.php
Labels: needs code review

#1302 chore(docker): update dockerignore
  .dockerignore
Labels: needs code review

#1284 feat(licenses): creative commons detection rewritten. Bug fixes.
  src/nomos/agent/STRINGS.in
  src/nomos/agent/parse.c
  src/nomos/agent_tests/testdata/LastGoodNomosTestfilesScan
  src/nomos/agent_tests/testdata/NomosTestfiles/Apache/Apache-2.0_j.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/CC/CC-BY-1.0_ref.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/CC/CC-BY-2.0_ref.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/CC/CC-BY-2.5_ref.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/CPL/CPL-1.0_ref_a.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/Dual-license/EPL-1.0_or_MPL-2.0_1.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/Dual-license/EPL-1.0_or_MPL-2.0_2.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/Dual-license/EPL-2.0_or_GPL-2.0_or_LGPL-2.1.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/Dual-license/GPL-2.0_or_BSD.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/Dual-license/GPL-2.0_or_Linux-OpenIB_1.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/Dual-license/GPL-2.0_or_Linux-OpenIB_2.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/Dual-license/MIT_or_GPL-3.0.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/GPL/GPL-2.0_j.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/GPL/universal-foss-exception.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/GPL/universal-foss-exception_url.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/HP/hp-snmp-pp.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/HP/snmp_pp.cpp
  src/nomos/agent_tests/testdata/NomosTestfiles/ICU/ICU-license-3.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/IPTC/IPTC.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/MIT/MIT-0.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/MIT/MIT-ref_i.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/No_license_found/GPL-Ghostscript_a.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/No_license_found/GPL-Ghostscript_b.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/OZPLB/OZPLB_ref_a.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/Qwt/Qwt_ref_a.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/SPDX/MIT-0
  src/nomos/agent_tests/testdata/NomosTestfiles/UCAR/UCAR.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/Zlib/zlib_ref_a.txt
Labels: ready

#1297 fix(restApi): Fix for missing plugins
  src/www/ui/api/Middlewares/FossologyInitMiddleware.php
  src/www/ui/api/Middlewares/RestAuthMiddleware.php
  src/www/ui/api/index.php
Labels: needs code review, needs test

#1290 feat(rest): Use bearer auth instead of basic
  install/src-install-apache-example.conf
  src/composer.json
  src/composer.lock
  src/lib/php/Exceptions/DuplicateTokenKeyException.php
  src/lib/php/Exceptions/DuplicateTokenNameException.php
  src/lib/php/common-sysconfig.php
  src/lib/php/services.xml.in
  src/www/ui/api/Controllers/AuthController.php
  src/www/ui/api/Controllers/FolderController.php
  src/www/ui/api/Controllers/ReportController.php
  src/www/ui/api/Controllers/UploadController.php
  src/www/ui/api/Helper/AuthHelper.php
  src/www/ui/api/Helper/DbHelper.php
  src/www/ui/api/Helper/RestHelper.php
  src/www/ui/api/Middlewares/RestAuthMiddleware.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui/async/AjaxManageToken.php
  src/www/ui/core-schema.dat
  src/www/ui/css/access-token.css
  src/www/ui/scripts/user-edit.js
  src/www/ui/template/user_edit.html.twig
  src/www/ui/user-del-helper.php
  src/www/ui/user-del.php
  src/www/ui/user-edit.php
Labels: needs test

#1317 docs(changelog): updating changelog files for 350-rc1
  CHANGELOG.md
  debian/changelog
Labels: needs code review
