Repository fossology/fossology, pull requests merged in 2019-08, with the labels that each got.

#1311 feat(copyright): Show text findings in copyright-hist
  src/copyright/ui/HistogramBase.php
  src/copyright/ui/TextFindingsAjax.php
  src/copyright/ui/ajax-copyright-hist.php
  src/copyright/ui/copyright-hist.php
  src/copyright/ui/email-hist.php
  src/copyright/ui/list.php
  src/copyright/ui/template/copyrighthist.html.twig
  src/copyright/ui/template/copyrighthist_scripts.html.twig
  src/copyright/ui/template/copyrighthist_tables.html.twig
  src/copyright/ui/template/emailhist_tables.html.twig
  src/copyright/ui/template/histTable.js.twig
  src/lib/php/Dao/CopyrightDao.php
  src/lib/php/Dao/UploadDao.php
Labels: needs code review, needs test

#1348 chore(debian): Fix lintian erros and warnings
  Makefile.conf
  Makefile.process
  debian/changelog
  debian/compat
  debian/control
  debian/fossology-common.README.Debian
  debian/rules
  debian/source/lintian-overrides
  debian/upstream/metadata
  debian/watch
  install/INSTALL
  src/decider/agent/Makefile
  src/deciderjob/agent/Makefile
  src/readmeoss/agent/Makefile
  src/reportImport/agent/Makefile
  src/reuser/agent/Makefile
  src/spdx2/agent/Makefile
  src/unifiedreport/agent/Makefile
  src/www/ui/scripts/ui-clearing-view_bulk.js
Labels: enhancement

#1400 fix(pfile): SHA256 is still optional
  install/db/dbmigrate_3.5-3.6.php
  src/ununpack/agent/utils.c
  src/wget_agent/agent/wget_agent.c
Labels: ready

#1426 hotfix(process): Fix the PHP agent installation
  Makefile.conf
  Makefile.process
  src/decider/agent/Makefile
  src/deciderjob/agent/Makefile
  src/readmeoss/agent/Makefile
  src/reportImport/agent/Makefile
  src/reuser/agent/Makefile
  src/spdx2/agent/Makefile
  src/unifiedreport/agent/Makefile
Labels: needs code review, needs test

#1428 Adding changelog files for 3.6.0-rc1 pre-release
  CHANGELOG.md
  debian/changelog
Labels: enhancement

#1446 feat(unifiedreport): add candidate licenses to the list of obligations
  src/lib/php/Dao/LicenseDao.php
  src/unifiedreport/agent/obligations.php
Labels: ready

#1445 fix(obligation): add default value if the obligation type and classif…
  src/lib/php/BusinessRules/ObligationMap.php
  src/www/ui/admin-obligation-file.php
Labels: ready

#1442 fix(copyright): Check if empty decision sent
  src/copyright/ui/Xpview.php
Labels: ready

#1430 fix(ojo): Remove call to omitEndingLineFeed on json cpp < 0.7
  src/ojo/agent/OjoUtils.cc
  src/ojo/agent/directoryScan.cc
  src/ojo/agent/directoryScan.hpp
Labels: needs code review, needs test

#1444 fix(dbMigrate): Fix PHP syntax error
  install/db/dbmigrate_3.5-3.6.php
Labels: ready

#1431 fix(copyright): show more than 100 copyrights on one page
  src/copyright/ui/template/histTable.js.twig
Labels: ready

#1425 fix(src/ununpack/agent/utils.c) Embed SHA256 implementation,
  src/ununpack/agent/Makefile
  src/ununpack/agent/sha2.c
  src/ununpack/agent/sha2.h
  src/ununpack/agent/utils.c
Labels: ready
