Repository fossology/fossology, pull requests merged in 2019-12, with the labels that each got.

#1532 fix(obligation): Associate all candidate licenses with same name
  install/db/Makefile
  install/db/dbmigrate_3.6-3.7.php
  install/fossinit.php
  src/lib/php/Application/ObligationCsvImport.php
  src/lib/php/BusinessRules/ObligationMap.php
  src/www/ui/admin-obligation-file.php
Labels: needs test

#1537 fix(copyright): Wait for ajax calls during bulk replace
  src/copyright/ui/template/histTable.js.twig
Labels: ready

#1538 fix(admin): Allow read user to edit user
  src/www/ui/template/user_edit.html.twig
  src/www/ui/user-edit.php
Labels: ready

#1546 fix(build-dep): Add PHP-CLI as build dependency
  utils/fo-installdeps
Labels: ready

#1551 feat(conf): add obligations to consider a particular license for its …
  src/unifiedreport/agent/obligations.php
  src/www/ui/core-schema.dat
  src/www/ui/template/ui-report-conf.html.twig
  src/www/ui/ui-report-conf.php
Labels: needs code review, needs test

#1556 fix(ui): decision and scope for licenses
  src/www/ui/change-license-processPost.php
  src/www/ui/template/ui-clearing-view_rhs.html.twig
  src/www/ui/ui-clearing-view.php
Labels: needs code review, needs test

#1554 feat(unifiedReport): exclude scanner found copyrights of irrelevent f…
  src/lib/php/Dao/CopyrightDao.php
  src/lib/php/Report/XpClearedGetter.php
Labels: ready

#1500 fix(rest): Hide sensitive user info
  src/www/ui/api/Helper/DbHelper.php
  src/www/ui/api/Models/User.php
  src/www/ui/api/documentation/openapi.yaml
Labels: needs code review, needs test
