Repository fossology/fossology, pull requests merged in 2019-09, with the labels that each got.

#1456 fix(ajaxExplorer): Reduce view creation
  src/lib/php/BusinessRules/AgentLicenseEventProcessor.php
  src/www/ui/async/AjaxExplorer.php
  src/www/ui/core-schema.dat
Labels: ready

#1469 fix(importReport): update easyRDF to a stable version
  src/composer.json
  src/composer.lock
  src/reportImport/agent/ReportImportAgent.php
Labels: needs code review

#1415 feat(api): Return job's ETA and status
  src/lib/php/services.xml.in
  src/www/ui/api/Controllers/JobController.php
  src/www/ui/api/Helper/DbHelper.php
  src/www/ui/api/Helper/RestHelper.php
  src/www/ui/api/Models/Analysis.php
  src/www/ui/api/Models/Job.php
  src/www/ui/api/documentation/openapi.yaml
Labels: needs test

#1433 fix(testing/db/c): Prevent buffer overflows
  src/testing/db/c/libfodbreposysconf.c
Labels: ready

#1434 fix(pkgagent): Avoid possible buffer overrun with strncpy
  src/pkgagent/agent/pkgagent.c
Labels: ready

#1435 fix(mimetype): Fix usage of strncpy, remove memset
  src/mimetype/agent/mimetype.c
Labels: ready

#1436 fix(delagent): Fix possible buffer overrun
  src/delagent/agent/util.c
Labels: ready

#1447 Feat/spasht 1.0
  src/Makefile
  src/composer.json
  src/composer.lock
  src/spasht/Makefile
  src/spasht/agent/Makefile
  src/spasht/agent/spasht.php
  src/spasht/agent/version.php.in
  src/spasht/spasht.conf
  src/spasht/ui/Makefile
  src/spasht/ui/agent-spasht.php
  src/spasht/ui/services.php
  src/spasht/ui/template/agent_spasht.html.twig
  src/spasht/ui/template/agent_spasht_advanceSearch_form.html.twig
  src/spasht/ui/template/agent_spasht_search.html.twig
  src/spasht/ui/template/show_definitions.html.twig
  src/spasht/ui/ui-spasht.php
  src/www/ui/core-schema.dat
  src/www/ui/css/spasht.css
Labels: GSOC-19

#1449 chore(ninka): Remove Ninka packaging from master
  debian/rules
  src/Makefile
Labels: needs code review, needs test

#1480 feat(pbconf): adapt to pb 0.15 and new fossology 3.3+
  pbconf/fossology.yml
  pbconf/fossology/pbve.pre
  pbconf/fossology/rpm/fossology.spec
  pbconf/pbfilter/all.yml
  pbconf/pbfilter/centos-6.yml
  pbconf/pbfilter/centos-7.yml
  pbconf/pbfilter/debian-6.yml
  pbconf/pbfilter/debian-7.yml
  pbconf/pbfilter/debian-8.yml
  pbconf/pbfilter/debian-9.yml
  pbconf/pbfilter/fedora-15.yml
  pbconf/pbfilter/fedora-17.yml
  pbconf/pbfilter/fedora-18.yml
  pbconf/pbfilter/fedora.yml
  pbconf/pbfilter/md.yml
  pbconf/pbfilter/rhel.yml
  pbconf/pbfilter/rpm.yml
  pbconf/pbfilter/ubuntu.yml
Labels: Category: Package Build, WIP

#1438 fix(lib/c): Prevent possible buffer overflow/-run
  src/lib/c/libfossdb.c
  src/lib/c/libfossrepo.c
Labels: needs test
