Repository fossology/fossology, pull requests merged in 2019-04, with the labels that each got.

#1313 fix: Add ubuntu log file to gitignore
  .gitignore
Labels: needs code review

#1319 fix(apache): Add rewrite string to apache conf
  Dockerfile
  Vagrantfile
  install/fo-apache.conf
  install/fo-postinstall.in
Labels: needs code review, needs test

#1321 docs(changelog): updating changelog files for 350-rc2
  CHANGELOG.md
  debian/changelog
Labels: needs code review

#1327 chore(docker): bump docker base image to stretch
  Dockerfile
  utils/fo-installdeps
Labels: needs code review, needs squash, needs test

#1331 chore(changelog): Changes for release 3.5.0
  CHANGELOG.md
  debian/changelog
Labels: needs code review

#1332 fix(fo-installdeps): there is a wrong failing default case
  utils/fo-installdeps
Labels: ready

#1336 fix(strings): correct typo
  src/nomos/agent/STRINGS.in
Labels: ready

#1333 Refactor Travis CI configuration
  .travis.yml
Labels: ready

#1335 feat(cp2foss): cp2foss prints out FolderPk as well
  src/cli/cp2foss.php
Labels: needs code review, needs test

#1310 feat(licenses): Apache detection code restructured. Apache and AGPL n…
  src/nomos/agent/STRINGS.in
  src/nomos/agent/parse.c
  src/nomos/agent_tests/testdata/LastGoodNomosTestfilesScan
  src/nomos/agent_tests/testdata/NomosTestfiles/AGPL/AGPL-3.0_ref_d.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/AGPL/AGPL-3.0_ref_e.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/Apache/Apache-1.0.c
  src/nomos/agent_tests/testdata/NomosTestfiles/Apache/Apache-2.0_k.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/Apache/Apache-2.0_l.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/BSD/BSD-2-Clause_ref_b.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/BSD/BSD-2-Clause_ref_c.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/BSD/BSD-2-Clause_ref_d.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/BSD/BSD-3-Clause-Clear.c
  src/nomos/agent_tests/testdata/NomosTestfiles/BSD/BSD-3-Clause-Clear.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/BSD/New-BSD_ref_a.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/CC/CC-BY-SA-3.0c.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/CPL/CPL-1.0_ref_b.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/Dual-license/Apache-2.0_or_CC-BY-4.0.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/Dual-license/Apache-2.0_or_LGPL-3.0+.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/GPL/GPL-2.0+_e.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/MIT/MIT-ref_j.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/MIT/MIT-style_b.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/No_license_found/gimp-file-extension.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/No_license_found/java1.class
  src/nomos/agent_tests/testdata/NomosTestfiles/No_license_found/java2.class
  src/nomos/agent_tests/testdata/NomosTestfiles/Public-domain/Public-domain-ref_b.txt
  src/nomos/agent_tests/testdata/NomosTestfiles/SPDX/copyleft-next-0.3.0
Labels: needs clarification

#1316 feat(unifiedReport): seperate user and scanner findings of copyrights
  src/composer.json
  src/composer.lock
  src/lib/php/Report/ClearedGetterCommon.php
  src/lib/php/Report/LicenseIrrelevantGetter.php
  src/lib/php/Report/LicenseMainGetter.php
  src/unifiedreport/agent/reportStatic.php
  src/unifiedreport/agent/unifiedreport.php
Labels: needs code review

#1324 feat(datatable): add select plugin of datatable to change paging
  src/copyright/ui/template/copyrighthist.html.twig
  src/copyright/ui/template/histTable.js.twig
  src/copyright/ui/template/ui-cp-view.html.twig
  src/www/ui/scripts/jquery.dataTables.select.js
  src/www/ui/template/admin_license_candidate.html.twig
  src/www/ui/template/admin_license_file.html.twig
  src/www/ui/template/admin_license_file.js.twig
  src/www/ui/template/advice_license.html.twig
  src/www/ui/template/browse.html.twig
  src/www/ui/template/browse_file.js.twig
  src/www/ui/template/browse_license-lic_hist.js.twig
  src/www/ui/template/file-browse.html.twig
  src/www/ui/template/file-browse.js.twig
  src/www/ui/template/ui-browse.html.twig
  src/www/ui/template/ui-browse.js.twig
  src/www/ui/template/upload_permissions.html.twig
Labels: needs code review

#1320 feat(api): Cache Slim DI container
  src/composer.json
  src/composer.lock
  src/lib/php/common-container.php
  src/www/ui/api/index.php
Labels: ready

#1314 fix(ui): Show license findings for folder with single child
  src/www/ui/async/AjaxExplorer.php
Labels: ready
