Repository fossology/fossology, pull requests merged in 2019-06, with the labels that each got.

#1356 feat(spdx2): Ignore files with no info in SPDX reports
  src/lib/php/Dao/UploadDao.php
  src/spdx2/agent/spdx2.php
  src/www/ui/admin-upload-edit.php
  src/www/ui/core-schema.dat
  src/www/ui/template/admin_upload_edit.html.twig
  src/www/ui/template/ui-report-conf.html.twig
  src/www/ui/template/ui-view-info.html.twig
  src/www/ui/ui-report-conf.php
  src/www/ui/ui-view-info.php
Labels: needs code review, needs test

#1370 feat(db): Store SHA256 of the uploaded file
  install/db/dbmigrate_3.5-3.6.php
  src/spdx2/agent_tests/Functional/fo_report.sql
  src/unifiedreport/agent_tests/Functional/fo_report.sql
  src/ununpack/agent/utils.c
  src/ununpack/agent_tests/Unit/test_DBInsert.c
  src/wget_agent/agent/wget_agent.c
  src/www/ui/core-schema.dat
  src/www/ui/template/ui-view-info.html.twig
  src/www/ui/ui-view-info.php
Labels: GSOC-19, needs code review

#1358 fix(admin-license-file): Fix update conclusion to self
  src/www/ui/admin-license-file.php
Labels: needs code review, needs test

#1376 fix(pfile): Fix warnings in ununpack and wget
  src/ununpack/agent/utils.c
  src/wget_agent/agent/wget_agent.c
Labels: needs code review, needs test

#1380 fix(reportConf): include correct array from to fix report conf
  src/www/ui/ui-report-conf.php
Labels: needs test

#1383 feat(dbmigrate_3.5-3.6): add limit to process number of records
  install/db/dbmigrate_3.5-3.6.php
Labels: ready

#1386 fix(showjobs): Check empty for allusers before updating
  src/www/ui/async/AjaxShowJobs.php
Labels: ready

#1384 fix(copyright): Fix pagination of copyright-list
  src/copyright/ui/list.php
Labels: ready
