Repository fossology/fossology, pull requests merged in 2019-10, with the labels that each got.

#1406 fix(fo_nomos_license_list.php): change function name
  src/cli/fo_nomos_license_list.php
Labels: needs test

#1491 fix(geekyscan): make full job report link more descriptive
  src/www/ui/async/AjaxShowJobs.php
Labels: ready

#1488 feat(spdx): add user found copyrights to SPDX reports
  src/spdx2/agent/spdx2.php
Labels: needs code review, needs test

#1479 fix(groups): add validations and remove CONSTRAINTS
  src/www/ui/core-schema.dat
  src/www/ui/page/AdminGroupUsers.php
  src/www/ui/template/admin_group_delete.html.twig
  src/www/ui/template/admin_group_users.html.twig
Labels: ready

#1451 Feat/spasht 3.0
  src/lib/php/Dao/SpashtDao.php
  src/lib/php/services.xml.in
  src/spasht/Makefile
  src/spasht/agent/Makefile
  src/spasht/agent/SpashtAgent.php
  src/spasht/agent/spasht.php
  src/spasht/ui/Makefile
  src/spasht/ui/agent-spasht.php
  src/spasht/ui/template/agent_spasht.html.twig
  src/spasht/ui/template/agent_spasht.js.twig
  src/spasht/ui/template/agent_spasht_advanceSearch_form.html.twig
  src/spasht/ui/template/agent_spasht_search.html.twig
  src/spasht/ui/template/show_definitions.html.twig
  src/spasht/ui/template/show_details_table.html.twig
  src/spasht/ui/template/show_uploads_table.html.twig
  src/spasht/ui/ui-spasht.php
  src/www/ui/core-schema.dat
Labels: GSOC-19, has merge conflicts

#1452 Feat/spasht 4.0
  src/lib/php/Dao/SpashtDao.php
  src/spasht/Makefile
  src/spasht/agent/Makefile
  src/spasht/agent/SpashtAgent.php
  src/spasht/agent/spasht
  src/spasht/agent/spasht.php
  src/spasht/agent/version.php.in
  src/spasht/ui/Makefile
  src/spasht/ui/agent-spasht.php
  src/spasht/ui/template/agent_spasht.js.twig
  src/spasht/ui/template/show_definitions.html.twig
  src/spasht/ui/template/show_details_table.html.twig
  src/spasht/ui/ui-spasht.php
  src/www/ui/async/AjaxExplorer.php
  src/www/ui/async/AjaxFileBrowser.php
  src/www/ui/template/browse_file.js.twig
  src/www/ui/template/file-browse.js.twig
  src/www/ui/template/ui-browse-license_file-list.js.twig
  src/www/ui/ui-browse-license.php
  src/www/ui/ui-file-browse.php
  src/www/ui/ui-license-list-files.php
Labels: GSOC-19

#1432 fix(ununpack): Increase buffer sizes to prevent overflow
  src/ununpack/agent/traverse.c
  src/ununpack/agent/ununpack-disk.c
  src/ununpack/agent/ununpack-iso.c
  src/ununpack/agent/utils.c
Labels: ready

#1509 fix(notices): updating notice file, debian copyright and spdx lic info
  NOTICES
  NOTICES.spdx
  debian/copyright
Labels: enhancement, ready

#1495 chore(control): Remove ninka from debian/control
  debian/control
  debian/rules
  src/Makefile
Labels: ready

#1498 feat(rest): Provide group ID during POST upload
  src/www/ui/api/Controllers/UploadController.php
  src/www/ui/api/Helper/UploadHelper.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/page/UploadFilePage.php
  src/www/ui/page/UploadPageBase.php
  src/www/ui/page/UploadVcsPage.php
Labels: ready

#1497 feat(decider): add auto conclusion for ojo findings
  src/decider/agent/DeciderAgent.php
  src/decider/ui/DeciderAgentPlugin.php
  src/decider/ui/template/agent_decider.html.twig
Labels: needs code review, needs test

#1350 feat(license): Provide predefined license comments
  src/lib/php/Dao/LicenseStdCommentDao.php
  src/lib/php/Dao/test/LicenseStdCommentDaoTest.php
  src/lib/php/Test/testdata.sql
  src/lib/php/services.xml.in
  src/www/ui/async/AjaxLicenseStdComments.php
  src/www/ui/core-schema.dat
  src/www/ui/page/AdminLicenseStdComments.php
  src/www/ui/scripts/admin-license-std-comments.js
  src/www/ui/scripts/change-license-common.js
  src/www/ui/template/admin_license_std_comments.html.twig
Labels: enhancement, needs code review, needs test

#1510 feat(rest): add auto conclusion for ojo findings if
  src/www/ui/agent-add.php
  src/www/ui/api/Controllers/JobController.php
  src/www/ui/api/Models/Decider.php
  src/www/ui/api/Models/ScanOptions.php
  src/www/ui/api/documentation/openapi.yaml
Labels: ready

#1486 fix(readmeoss): added edited global license text in readmeoss
  src/readmeoss/agent/readmeoss.php
Labels: ready

#1516 fix(decider): remove force dependency of nomos and monk for ojo decider
  src/decider/ui/DeciderAgentPlugin.php
  src/www/ui/api/Controllers/JobController.php
  src/www/ui/api/Models/ScanOptions.php
Labels: ready
