Repository fossology/fossology, pull requests merged in 2019-01, with the labels that each got.

#1224 feat(select2): Use select2 lib for drop-downs
  src/delagent/ui/admin-folder-delete.php
  src/delagent/ui/template/admin_upload_delete.html.twig
  src/lib/php/Plugin/DefaultPlugin.php
  src/lib/php/UI/MenuRenderer.php
  src/lib/php/common-buckets.php
  src/lib/php/services.xml.in
  src/reuser/ui/template/reuse-folder.html.twig
  src/www/ui/admin-tag-manage.php
  src/www/ui/async/AjaxBrowse.php
  src/www/ui/template/admin-folder-create-form.html.twig
  src/www/ui/template/admin-folder-edit-form.html.twig
  src/www/ui/template/admin_license-upload_form.html.twig
  src/www/ui/template/admin_license_candidate-merge.html.twig
  src/www/ui/template/agent_adder.html.twig
  src/www/ui/template/browse.html.twig
  src/www/ui/template/change_license_modal.html.twig
  src/www/ui/template/components/select-folder.html.twig
  src/www/ui/template/file-browse.html.twig
  src/www/ui/template/include/foot.html.twig
  src/www/ui/template/include/macros.html.twig
  src/www/ui/template/ui-clearing-view_bulk.html.twig
  src/www/ui/template/upload_permissions.html.twig
  src/www/ui/template/upload_srv.html.twig
  src/www/ui/template/user_edit.html.twig
  src/www/ui/user-add.php
  src/www/ui/user-del.php
Labels: enhancement, needs code review, needs test

#1265 fix(libschema): Remove schema to match PHP strings
  src/lib/php/libschema.php
Labels: needs code review

#1218 feat(copyright): select and replace copyright in bulk mode
  src/copyright/ui/HistogramBase.php
  src/copyright/ui/template/histTable.js.twig
Labels: needs test

#1249 fix(nomos): Use space as separator
  src/nomos/agent/CHECKSTR
  src/nomos/agent/GENSEARCHDATA
  src/nomos/agent/PRECHECK
  src/nomos/agent/STRINGS.in
Labels: needs code review, needs test

#1277 fix(scheduler): add check for empty results from query
  src/scheduler/agent/database.c
Labels: ready
