Repository fossology/fossology, pull requests merged in 2019-02, with the labels that each got.

#1261 fix(constraints): Also clean old constraints
  docker-compose.yml
  docker-entrypoint.sh
  install/db/dbmigrate_3.3-3.4.php
  install/fo-postinstall.in
  install/fossinit.php
Labels: needs code review

#1258 fix(delagent): delete existing clearing events using delagent
  src/delagent/agent/delagent.c
  src/delagent/agent/delagent.h
  src/delagent/agent/util.c
  src/delagent/agent_tests/Unit/testDeleteFolders.c
  src/delagent/agent_tests/Unit/testListFolders.c
  src/delagent/ui/admin-folder-delete.php
Labels: ready

#1248 fix(nomos): Detect EPL in XMLs
  src/nomos/agent/STRINGS.in
  src/nomos/agent/parse.c
  src/nomos/agent_tests/testdata/LastGoodNomosTestfilesScan
  src/nomos/agent_tests/testdata/NomosTestfiles/EPL/epl1-pom.xml
Labels: needs code review, needs test

#1268 refactor(view-page): Use Twig templates for info page
  src/www/ui/template/ui-view-info.html.twig
  src/www/ui/ui-view-info.php
Labels: needs code review, needs test

#1269 feat(reused-info): Show reused package in info page
  src/www/ui/template/ui-view-info.html.twig
  src/www/ui/ui-view-info.php
Labels: ready

#1238 docs(libcpp): Added doxygen comments for CPP library
  src/dox.c
  src/lib/c/libfossology.h
  src/lib/cpp/files.cc
  src/lib/cpp/files.hpp
  src/lib/cpp/libfossAgentDatabaseHandler.cc
  src/lib/cpp/libfossAgentDatabaseHandler.hpp
  src/lib/cpp/libfossUtils.cc
  src/lib/cpp/libfossUtils.hpp
  src/lib/cpp/libfossdbQueryResult.cc
  src/lib/cpp/libfossdbQueryResult.hpp
  src/lib/cpp/libfossdbmanagerclass.cc
  src/lib/cpp/libfossdbmanagerclass.hpp
  src/lib/cpp/libfossologyCPP.hpp
  src/lib/cpp/tests/run_tests.cc
  src/lib/cpp/tests/testUtils.hpp
  src/lib/cpp/tests/test_fossdbmanagerclass.cc
  src/lib/cpp/uniquePtr.hpp
Labels: needs code review

#1259 fix(web.postinst): Reflect changes from php-conf-fix
  debian/fossology-web.postinst
Labels: needs test

#1260 fix(fo-installdeps): Add php-mbstring to build deps
  debian/control
  utils/fo-installdeps
Labels: needs code review, needs test

#1272 feat(license-admin): Show obligations for license
  src/lib/php/BusinessRules/LicenseMap.php
  src/lib/php/BusinessRules/ObligationMap.php
  src/lib/php/BusinessRules/test/LicenseMapTest.php
  src/www/ui/admin-license-file.php
  src/www/ui/template/admin_license-upload_form.html.twig
  src/www/ui/template/admin_license_file.html.twig
  src/www/ui/template/admin_license_file.js.twig
Labels: needs code review, needs test

#1214 feat(restapi): New endpoints
  src/composer.json
  src/composer.lock
  src/delagent/ui/admin-folder-delete.php
  src/lib/php/common-container.php
  src/lib/php/services.xml.in
  src/readmeoss/ui/ReadMeOssPlugin.php
  src/spdx2/ui/SpdxTwoGeneratorUi.php
  src/unifiedreport/ui/agent-foreport.php
  src/www/ui/api/Controllers/AuthController.php
  src/www/ui/api/Controllers/BadRequestController.php
  src/www/ui/api/Controllers/FolderController.php
  src/www/ui/api/Controllers/JobController.php
  src/www/ui/api/Controllers/ReportController.php
  src/www/ui/api/Controllers/RestController.php
  src/www/ui/api/Controllers/SearchController.php
  src/www/ui/api/Controllers/UploadController.php
  src/www/ui/api/Controllers/UserController.php
  src/www/ui/api/Helper/AuthHelper.php
  src/www/ui/api/Helper/DbHelper.php
  src/www/ui/api/Helper/RestHelper.php
  src/www/ui/api/Helper/StringHelper.php
  src/www/ui/api/Helper/UploadHelper.php
  src/www/ui/api/Middlewares/RestAuthHelper.php
  src/www/ui/api/Models/Analysis.php
  src/www/ui/api/Models/Decider.php
  src/www/ui/api/Models/Folder.php
  src/www/ui/api/Models/Info.php
  src/www/ui/api/Models/Job.php
  src/www/ui/api/Models/Reuser.php
  src/www/ui/api/Models/ScanOptions.php
  src/www/ui/api/Models/SearchResult.php
  src/www/ui/api/Models/Upload.php
  src/www/ui/api/Models/User.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui/page/AdminContentMove.php
  src/www/ui/page/UploadFilePage.php
  src/www/ui/page/upload-helper.php
  src/www/ui/ui-download.php
Labels: needs code review

#1211 feat(licenseref): add new exception text to fossology database
  install/db/licenseref.sql
Labels: needs test
