Repository fossology/fossology, pull requests merged in 2020-03, with the labels that each got.

#1528 fix(copyright): Remove non utf8 strings
  .travis.yml
  debian/control
  install/defconf/Db.conf.in
  src/copyright/agent/Makefile
  src/copyright/agent/cleanEntries.cc
  src/copyright/agent/cleanEntries.hpp
  src/copyright/agent/database.cc
  src/copyright/agent_tests/Unit/Makefile
  src/copyright/agent_tests/Unit/test_scanners.cc
  src/copyright/agent_tests/testdata/testdata142
  src/copyright/agent_tests/testdata/testdata142_exp
  utils/fo-installdeps
Labels: needs code review, needs test

#1557 feat(migrate): Program to make file UTF-8 compatible
  .gitignore
  utils/FossologyUnicodeClean.cc
  utils/FossologyUnicodeClean.hpp
  utils/Makefile
Labels: needs code review, needs test

#1645 chore(release): add changelog for 3.8.0-rc1
  CHANGELOG.md
  debian/changelog
Labels: needs code review

#1650 fix(package): fix syntax
  debian/control
Labels: ready

#1597 fix(apache): Enable fossology on source install
  .gitignore
  Makefile.conf
  install/Makefile
Labels: ready

#1644 feat(unifiedReport): move obligations to DAO layer remove unused file
  src/lib/php/Report/ObligationsGetter.php
  src/lib/php/Report/obligations.php
  src/unifiedreport/agent/Makefile
  src/unifiedreport/agent/unifiedreport.php
Labels: ready

#1641 fix(fo-installdeps): Missing Fedora dependecies
  utils/fo-installdeps
Labels: ready

#1613 fix(AdviceLicense): Show error message on failure
  src/www/ui/page/AdminLicenseCandidate.php
Labels: ready

#1649 feat(SWH): add time to reset if X-RateLimit-Limit reached for SWH agent
  src/softwareHeritage/agent/softwareHeritageAgent.php
Labels: ready

#1652 Feat(Copyright): Fixed the checking of config file in wrong folder
  src/copyright/agent/regexConfProvider.cc
Labels: ready

#1658 fix(git) : add php.ini to gitignore
  .gitignore
Labels: ready

#1659 docs(contributing.md): Fixed broken link in contributing.md"
  CONTRIBUTING.md
Labels: ready

#1656 fix(travis): Fix build config warnings
  .travis.yml
Labels: needs code review, needs test

#1664 fix(packaging): Create apache softlink on source
  Makefile.process
  install/Makefile
  install/fo-postinstall.in
Labels: ready
