Repository fossology/fossology, pull requests merged in 2020-05, with the labels that each got.

#1700 chore(release): Changelog for release 3.8.0
  CHANGELOG.md
  README.md
  debian/changelog
Labels: needs code review

#1545 chore(ununpack): Remove external files
  .travis.yml
  NOTICES
  NOTICES.spdx
  debian/control
  debian/copyright
  src/delagent/agent/Makefile
  src/delagent/agent/delagent.h
  src/delagent/agent/util.c
  src/delagent/agent_tests/Unit/Makefile
  src/delagent/mod_deps
  src/ununpack/agent/LICENSE.md5
  src/ununpack/agent/Makefile
  src/ununpack/agent/checksum.c
  src/ununpack/agent/checksum.h
  src/ununpack/agent/md5.c
  src/ununpack/agent/md5.h
  src/ununpack/agent/sha1.c
  src/ununpack/agent/sha1.h
  src/ununpack/agent/sha2.c
  src/ununpack/agent/sha2.h
  src/ununpack/agent/ununpack.h
  src/ununpack/agent/utils.c
  src/ununpack/agent_tests/Unit/Makefile
  src/ununpack/mod_deps
  src/wget_agent/agent/Makefile
  src/wget_agent/agent/wget_agent.c
  src/wget_agent/agent_tests/Unit/Makefile
Labels: ready

#1635 fix(rest): Get upload summary without UI
  src/www/ui/api/Controllers/UploadController.php
  src/www/ui/api/Helper/UploadHelper.php
Labels: ready

#1662 fix(AdviceLicense):show error message on failed merge
  src/www/ui/page/AdminLicenseCandidate.php
Labels: needs squash, ready

#1688 feat(upload): Add possibility to upload specific Git branch
  src/wget_agent/agent/wget_agent.c
  src/www/ui/api/Helper/UploadHelper.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/page/UploadVcsPage.php
  src/www/ui/template/upload_vcs.html.twig
Labels: enhancement, ready

#1695 feat(spdx export): Add sha256 to exported spdx.
  src/lib/php/Dao/TreeDao.php
  src/lib/php/Dao/UploadDao.php
  src/lib/php/Dao/test/TreeDaoTest.php
  src/lib/php/Dao/test/UploadDaoTest.php
  src/spdx2/agent/spdx2.php
  src/spdx2/agent/template/spdx2-file.xml.twig
  src/spdx2/agent/template/spdx2-package.xml.twig
  src/spdx2/agent/template/spdx2tv-file.twig
  src/spdx2/agent/template/spdx2tv-package.twig
Labels: ready

#1600 feat(scanners) : ignore files from scanning using mimetype
  src/copyright/agent/copyright.cc
  src/copyright/agent/copyrightState.cc
  src/copyright/agent/copyrightState.hpp
  src/copyright/agent/copyrightUtils.cc
  src/copyright/agent/copyrightUtils.hpp
  src/copyright/agent/database.cc
  src/copyright/agent/database.hpp
  src/copyright/ui/agent-copyright.php
  src/copyright/ui/agent-ecc.php
  src/copyright/ui/agent-keyword.php
  src/lib/c/libfossagent.c
  src/lib/c/libfossagent.h
  src/lib/c/libfossdb.c
  src/lib/c/libfossdbmanager.h
  src/lib/cpp/libfossAgentDatabaseHandler.cc
  src/lib/cpp/libfossAgentDatabaseHandler.hpp
  src/lib/php/UI/template/include/upload.html.twig
  src/lib/php/common-sysconfig.php
  src/monk/agent/match.c
  src/monk/agent/monk.c
  src/monk/agent/monk.h
  src/monk/agent/scheduler.c
  src/monk/ui/agent-monk.php
  src/nomos/agent/nomos.c
  src/nomos/agent/nomos.h
  src/nomos/ui/agent-nomos.php
  src/ojo/agent/OjoState.cc
  src/ojo/agent/OjoState.hpp
  src/ojo/agent/OjoUtils.cc
  src/ojo/agent/OjoUtils.hpp
  src/ojo/agent/OjosDatabaseHandler.cc
  src/ojo/agent/OjosDatabaseHandler.hpp
  src/ojo/agent/ojos.cc
  src/ojo/ui/agent-ojos.php
  src/www/ui/agent-add.php
  src/www/ui/template/agent_adder.html.twig
Labels: enhancement, ready

#1553 fix(libschema): Schema fix for PostgreSQL 12
  src/lib/php/libschema.php
  src/www/ui/core-schema.dat
Labels: ready

#1717 fix(unifiedreport): Get department from config
  src/unifiedreport/agent/reportSummary.php
  src/www/ui/core-schema.dat
  src/www/ui/template/ui-report-conf.html.twig
  src/www/ui/ui-report-conf.php
Labels: needs code review, needs test

#1699 feat(rest): extend upload model with filesha1
  src/www/ui/api/Helper/DbHelper.php
  src/www/ui/api/Models/Upload.php
  src/www/ui/api/documentation/openapi.yaml
Labels: ready

#1714 fix(upload): Fix the check for expire_action
  src/maintagent/agent/process.c
  src/www/ui/ui-browse.php
Labels: ready

#1723 fix(SCM): fix warnings in apache log if SCM is not selected
  src/copyright/ui/agent-copyright.php
  src/copyright/ui/agent-ecc.php
  src/copyright/ui/agent-keyword.php
  src/monk/ui/agent-monk.php
  src/nomos/ui/agent-nomos.php
  src/ojo/ui/agent-ojos.php
Labels: ready

#1725 chore(release): Changelog for release 3.8.1
  CHANGELOG.md
  debian/changelog
Labels: ready

#1726 fix(nomos-standalone): included changes for the PR #1600
  src/nomos/agent/standalone.c
  src/nomos/agent/standalone.h
Labels: ready

#1719 feat(rest): Upload from URL and server
  src/www/ui/api/Controllers/UploadController.php
  src/www/ui/api/Helper/UploadHelper.php
  src/www/ui/api/Helper/UploadHelper/HelperToUploadSrvPage.php
  src/www/ui/api/Helper/UploadHelper/HelperToUploadUrlPage.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/page/UploadSrvPage.php
  src/www/ui/page/UploadUrlPage.php
Labels: enhancement, needs code review, needs test

#1685 feat(nomos): Optimize JSON output
  src/nomos/agent/json_writer.c
  src/nomos/agent/json_writer.h
  src/nomos/agent/licenses.c
  src/nomos/agent/nomos.c
  src/nomos/agent/nomos.h
  src/nomos/agent/nomos_utils.h
Labels: needs code review, needs test

#1677 feat(maintenance): Remove orphan log files
  src/maintagent/agent/maintagent.c
  src/maintagent/agent/maintagent.h
  src/maintagent/agent/process.c
  src/maintagent/agent/usage.c
  src/maintagent/agent/utils.c
  src/maintagent/ui/maintagent.php
  src/www/ui/async/AjaxShowJobs.php
Labels: ready
