Repository fossology/fossology, pull requests merged in 2020-01, with the labels that each got.

#1558 Feat/spasht/dev
  src/composer.lock
  src/lib/php/Dao/SpashtDao.php
  src/spasht/agent/Makefile
  src/spasht/agent/SpashtAgent.php
  src/spasht/ui/Makefile
  src/spasht/ui/ajax-spasht-copyright-hist.php
  src/spasht/ui/template/agent_spasht.html.twig
  src/spasht/ui/template/agent_spasht.js.twig
  src/spasht/ui/template/agent_spasht_ui_content.html.twig
  src/spasht/ui/template/show_details_table.html.twig
  src/spasht/ui/template/show_uploads_table.html.twig
  src/spasht/ui/ui-spasht.php
  src/www/ui/css/spasht.css
Labels: GSOC-19, ready

#1541 fix(ojo): Handle dual-license and SPDX new naming
  src/ojo/agent/OjoAgent.cc
  src/ojo/agent/OjoAgent.hpp
  src/ojo/agent/OjosDatabaseHandler.cc
  src/ojo/agent/ojomatch.hpp
  src/ojo/agent/ojoregex.hpp
  src/ojo/agent_tests/Functional/cli_test.sh
  src/ojo/agent_tests/Functional/regexTest.json
  src/ojo/agent_tests/Unit/test_scanners.cc
Labels: needs code review, needs test

#1559 fix(view-license): Browse file without scanner ars
  src/lib/php/Dao/ClearingDao.php
Labels: needs code review, needs test

#1565 chore(lib): Move agent list to common place
  src/lib/php/Dao/ClearingDao.php
  src/lib/php/Data/AgentRef.php
  src/lib/php/Proxy/UploadTreeProxy.php
  src/lib/php/Report/LicenseClearedGetter.php
  src/lib/php/UI/template/include/base.html.twig
  src/spdx2/agent/spdx2.php
  src/www/ui/async/AjaxExplorer.php
  src/www/ui/async/AjaxFileBrowser.php
  src/www/ui/template/browse_file.js.twig
  src/www/ui/template/file-browse.js.twig
  src/www/ui/template/ui-browse-license_file-list.js.twig
  src/www/ui/ui-browse-license.php
  src/www/ui/ui-clearing-view.php
  src/www/ui/ui-file-browse.php
  src/www/ui/ui-license-list-files.php
Labels: ready

#1571 fix(nomos) : segfault for large offset value
  src/nomos/agent/parse.c
Labels: needs code review, needs test

#1572 fix(nomos) : CC-BY-SA identification
  src/nomos/agent/STRINGS.in
Labels: needs code review, needs test

#1534 fix(license-csv): Update license if exists
  src/lib/php/Application/LicenseCsvExport.php
  src/lib/php/Application/LicenseCsvImport.php
  src/lib/php/Application/test/LicenseCsvExportTest.php
  src/lib/php/Application/test/LicenseCsvImportTest.php
  src/lib/php/Db/DbManager.php
  src/lib/php/services.xml.in
  src/www/ui/page/AdminLicenseFromCSV.php
Labels: needs code review, needs test

#1582 chore(nomos): Rename test file
  src/nomos/agent_tests/testdata/LastGoodNomosTestfilesScan
  src/nomos/agent_tests/testdata/NomosTestfiles/MPL/YUI-Compressor.txt
Labels: needs code review

#1585 fix(ojo): Add lower limit to license length
  src/nomos/agent_tests/testdata/LastGoodNomosTestfilesScan
  src/nomos/agent_tests/testdata/NomosTestfiles/SPDX/GPL-2.0-with-code.js
  src/ojo/agent/ojoregex.hpp
  src/ojo/agent_tests/Functional/regexTest.json
Labels: needs test

#1566 fix(bulk): Fix dropdown bulk on folder level
  src/lib/php/UI/template/include/foot.html.twig
  src/www/ui/scripts/change-license-browse.js
  src/www/ui/scripts/change-license-view.js
  src/www/ui/template/browse_file.js.twig
  src/www/ui/template/file-browse.js.twig
Labels: needs code review, needs test

#1589 feat(ui): Place DataTables processing at top
  src/www/ui/css/jquery.dataTables.css
Labels: ready
