Repository fossology/fossology, pull requests merged in 2020-12, with the labels that each got.

#1747 feat(conf): add textarea in conf page for notes
  src/unifiedreport/agent/reportStatic.php
  src/www/ui/core-schema.dat
  src/www/ui/template/ui-report-conf.html.twig
  src/www/ui/ui-report-conf.php
Labels: ready

#1783 Import notice file content into acknowledgement
  src/www/ui/ajax-notice-files.php
  src/www/ui/scripts/change-license-browse.js
  src/www/ui/scripts/change-license-common.js
  src/www/ui/template/ui-clearing-view.html.twig
  src/www/ui/template/ui-clearing-view_bulk.html.twig
Labels: ready

#1802 fix(conf): fix not able to save conf in case of brackets
  src/www/ui/ui-report-conf.php
Labels: ready

#1804 feat(search) - possibility to search in selected upload only
  src/lib/php/Dao/UploadDao.php
  src/www/ui/api/Controllers/SearchController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/search-helper.php
  src/www/ui/search.php
  src/www/ui/template/ui-search.html.twig
Labels: enhancement, ready

#1811 feat(gui): Add Bucket link for license view page
  src/buckets/ui/ui-buckets.php
Labels: enhancement, ready

#1812 fix(rest) : Set job status as Failed when any one of the job is failed
  src/www/ui/api/Controllers/JobController.php
Labels: ready

#1832 fix(readmeoss): unescape contents
  src/readmeoss/agent/readmeoss.php
Labels: ready

#1821 fix(ununpack): Initialize gcrypt
  src/ununpack/agent/ununpack.c
  src/wget_agent/agent/main.c
Labels: ready

#1794 feat(utils): Filter inputs for unicode ctrl chars
  src/lib/php/Dao/ClearingDao.php
  src/lib/php/Dao/CopyrightDao.php
  src/lib/php/Dao/LicenseDao.php
  src/lib/php/Dao/LicenseStdCommentDao.php
  src/lib/php/Dao/SpashtDao.php
  src/lib/php/Util/StringOperation.php
  src/lib/php/Util/test/StringOperationTest.php
  src/www/ui/admin-license-file.php
  src/www/ui/admin-obligation-file.php
Labels: ready

#1748 feat(rest): Get file info from hash
  src/lib/php/Dao/PfileDao.php
  src/lib/php/Dao/test/PfileDaoTest.php
  src/lib/php/Test/testdata.sql
  src/lib/php/services.xml.in
  src/www/ui/api/Controllers/FileSearchController.php
  src/www/ui/api/Helper/DbHelper.php
  src/www/ui/api/Helper/FileHelper.php
  src/www/ui/api/Helper/UploadHelper.php
  src/www/ui/api/Models/File.php
  src/www/ui/api/Models/Findings.php
  src/www/ui/api/Models/Hash.php
  src/www/ui/api/Models/Upload.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui/core-schema.dat
Labels: ready

#1796 feat(nomos): Apache detection
  src/nomos/agent/parse.c
  src/nomos/agent_tests/testdata/LastGoodNomosTestfilesScan
  src/nomos/agent_tests/testdata/NomosTestfiles/Apache/Apache-2.0-nourl.txt
Labels: ready

#1844 fix(globalDecision): make includesubfolders true in case of global to…
  src/lib/php/BusinessRules/ClearingDecisionProcessor.php
  src/lib/php/BusinessRules/test/ClearingDecisionProcessorTest.php
Labels: needs code review, needs test

#1764 feat(rest): Filter uploads by folder id
  src/lib/php/Dao/FolderDao.php
  src/lib/php/Proxy/UploadBrowseProxy.php
  src/lib/php/services.xml.in
  src/www/ui/api/Controllers/FolderController.php
  src/www/ui/api/Controllers/SearchController.php
  src/www/ui/api/Controllers/UploadController.php
  src/www/ui/api/Helper/DbHelper.php
  src/www/ui/api/Helper/RestHelper.php
  src/www/ui/api/documentation/openapi.yaml
Labels: ready

#1847 fix(twig): Update twig version to preserve spaces
  src/composer.json
  src/composer.lock
  src/www/ui/template/admin_license_file.js.twig
  src/www/ui/template/ui-browse.html.twig
  src/www/ui/ui-browse.php
Labels: ready

#1842 Nomos/lic intel binary
  src/nomos/agent/STRINGS.in
  src/nomos/agent/parse.c
  src/nomos/agent_tests/testdata/LastGoodNomosTestfilesScan
  src/nomos/agent_tests/testdata/NomosTestfiles/Intel/INTEL-binary.txt
Labels: ready

#1848 feat(cd): Build Focal packages on release
  .github/workflows/release-publish.yml
Labels: needs code review, needs test

#1830 update(org): upgraded php version to php7
  .travis.yml
  src/composer.json
  src/composer.lock
  src/spdx2/agent/template/spdx2-document.xml.twig
  src/spdx2/agent/template/spdx2-file.xml.twig
  src/spdx2/agent/template/spdx2-package.xml.twig
  src/spdx2/agent/template/spdx2tv-document.twig
  src/spdx2/agent_tests/Functional/schedulerTest.php
  src/www/ui/page/UploadVcsPage.php
  src/www/ui/upload-instructions.php
Labels: ready

#1828 debian: Improve deb package building
  debian/fossology-scheduler/usr/share/lintian/overrides/fossology-scheduler
  debian/rules
Labels: needs test

#1759 feat(conf): make unified report configurable
  src/lib/php/Dao/UploadDao.php
  src/unifiedreport/agent/reportStatic.php
  src/unifiedreport/agent/unifiedreport.php
  src/www/ui/core-schema.dat
  src/www/ui/template/ui-report-conf.html.twig
  src/www/ui/ui-report-conf.php
Labels: enhancement, ready

#1822 feat(copyright): Search and replace with regex
  src/copyright/ui/HistogramBase.php
  src/copyright/ui/copyright-hist.php
  src/copyright/ui/ecc-hist.php
  src/copyright/ui/email-hist.php
  src/copyright/ui/keyword-hist.php
  src/copyright/ui/template/copyrighthist_scripts.html.twig
  src/copyright/ui/template/histTable.js.twig
Labels: ready

#1810 feat(password): Create password policy
  src/lib/php/Dao/UploadPermissionDao.php
  src/lib/php/common-auth.php
  src/lib/php/common-sysconfig.php
  src/lib/php/tests/test_common_auth.php
  src/www/ui/admin-config.php
  src/www/ui/css/fossology.css
  src/www/ui/template/password-policy-check.js.twig
  src/www/ui/template/user_edit.html.twig
  src/www/ui/user-add.php
  src/www/ui/user-del-helper.php
  src/www/ui/user-edit.php
Labels: ready

#1852 fix(API): added container-interop/container-interop dependency for resolving Internal Server Error (500)
  src/composer.json
  src/composer.lock
Labels: needs code review, needs test

#1857 fix(ack): add missing uploadid in getresults function
  src/www/ui/ajax-notice-files.php
Labels: ready

#1768 feat(build): Get build version number from git
  .github/workflows/release-publish.yml
  Makefile.conf
  utils/fo-debuild
  utils/fo-installdeps
  utils/fo-mktar
  utils/utils.sh
Labels: needs code review, needs test

#1849 feat(browser): total files in license browser view
  src/www/ui/async/AjaxExplorer.php
  src/www/ui/template/browse_file.js.twig
Labels: ready

#1855 (feat) docker services healthchecks in the docker-compose file
  docker-compose.yml
Labels: enhancement, ready
