Repository fossology/fossology, pull requests merged in 2020-08, with the labels that each got.

#1773 fix(Nomos): Added a new License signature
  src/nomos/agent/STRINGS.in
  src/nomos/agent/parse.c
  src/nomos/agent_tests/testdata/LastGoodNomosTestfilesScan
  src/nomos/agent_tests/testdata/NomosTestfiles/PHP/PHP-2.02.txt
Labels: ready

#1766 fix(report): Don't group results with custom text
  src/lib/php/Report/ClearedGetterCommon.php
  src/readmeoss/agent/readmeoss.php
  src/unifiedreport/agent/unifiedreport.php
Labels: ready

#1754 fix(lib): Remove extra parameters
  src/lib/c/libfossagent.c
Labels: needs code review, needs test

#1476 feat(newagent): Spasht (final PR to master)
  .gitignore
  debian/control
  debian/rules
  src/Makefile
  src/composer.lock
  src/fossy-ruleset.xml
  src/lib/php/Dao/SpashtDao.php
  src/lib/php/Data/AgentRef.php
  src/lib/php/Data/Spasht/Coordinate.php
  src/lib/php/Data/Spasht/DefinitionSummary.php
  src/lib/php/Db/DbManager.php
  src/lib/php/UI/template/include/base.html.twig
  src/lib/php/common-sysconfig.php
  src/lib/php/services.xml.in
  src/phpunit.xml
  src/spasht/Makefile
  src/spasht/agent/Makefile
  src/spasht/agent/SpashtAgent.php
  src/spasht/agent/spasht.php
  src/spasht/agent/version.php.in
  src/spasht/spasht.conf
  src/spasht/ui/Makefile
  src/spasht/ui/agent-spasht.php
  src/spasht/ui/ajax-spasht-copyright-hist.php
  src/spasht/ui/services.php
  src/spasht/ui/template/agent_spasht.html.twig
  src/spasht/ui/template/agent_spasht.js.twig
  src/spasht/ui/template/agent_spasht_search.html.twig
  src/spasht/ui/template/agent_spasht_ui_content.html.twig
  src/spasht/ui/template/agent_spasht_ui_tabs.html.twig
  src/spasht/ui/template/show_definitions.html.twig
  src/spasht/ui/template/show_details_table.html.twig
  src/spasht/ui/template/show_uploads_table.html.twig
  src/spasht/ui/template/spasht_histTable.js.twig
  src/spasht/ui/ui-spasht.php
  src/www/ui/ajax-clearing-view.php
  src/www/ui/core-schema.dat
  src/www/ui/css/fossology.css
  src/www/ui/css/spasht.css
  src/www/ui/template/file-browse.js.twig
Labels: GSOC-19, needs code review, needs test

#1780 fix(licenseref): handle errors license errors
  install/fossinit.php
Labels: needs test

#1793 fix(licenseRef): Fix type in array_map
  install/fossinit.php
Labels: ready
