Repository fossology/fossology, pull requests merged in 2020-02, with the labels that each got.

#1573 feat(upload): add feature to change permission of a all upload in a f…
  src/www/ui/page/UploadPermissionPage.php
  src/www/ui/template/upload_permissions.html.twig
Labels: ready

#1599 feat(rest): Get upload summary
  src/delagent/ui/delete-helper.php
  src/www/ui/Makefile
  src/www/ui/api/Controllers/UploadController.php
  src/www/ui/api/Helper/UploadHelper.php
  src/www/ui/api/Models/UploadSummary.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui/page/BrowseLicense.php
Labels: needs code review, needs test

#1594 chore(wget_agent): Remove duplicate code
  src/wget_agent/agent/wget_agent.c
Labels: ready

#1568 feat(rest): Add group context (groupName param) for REST Api calls
  src/www/ui/api/Helper/AuthHelper.php
  src/www/ui/api/Middlewares/RestAuthMiddleware.php
  src/www/ui/api/documentation/openapi.yaml
Labels: ready

#1401 Feat/sh agent
  .gitignore
  debian/control
  debian/rules
  src/Makefile
  src/composer.json
  src/composer.lock
  src/dox.c
  src/lib/php/Dao/SoftwareHeritageDao.php
  src/lib/php/Dao/UploadDao.php
  src/lib/php/services.xml.in
  src/softwareHeritage/Makefile
  src/softwareHeritage/agent/Makefile
  src/softwareHeritage/agent/softwareHeritage.conf
  src/softwareHeritage/agent/softwareHeritage.php
  src/softwareHeritage/agent/softwareHeritageAgent.php
  src/softwareHeritage/agent/version.php.in
  src/softwareHeritage/softwareHeritage.conf
  src/softwareHeritage/ui/AjaxSHDetailsBrowser.php
  src/softwareHeritage/ui/Makefile
  src/softwareHeritage/ui/agent-shagent.php
  src/softwareHeritage/ui/services.php
  src/softwareHeritage/ui/softwareHeritage-plugin.php
  src/softwareHeritage/ui/template/softwareHeritage.html.twig
  src/softwareHeritage/ui/template/softwareHeritage.js.twig
  src/www/ui/core-schema.dat
Labels: GSOC-19, enhancement, needs test

#1593 fix(SHagent): add proxy settings, add SH agent to PHPCS
  debian/control
  debian/rules
  src/fossy-ruleset.xml
  src/lib/php/Dao/SoftwareHeritageDao.php
  src/softwareHeritage/agent/softwareHeritage.conf
  src/softwareHeritage/agent/softwareHeritageAgent.php
  src/softwareHeritage/ui/AjaxSHDetailsBrowser.php
  src/softwareHeritage/ui/agent-shagent.php
  src/softwareHeritage/ui/softwareHeritage-plugin.php
  src/softwareHeritage/ui/template/softwareHeritage.html.twig
  src/softwareHeritage/ui/template/softwareHeritage.js.twig
Labels: enhancement, needs code review, needs test

#1605 feat(reuse): add reuse of report configuration settings
  install/db/dbmigrate_3.5-3.6.php
  install/db/dbmigrate_3.6-3.7.php
  src/lib/php/Dao/UploadDao.php
  src/reuser/agent/ReuserAgent.php
  src/reuser/ui/agent-reuser.php
  src/reuser/ui/template/agent_reuser.html.twig
  src/www/ui/ui-view-info.php
Labels: ready

#1610 feat(email-smtp-config): Add SMTP User field into Fossology email con…
  src/lib/php/common-sysconfig.php
  src/scheduler/agent/database.c
Labels: ready

#1616 feat(ojo): Remove upper limit from license name
  src/ojo/agent/Makefile
  src/ojo/agent/ojoregex.hpp
  src/ojo/agent_tests/Functional/schedulerTest.php
  src/ojo/agent_tests/Unit/test_regex.cc
Labels: enhancement, ready

#1608 feat(rest): Get the license list for upload
  src/www/ui/api/Controllers/UploadController.php
  src/www/ui/api/Helper/UploadHelper.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui/ui-license-list.php
Labels: needs code review, needs test

#1615 feat(SWHagent): add status of request to DB
  src/lib/php/Dao/ShowJobsDao.php
  src/lib/php/Dao/SoftwareHeritageDao.php
  src/softwareHeritage/agent/softwareHeritageAgent.php
  src/www/ui/core-schema.dat
Labels: enhancement, needs test

#1604 fix(reuser): Run decider after reuser
  src/decider/ui/DeciderAgentPlugin.php
  src/reuser/ui/agent-reuser.php
  src/www/ui/page/UploadPageBase.php
Labels: ready

#1628 fix(lib): Check group on local decision only
  src/lib/php/Dao/ClearingDao.php
  src/lib/php/Proxy/UploadTreeProxy.php
Labels: ready

#1617 feat(unifiedReport): include DNU information in assesment summary if …
  src/unifiedreport/agent/reportStatic.php
  src/unifiedreport/agent/unifiedreport.php
Labels: ready

#1638 Fix(Dockerfile): make clean install clean
  Dockerfile
Labels: ready

#1619 feat(auth): Add external authentification feature
  install/defconf/fossology.conf.in
  src/lib/php/common-auth.php
  src/www/ui/core-auth.php
Labels: enhancement, ready
