Repository fossology/fossology, pull requests merged in 2020-06, with the labels that each got.

#1702 feat(groups): Update default group for user
  src/lib/php/UI/template/components/menu.html.twig
  src/www/ui/template/user_edit.html.twig
  src/www/ui/user-edit.php
Labels: ready

#1732 fix(clearingCount): do not add count as cleared in case of to be disc…
  src/lib/php/Dao/ClearingDao.php
  src/www/ui/async/AjaxExplorer.php
Labels: ready

#1667 feat(ui): Conversion of timestamps to browser timezone
  src/lib/php/UI/template/components/login-form.html.twig
  src/lib/php/common-folders.php
  src/lib/php/common-ui.php
  src/reportImport/ui/ReportImportPlugin.php
  src/reuser/ui/reuser-plugin.php
  src/www/ui/admin-dashboard-general.php
  src/www/ui/admin-upload-edit.php
  src/www/ui/async/AjaxBrowse.php
  src/www/ui/async/AjaxFolderContents.php
  src/www/ui/async/AjaxShowJobs.php
  src/www/ui/core-auth.php
  src/www/ui/template/upload_permissions.html.twig
Labels: ready

#1691 feat(download): Limit source code download for admin users only
  src/lib/php/common-license-file.php
  src/lib/php/common-sysconfig.php
  src/www/ui/ui-download.php
Labels: ready

#1733 fix(spasht-ui): Removed extension from the spasht search
  src/spasht/ui/template/agent_spasht_search.html.twig
  src/spasht/ui/ui-spasht.php
Labels: ready

#1740 fix(bulk): add class to show text highlighted for matched page
  src/www/ui/template/bulk-history.html.twig
Labels: ready

#1744 perf(license_candidate): Create PRIMARY KEY
  src/www/ui/core-schema.dat
Labels: enhancement, ready

#1713 feat(export): Export Copyrights
  src/lib/php/BusinessRules/ClearingDecisionFilter.php
  src/lib/php/Dao/CopyrightDao.php
  src/www/ui/Makefile
  src/www/ui/api/Helper/UploadHelper.php
  src/www/ui/template/ui-export-list.html.twig
  src/www/ui/template/ui-license-list-form.html.twig
  src/www/ui/ui-export-list.php
  src/www/ui/ui-license-list.php
Labels: enhancement, ready

#1745 fix(ui): Use default timezone if not set
  src/lib/php/common-ui.php
Labels: ready

#1709 feat(jobs): Show all running jobs
  src/lib/php/Dao/ShowJobsDao.php
  src/www/ui/async/AjaxAllJobStatus.php
  src/www/ui/page/AllJobStatus.php
  src/www/ui/template/all_job_status.html.twig
Labels: ready

#1743 fix(spdx): Fix duplicate copyrights
  src/spdx2/agent/spdx2.php
Labels: needs code review, needs test

#1682 feat(conf): change all local clearings to global from conf
  src/deciderjob/agent/DeciderJobAgent.php
  src/lib/php/Auth/Auth.php
  src/lib/php/Dao/ClearingDao.php
  src/lib/php/Plugin/FO_Plugin.php
  src/lib/php/common-users.php
  src/www/ui/ajax-clearing-view.php
  src/www/ui/template/ui-report-conf.html.twig
  src/www/ui/ui-report-conf.php
  src/www/ui/user-add.php
  src/www/ui/user-edit.php
Labels: needs code review, needs test

#1711 fix(spdxReport): add missing artifact to file path in spdx reporting
  src/spdx2/agent/spdx2.php
Labels: ready

#1736 feat(ci): Use FOSSology scanners CI
  utils/automation/.gitlab-ci.sample.yml
  utils/automation/.travis.sample.yml
  utils/automation/Dockerfile.ci
  utils/automation/fossologyscanner.py
  utils/automation/whitelist.sample.json
Labels: enhancement, needs code review, needs test
