Repository fossology/fossology, pull requests merged in 2020-04, with the labels that each got.

#1598 fix(rest): Remove hostname from JWT
  src/www/ui/api/Controllers/AuthController.php
  src/www/ui/api/Helper/AuthHelper.php
  src/www/ui/api/Middlewares/RestAuthMiddleware.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/async/AjaxManageToken.php
  src/www/ui/user-edit.php
Labels: needs test

#1651 feat(DB): Recode copyright tables to UTF-8
  .gitignore
  Dockerfile
  Makefile.conf
  docker-entrypoint.sh
  install/db/Makefile
  install/db/dbmigrate_3.7-3.8.php
  install/db/dbmigrate_change_db_encoding.php.in
  install/fo-postinstall.in
  install/fossinit.php
  src/copyright/agent/FossologyUnicodeClean.cc
  src/copyright/agent/FossologyUnicodeClean.hpp
  src/copyright/agent/Makefile
  src/copyright/agent/cleanEntries.cc
  src/copyright/agent/cleanEntries.hpp
  src/lib/cpp/Makefile
  src/lib/cpp/libfossUtils.cc
  src/lib/cpp/libfossUtils.hpp
  src/ojo/agent/OjosDatabaseHandler.cc
  utils/Makefile
Labels: enhancement, ready

#1694 fix(spdx-rdf-report): Fix comments in export.
  src/spdx2/agent/template/spdx2-file.xml.twig
Labels: ready

#1705 fix(schema): Match schema with schema export
  src/www/ui/core-schema.dat
Labels: ready

#1707 fix(delete): Do not remove upload_pk
  src/delagent/agent/util.c
  src/maintagent/agent/process.c
  src/www/ui/async/AjaxShowJobs.php
  src/www/ui/core-schema.dat
  src/www/ui/template/ui-showjobs.js.twig
  src/www/ui/ui-browse.php
Labels: ready

#1686 fix(travis): Fix page deploy stage
  .travis.yml
Labels: ready
