Repository fossology/fossology, pull requests merged in 2021-07, with the labels that each got.

#2000 feat(rest): Add POST/PATCH license endpoints
  src/lib/php/Dao/LicenseDao.php
  src/phpunit-bootstrap.php
  src/www/ui/api/Controllers/LicenseController.php
  src/www/ui/api/Helper/DbHelper.php
  src/www/ui/api/Models/License.php
  src/www/ui/api/Models/Obligation.php
  src/www/ui/api/Models/ScanOptions.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui_tests/api/Controllers/FolderControllerTest.php
  src/www/ui_tests/api/Controllers/LicenseControllerTest.php
  src/www/ui_tests/api/Controllers/UploadControllerTest.php
  src/www/ui_tests/api/Models/LicenseTest.php
  src/www/ui_tests/api/Models/ObligationTest.php
  src/www/ui_tests/api/Models/ScanOptionsTest.php
Labels: enhancement, needs code review, needs test

#2016 fix(auth): fix call to add_user() when login from external auth
  src/www/ui/core-auth.php
Labels: needs test

#2042 feat(expose-headers): added the expose headers option
  src/www/ui/api/Controllers/AuthController.php
  src/www/ui/api/Middlewares/RestAuthMiddleware.php
Labels: needs code review, needs test

#2040 feat(reso): new agent for REUSE.Software standard
  .gitignore
  src/Makefile
  src/decider/agent/DeciderAgent.php
  src/decider/ui/template/agent_decider.html.twig
  src/fossy-ruleset.xml
  src/lib/php/Data/AgentRef.php
  src/lib/php/UI/template/include/base.html.twig
  src/reso/Makefile
  src/reso/agent/Makefile
  src/reso/agent/ResoAgent.php
  src/reso/agent/reso.php
  src/reso/agent/version.php.in
  src/reso/reso.conf
  src/reso/ui/Makefile
  src/reso/ui/ResoAgentPlugin.php
  src/www/ui/api/Models/Analysis.php
  src/www/ui/api/Models/Decider.php
  src/www/ui/api/Models/ScanOptions.php
  src/www/ui/api/documentation/openapi.yaml
Labels: ready

#2048 feat(rest): Filter licenses by kind
  src/www/ui/api/Controllers/LicenseController.php
  src/www/ui/api/Helper/DbHelper.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui_tests/api/Controllers/LicenseControllerTest.php
Labels: ready

#2044 fix(ojo): Set candidate license creator
  src/ojo/agent/OjoAgent.cc
  src/ojo/agent/OjoAgent.hpp
  src/ojo/agent/OjoUtils.cc
  src/ojo/agent/OjosDatabaseHandler.cc
  src/ojo/agent/OjosDatabaseHandler.hpp
Labels: ready

#2051 feat(changelog) add changelog for 3.11.0-rc2
  CHANGELOG.md
  debian/changelog
Labels: needs code review

#2056 fix(rules) : adding debian package for reso agent
  debian/control
  debian/rules
Labels: ready

#2060 fix(migration): check if uploadtree is empty
  install/db/dbmigrate_copyright-event.php
Labels: needs test

#2055 fix(copyright):Change menu text of copyright page
  src/copyright/ui/copyright-hist.php
Labels: needs code review, needs test

#2067 feat(changelog): add changelog for release 3.11.0
  CHANGELOG.md
  debian/changelog
Labels: ready
