Repository fossology/fossology, pull requests merged in 2021-01, with the labels that each got.

#1856 feat(ununpack): standalone
  .gitignore
  src/ununpack/agent/Makefile.sa
  src/ununpack/agent/checksum.h
  src/ununpack/agent/standalone.c
  src/ununpack/agent/standalone.h
  src/ununpack/agent/ununpack.h
  src/ununpack/agent/utils.c
Labels: enhancement, ready

#1862 docs(db): remove obsolete comment from schema
  src/www/ui/core-schema.dat
Labels: needs code review

#1861 fix(db): add indexes to pfile on sha1 and sha256
  src/www/ui/core-schema.dat
Labels: needs code review, needs test

#1851 refactor(login): updated password hashing algorithm
  src/cli/fo_usergroup.php
  src/cli/tests/test_common.php
  src/lib/php/Dao/UserDao.php
  src/lib/php/common-auth.php
  src/lib/php/common-users.php
  src/testing/db/create_test_database.php
  src/testing/install/test4migrationinstall/test_common.php
  src/testing/install/test4packageinstall/test_common.php
  src/www/ui/core-auth.php
  src/www/ui/user-add.php
  src/www/ui/user-edit.php
Labels: enhancement, ready

#1865 fix(login): Do not set group_fk if empty
  src/www/ui/user-edit.php
Labels: needs code review, needs test

#1866 chore(release): Release changelog for 3.10.0-rc1
  CHANGELOG.md
  README.md
  debian/changelog
Labels: needs code review

#1867 fix(cd): Use published event to build release pkgs
  .github/workflows/release-publish.yml
Labels: ready

#1854 feat(rest): get copyright info for file hash
  src/lib/php/Dao/PfileDao.php
  src/lib/php/Dao/test/PfileDaoTest.php
  src/lib/php/Test/testdata.sql
  src/www/ui/api/Controllers/FileSearchController.php
  src/www/ui/api/Helper/FileHelper.php
  src/www/ui/api/Models/Findings.php
  src/www/ui/api/documentation/openapi.yaml
Labels: enhancement, ready

#1863 feat(rest): add license search based on short name
  src/www/ui/api/Controllers/LicenseController.php
  src/www/ui/api/Models/License.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
Labels: enhancement, ready

#1864 feat(reuse): Change data type of reuse_group from int to string.
  src/www/ui/api/Controllers/JobController.php
  src/www/ui/api/Models/Reuser.php
  src/www/ui/api/Models/ScanOptions.php
  src/www/ui/api/documentation/openapi.yaml
Labels: ready

#1869 fix(globaldecision): do not add decisions if the events have no change
  src/www/ui/ui-clearing-view.php
Labels: needs code review, needs test

#1872 feat(rest): get groups and create group functionality
  src/www/ui/api/Controllers/GroupController.php
  src/www/ui/api/Models/Group.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
Labels: enhancement, ready

#1874 feat(swh): Allow API token
  src/lib/php/Dao/SoftwareHeritageDao.php
  src/lib/php/common-sysconfig.php
  src/softwareHeritage/agent/Makefile
  src/softwareHeritage/agent/softwareHeritage.conf
  src/softwareHeritage/agent/softwareHeritageAgent.php
  src/softwareHeritage/ui/AjaxSHDetailsBrowser.php
Labels: ready

#1883 fix(reuser): updated misleading UI label
  src/reuser/ui/template/agent_reuser.html.twig
Labels: needs code review
