Repository fossology/fossology, pull requests merged in 2021-06, with the labels that each got.

#2001 feat(migration): general improvements for copyright migration
  install/db/dbmigrate_copyright-event.php
Labels: enhancement, needs test

#2013 feat(ui): Remember assignee filter on Browse view
  src/www/ui/scripts/browse.js
Labels: ready

#2009 fix(ui): Break long lines in copyright table
  src/copyright/ui/HistogramBase.php
  src/spasht/ui/template/agent_spasht_ui_tabs.html.twig
  src/www/ui/css/jquery.dataTables.css
Labels: ready

#2011 fix(copyright): Make check strict
  src/copyright/ui/ajax-copyright-hist.php
  src/copyright/ui/list.php
  src/lib/php/Dao/CopyrightDao.php
  src/reuser/agent/ReuserAgent.php
Labels: ready

#2004 fix(nomos): improved nomos MPL-2.0 detection
  src/nomos/agent/STRINGS.in
  src/nomos/agent/parse.c
Labels: needs code review, needs test

#1996 fix(ui): License text editor
  src/www/ui/scripts/change-license-common.js
Labels: needs code review, needs test

#2005 fix(debian): Add php-gd package as dependency
  debian/control
Labels: needs test

#2022 fix(ui): Fix the modal height for small screens
  src/www/ui/template/ui-clearing-view_bulk.html.twig
  src/www/ui/template/ui-clearing-view_rhs.html.twig
Labels: needs code review, needs test

#2010 fix(api): Add missing reuser options
  src/www/ui/api/Models/Reuser.php
  src/www/ui/api/Models/ScanOptions.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui_tests/api/Models/ReuserTest.php
Labels: ready

#2019 feat(rest): Add /users/self endpoint
  .gitignore
  src/www/ui/api/Controllers/UserController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui_tests/api/Controllers/UserControllerTest.php
Labels: needs code review, needs test

#2034 fix(cli): Dependency exception
  src/lib/php/common-job.php
Labels: ready

#2033 feat(changelog): add release changelog for 3.11.0-rc1
  CHANGELOG.md
  debian/changelog
Labels: needs code review, needs test
