Repository fossology/fossology, pull requests merged in 2021-04, with the labels that each got.

#1945 updated the documentation link
  src/lib/php/UI/Component/Menu.php
Labels: GSOC-21, ready

#1961 fix(ui): updated the link of scheduler documentation
  src/www/ui/template/upload_instructions.html.twig
Labels: GSOC-21, ready

#1914 feat(copyright): save deleted copyrights in copyright_event table
  install/db/Makefile
  install/db/dbmigrate_copyright-event.php
  install/fossinit.php
  src/cli/tests/test_fo_copyright_list.php
  src/copyright/agent_tests/Functional/schedulerTest.php
  src/copyright/ui/ajax-copyright-hist.php
  src/copyright/ui/list.php
  src/lib/php/Dao/ClearingDao.php
  src/lib/php/Dao/CopyrightDao.php
  src/lib/php/Dao/UploadDao.php
  src/lib/php/Dao/test/CopyrightDaoTest.php
  src/reuser/agent/ReuserAgent.php
  src/reuser/ui/template/agent_reuser.html.twig
  src/www/ui/core-schema.dat
Labels: needs code review, needs test

#1967 chore(release): Release changelog for 3.10.0-RC2
  CHANGELOG.md
  debian/changelog
Labels: needs code review
