Repository fossology/fossology, pull requests merged in 2021-05, with the labels that each got.

#1974 fix(actions): Build pages on release
  .github/workflows/deploy-pages.yml
Labels: ready

#1978 fix(docker-compose): Revert container port to 8081
  docker-compose.yml
Labels: ready

#1975 perf(migration): remove offset to make the query faster
  install/db/dbmigrate_copyright-event.php
Labels: needs code review, needs test

#1888 fix(build): Make script compatible with Xenial
  utils/fo-debuild
Labels: needs code review, needs test

#1735 test(rest): Unit test cases for REST API
  src/phpunit.xml
  src/www/ui/api/Controllers/FolderController.php
  src/www/ui/api/Controllers/ReportController.php
  src/www/ui/api/Controllers/UploadController.php
  src/www/ui_tests/Makefile
  src/www/ui_tests/api/Controllers/AuthControllerTest.php
  src/www/ui_tests/api/Controllers/FolderControllerTest.php
  src/www/ui_tests/api/Controllers/JobControllerTest.php
  src/www/ui_tests/api/Controllers/ReportControllerTest.php
  src/www/ui_tests/api/Controllers/UploadControllerTest.php
  src/www/ui_tests/api/Controllers/UserControllerTest.php
  src/www/ui_tests/api/Controllers/VersionControllerTest.php
  src/www/ui_tests/api/Helper/AuthHelperTest.php
  src/www/ui_tests/api/Helper/DbHelperTest.php
  src/www/ui_tests/api/Helper/RestHelperTest.php
  src/www/ui_tests/api/Makefile
  src/www/ui_tests/api/Models/AnalysisTest.php
  src/www/ui_tests/api/Models/DeciderTest.php
  src/www/ui_tests/api/Models/FileTest.php
  src/www/ui_tests/api/Models/FolderTest.php
  src/www/ui_tests/api/Models/InfoTest.php
  src/www/ui_tests/api/Models/JobTest.php
  src/www/ui_tests/api/Models/ReuserTest.php
  src/www/ui_tests/api/Models/SearchResultTest.php
  src/www/ui_tests/api/Models/UploadSummaryTest.php
  src/www/ui_tests/api/Models/UploadTest.php
  src/www/ui_tests/api/Models/UserTest.php
  src/www/ui_tests/api/tests.xml
Labels: enhancement, ready

#1807 fix(gcc-10): Fix errors and warnings
  .travis.yml
  src/lib/c/sqlCopy.c
  src/monk/agent/_squareVisitor.h.post
  src/nomos/agent/doctorBuffer_utils.c
  src/nomos/agent/nomos.c
  src/nomos/agent/nomos.h
  src/nomos/agent/nomos_regex.c
  src/nomos/agent/nomos_regex.h
  src/nomos/agent/nomos_utils.c
  src/nomos/agent/nomos_utils.h
  src/scheduler/agent/event.c
  src/wget_agent/agent/wget_agent.c
Labels: ready

#1877 feat(licenseExport): include obligation topic in exported CSV
  src/lib/php/Application/LicenseCsvExport.php
  src/lib/php/Application/LicenseCsvImport.php
  src/lib/php/Application/test/LicenseCsvExportTest.php
  src/www/ui/template/admin_license_from_csv.html.twig
Labels: ready

#1886 feat(addMetadata): added creationdate,lastModifiedDate,usernameCreate…
  src/lib/php/Dao/LicenseDao.php
  src/lib/php/Test/TestPgDb.php
  src/www/ui/core-schema.dat
  src/www/ui/page/AdviceLicense.php
  src/www/ui/template/advice_license-edit.html.twig
Labels: GSOC-21, ready

#1889 fix(email): Update email command for s-nail
  debian/control
  install/defconf/fossology.conf.in
  src/scheduler/agent/database.c
Labels: GSOC-21, enhancement, ready

#1890 feat(Ui): added Default upload visibility
  src/lib/php/Test/testdata.sql
  src/lib/php/UI/template/include/upload.html.twig
  src/lib/php/common-sysconfig.php
  src/lib/php/common-users.php
  src/spdx2/agent_tests/Functional/fo_report.sql
  src/unifiedreport/agent_tests/Functional/fo_report.sql
  src/www/ui/admin-config.php
  src/www/ui/core-schema.dat
  src/www/ui/page/UploadPageBase.php
  src/www/ui/template/user_edit.html.twig
  src/www/ui/user-add.php
  src/www/ui/user-edit.php
Labels: GSOC-21, enhancement, ready

#1898 feat(rest): Add assignee id to fossology API
  src/lib/php/Dao/UploadDao.php
  src/www/ui/api/Helper/DbHelper.php
  src/www/ui/api/Helper/UploadHelper.php
  src/www/ui/api/Models/Upload.php
  src/www/ui/api/Models/UploadSummary.php
  src/www/ui/api/documentation/openapi.yaml
Labels: GSOC-21, enhancement, ready

#1908 fix(username): update session variable on username change
  src/www/ui/template/user_edit.html.twig
  src/www/ui/user-edit.php
Labels: GSOC-21, ready

#1912 fix(UI): fix html errors, css errors and add viewport meta tag
  src/lib/php/Plugin/DefaultPlugin.php
  src/lib/php/Plugin/FO_Plugin.php
  src/lib/php/UI/template/include/base.html.twig
  src/www/ui/css/fossology.css
  src/www/ui/template/admin_obligation-upload_form.html.twig
  src/www/ui/template/popup_license.html.twig
  src/www/ui/template/ui-clearing-view_bulk.html.twig
Labels: GSOC-21, ready

#1916 fix(reuser): removed agent log
  src/reuser/agent/ReuserAgent.php
Labels: GSOC-21, ready

#1918 fix(report): Do not merge ack text
  src/lib/php/Report/LicenseClearedGetter.php
Labels: ready

#1926 fix(ui): Show error message for invalid license id
  src/www/ui/admin-license-file.php
  src/www/ui/template/admin_license-upload_form.html.twig
Labels: ready

#1962 fix(decision): Create clearing events for irrelevant folder decisions
  src/lib/php/Dao/ClearingDao.php
  src/www/ui/scripts/change-license-browse.js
  src/www/ui/scripts/change-license-common.js
Labels: ready

#1947 chore(dependency): update jquery and select2 version
  .gitignore
  NOTICES.spdx
  debian/copyright
  debian/source/lintian-overrides
  src/lib/php/UI/template/include/foot.html.twig
  src/www/ui/css/select2.min.css
  src/www/ui/scripts/jquery-3.3.1.min.js
  src/www/ui/scripts/jquery-3.6.0.min.js
  src/www/ui/scripts/select2.full.min.js
  src/www/ui/template/ui-browse.js.twig
Labels: GSOC-21, enhancement, ready

#1948 feat(export) : Consolidating results per file or directories
  src/www/ui/template/ui-export-list.html.twig
  src/www/ui/ui-export-list.php
Labels: enhancement, ready

#1971 feat(dbcreate): retry psql check while starting
  install/db/dbcreate.in
Labels: enhancement, ready

#1986 fix(test): Add new assignee attribute to REST
  src/Makefile
  src/www/ui_tests/api/Controllers/UploadControllerTest.php
  src/www/ui_tests/api/Models/SearchResultTest.php
  src/www/ui_tests/api/Models/UploadSummaryTest.php
  src/www/ui_tests/api/Models/UploadTest.php
Labels: ready

#1982 feat(monkbulk): Configurable irrelevant file scan
  src/decider/agent/BulkReuser.php
  src/lib/php/Dao/LicenseDao.php
  src/monk/agent/database.c
  src/monk/agent/database.h
  src/monk/agent/monkbulk.c
  src/monk/agent/monkbulk.h
  src/www/ui/change-license-bulk.php
  src/www/ui/core-schema.dat
  src/www/ui/scripts/change-license-common.js
  src/www/ui/template/ui-clearing-view_bulk.html.twig
Labels: enhancement, ready

#1965 feat(maintagent): add job to remove expired tokens from database
  src/lib/php/common-sysconfig.php
  src/maintagent/agent/maintagent.c
  src/maintagent/agent/maintagent.h
  src/maintagent/agent/process.c
  src/maintagent/agent/usage.c
  src/maintagent/ui/maintagent.php
Labels: GSOC-21, ready

#1981 remove wrong 'extern "C"'
  src/lib/c/libfossdbmanager.h
  src/lib/cpp/libfossdbQueryResult.hpp
  src/lib/cpp/libfossdbmanagerclass.hpp
Labels: ready

#1976 feat(browse): add a simple search to get folder
  src/www/ui/template/ui-browse.html.twig
  src/www/ui/template/ui-browse.js.twig
  src/www/ui/ui-browse.php
Labels: ready

#1994 fix(ui): Add scroll to NOTICE file modal
  src/lib/php/Dao/ClearingDao.php
  src/www/ui/ajax-clearing-view.php
  src/www/ui/css/fossology.css
  src/www/ui/scripts/change-license-common.js
Labels: ready

#1993 feat(ci): Mark PRs with conflict with Actions
  .github/workflows/conflict-check.yml
Labels: enhancement, ready

#1998 feat(restAPI): Added options request and verification function
  src/lib/php/common-sysconfig.php
  src/www/ui/api/Controllers/AuthController.php
  src/www/ui/api/Middlewares/RestAuthMiddleware.php
  src/www/ui/api/index.php
Labels: GSOC-21, enhancement, needs test

#1997 feat(copyright): add bulk undo for deactivated copyrights
  src/copyright/ui/HistogramBase.php
  src/copyright/ui/TextFindingsAjax.php
  src/copyright/ui/ajax-copyright-hist.php
  src/copyright/ui/template/histTable.js.twig
  src/spasht/ui/ajax-spasht-copyright-hist.php
  src/spasht/ui/template/agent_spasht_ui_tabs.html.twig
  src/spasht/ui/template/spasht_histTable.js.twig
Labels: enhancement, ready

#1958 feat(export): Download results in spreadsheet (xlsx)
  .travis.yml
  src/composer.json
  src/composer.lock
  src/www/ui/template/ui-export-list.html.twig
  src/www/ui/ui-export-list.php
  utils/fo-installdeps
Labels: ready
