Repository fossology/fossology, pull requests merged in 2021-09, with the labels that each got.

#2094 hotfix(api): Add missing auth controller
  src/www/ui/api/Controllers/AuthController.php
  src/www/ui_tests/api/Controllers/AuthControllerTest.php
  src/www/ui_tests/api/Models/AnalysisTest.php
  src/www/ui_tests/api/Models/UserTest.php
Labels: ready

#2099 docs: Updated README.md and CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: Documentation

#2096 feat(unifiedreport): include assigned to in component clearing section
  src/unifiedreport/agent/reportSummary.php
  src/unifiedreport/agent/unifiedreport.php
Labels: needs test

#2102 fix(upload): Fix upload description input
  src/lib/php/UI/template/include/upload.html.twig
Labels: needs code review, needs test
