Repository fossology/fossology, pull requests merged in 2021-08, with the labels that each got.

#2052 Fix/openapi linting
  .github/workflows/static-checks.yml
  src/www/ui/api/documentation/openapi.yaml
Labels: ready

#2057 fix(report): same license text for different shortname
  src/lib/php/Report/ClearedGetterCommon.php
Labels: needs test

#2068 fix(ui/uploadVcsPage):Fix upload from VCS for parameterize agent
  src/www/ui/page/UploadVcsPage.php
Labels: needs code review, needs test

#2080 fix(rest): fixed the pagination in apis
  src/www/ui/api/Controllers/LicenseController.php
  src/www/ui/api/Controllers/UploadController.php
Labels: ready

#1808 fix(logrotate): Send SIGHUP
  debian/fossology-scheduler.logrotate
  pbconf/fossology/deb/fossology-scheduler.logrotate
Labels: enhancement, ready

#1988 chore(os): Drop xenial support for eol
  .github/workflows/release-publish.yml
  .travis.yml
  Makefile.conf
  Vagrantfile
  src/copyright/mod_deps
  src/lib/php/Dao/LicenseDao.php
  src/lib/php/Util/StringOperation.php
  src/mimetype/agent_tests/Functional/cliParamsTest4Mimetype.php
  src/nomos/mod_deps
  src/ojo/mod_deps
  src/ununpack/agent_tests/Functional/cliParamsTest4UnunpackNormal.php
  utils/fo-debuild
  utils/fo-installdeps
  utils/utils.sh
Labels: ready

#2036 feat(spasht): Show effective score
  src/lib/php/Data/Spasht/Coordinate.php
  src/lib/php/Data/Spasht/DefinitionSummary.php
  src/spasht/ui/template/agent_spasht.js.twig
  src/spasht/ui/template/show_definitions.html.twig
  src/spasht/ui/template/show_details_table.html.twig
  src/spasht/ui/ui-spasht.php
Labels: ready

#2064 feat(rest): New info and health endpoints
  src/lib/php/common-sysconfig.php
  src/www/ui/api/Controllers/AuthController.php
  src/www/ui/api/Controllers/InfoController.php
  src/www/ui/api/Middlewares/RestAuthMiddleware.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
Labels: ready

#2077 fix(unifiedreport): Fix upload link for API
  src/unifiedreport/agent/unifiedreport.php
  src/unifiedreport/ui/agent-foreport.php
Labels: ready

#2076 ci(actions): Build Docker images in Actions
  .github/workflows/docker-build.yml
  .github/workflows/release-publish.yml
Labels: enhancement, ready

#2082 fix (build): do not fail is /usr/share/man* folders already exist
  Dockerfile
Labels: needs test

#1954 feat(edit-user): Let user can define default folder and use the defau…
  src/lib/php/Dao/FolderDao.php
  src/lib/php/Test/testdata.sql
  src/lib/php/common-users.php
  src/spdx2/agent_tests/Functional/fo_report.sql
  src/unifiedreport/agent_tests/Functional/fo_report.sql
  src/www/ui/core-schema.dat
  src/www/ui/page/UploadPageBase.php
  src/www/ui/template/user_edit.html.twig
  src/www/ui/ui-browse.php
  src/www/ui/user-edit.php
Labels: ready

#2038 feat(rest): Filter uploads with 4 new parameters
  src/www/ui/api/Controllers/UploadController.php
  src/www/ui/api/Helper/DbHelper.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui_tests/api/Controllers/UploadControllerTest.php
Labels: enhancement, ready
