Repository fossology/fossology, pull requests merged in 2021-12, with the labels that each got.

#2091 feat(maintagent): Implement deleteOrphanGold fn
  src/maintagent/agent/maintagent.h
  src/maintagent/agent/process.c
  src/maintagent/agent/utils.c
  src/maintagent/ui/maintagent.php
Labels: enhancement, ready

#2093 feat(maintagent): Remove old gold files
  src/maintagent/agent/maintagent.c
  src/maintagent/agent/maintagent.h
  src/maintagent/agent/process.c
  src/maintagent/agent/utils.c
  src/maintagent/ui/maintagent.php
Labels: enhancement, ready

#2098 feat(maintagent): Remove old log files
  src/maintagent/agent/maintagent.c
  src/maintagent/agent/maintagent.h
  src/maintagent/agent/process.c
  src/maintagent/agent/usage.c
  src/maintagent/ui/maintagent.php
Labels: enhancement, ready

#2117 fix(ui): add line break in upload name if exceeds 20 chars
  src/lib/php/UI/FolderNav.php
  src/www/ui/async/AjaxBrowse.php
  src/www/ui/css/jquery.treeview.css
  src/www/ui/scripts/change-license-browse.js
  src/www/ui/scripts/change-license-view.js
  src/www/ui/template/ui-browse.html.twig
  src/www/ui/template/ui-clearing-view.html.twig
  src/www/ui/template/ui-clearing-view_bulk.html.twig
  src/www/ui/template/ui-report-conf.html.twig
  src/www/ui/template/ui-view-info.html.twig
  src/www/ui/ui-report-conf.php
  src/www/ui/ui-view.php
Labels: needs code review, needs test

#2126 feat(changelog): add changelog for release 4.0.0-rc1
  CHANGELOG.md
  debian/changelog
Labels: ready

#2127 chore(cd): Continue release build on failure
  .github/workflows/release-publish.yml
Labels: enhancement, needs code review

#2130 fix(reportImport): Fix interfaces in report import
  src/reportImport/agent/ReportImportSink.php
Labels: ready
