Repository fossology/fossology, pull requests merged in 2022-02, with the labels that each got.

#2144 feat(keyword): add new word 'stolen from' to keyword agent
  src/copyright/agent/keyword.conf
  src/copyright/agent_tests/Unit/test_scanners.cc
Labels: ready

#2148 feat(upload): Warning on duplicate upload
  src/lib/php/UI/template/include/upload.html.twig
  src/www/ui/async/AjaxFolderContents.php
  src/www/ui/template/upload_file.html.twig
Labels: needs code review, needs test

#2151 fix(report): Set content type header
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/ui-download.php
Labels: ready

#2139 feat(rest): Provide server version on REST api
  Makefile.conf
  src/www/ui/api/Controllers/InfoController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui_tests/api/Controllers/InfoControllerTest.php
Labels: ready

#2145 refactor(clearingDao): add few functions to a single one
  src/decider/agent_tests/Functional/schedulerTest.php
  src/lib/php/Dao/ClearingDao.php
  src/lib/php/Dao/test/ClearingDaoTest.php
  src/www/ui/async/AjaxExplorer.php
  src/www/ui/ui-clearing-view.php
Labels: ready

#2154 fix(test): fix test failures caused by sysconfig
  src/lib/php/Test/TestPgDb.php
  src/reuser/agent_tests/Functional/schedulerTest.php
Labels: needs code review

#2155 feat(lbtablelength):Added all for license browser table
  src/www/ui/template/browse_file.js.twig
Labels: ready

#2153 feat(upload): allow multifile upload from UI
  src/lib/php/UI/template/include/upload.html.twig
  src/reuser/ui/template/agent_reuser.html.twig
  src/www/ui/api/Controllers/UploadController.php
  src/www/ui/api/Helper/UploadHelper.php
  src/www/ui/page/UploadFilePage.php
  src/www/ui/template/upload_file.html.twig
  src/www/ui_tests/api/Controllers/UploadControllerTest.php
Labels: enhancement, ready

#2136 feat(gdpr) deactivate users + Store last cnx timestamp
  src/lib/php/Dao/UserDao.php
  src/www/ui/api/Helper/AuthHelper.php
  src/www/ui/core-auth.php
  src/www/ui/core-schema.dat
  src/www/ui/page/AdminGroupUsers.php
  src/www/ui/template/user_edit.html.twig
  src/www/ui/user-edit.php
Labels: needs code review, needs test

#2163 fix(testcase): fix test cases for lib
  src/cli/tests/test_fo_copyright_list.php
  src/clixml/agent/clixml.php
  src/lib/c/tests/test_fossscheduler.c
  src/lib/php/Application/test/LicenseCsvImportTest.php
  src/lib/php/BusinessRules/test/ClearingDecisionFilterTest.php
  src/lib/php/Dao/ClearingDao.php
  src/lib/php/Dao/test/FolderDaoTest.php
  src/lib/php/Dao/test/UploadDaoTest.php
  src/lib/php/Dao/test/UserDaoTest.php
  src/lib/php/Data/Clearing/test/ClearingResultTest.php
  src/lib/php/Db/test/DbManagerTest.php
  src/lib/php/Plugin/test/DefaultPluginTest.php
  src/lib/php/Proxy/test/LatestScannerProxyTest.php
  src/lib/php/Proxy/test/UploadBrowseProxyTest.php
  src/lib/php/Proxy/test/UploadTreeViewProxyTest.php
  src/lib/php/Util/test/ArrayOperationTest.php
  src/www/ui_tests/startUpTest.php
Labels: ready

#2164 fix(global): add statement name for global query to fix reuser
  src/lib/php/Dao/ClearingDao.php
Labels: ready

#2160 chore(browse): redirect to license view if empty
  src/www/ui/ui-browse.php
Labels: ready

#2161 feat(dev-ctbutton): Added clean text button at license text field
  src/www/ui/scripts/change-license-browse.js
  src/www/ui/scripts/change-license-common.js
  src/www/ui/scripts/change-license-view.js
  src/www/ui/template/ui-clearing-view_bulk.html.twig
Labels: ready
