Repository fossology/fossology, pull requests merged in 2022-09, with the labels that each got.

#2251 feat(API): get group members with corresponding roles
  src/www/ui/api/Controllers/GroupController.php
  src/www/ui/api/Controllers/UserController.php
  src/www/ui/api/Helper/DbHelper.php
  src/www/ui/api/Models/UserGroupMember.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui_tests/api/Controllers/GroupControllerTest.php
  src/www/ui_tests/api/Controllers/UserControllerTest.php
  src/www/ui_tests/api/Helper/DbHelperTest.php
Labels: ready, GSoC-22

#2275 feat(api): PUT api to Set permissions for a upload and GET API to fetch respective permissions of groups
  src/www/ui/api/Controllers/UploadController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui/page/UploadPermissionPage.php
Labels: ready, GSoC-22

#2290 feat(API): REST-API to initiate FOSSology maintenance
  src/maintagent/ui/maintagent.php
  src/www/ui/api/Controllers/MaintenanceController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui_tests/api/Controllers/MaintenanceControllerTest.php
Labels: GSoC-22

#2292 feat(API): import csv-license file
  src/www/ui/api/Controllers/LicenseController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui/page/AdminLicenseFromCSV.php
  src/www/ui_tests/api/Controllers/LicenseControllerTest.php
Labels: ready, GSoC-22

#2309 feat(api): Download file using UploadID
  src/www/ui/api/Controllers/UploadController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui/ui-download.php
Labels: ready, GSoC-22

#2303 feat(API): add user to a group.
  src/www/ui/api/Controllers/GroupController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui_tests/api/Controllers/GroupControllerTest.php
Labels: ready, GSoC-22

#2276 feat(copyright): SPDX copyright detection added
  src/copyright/agent/cleanEntries.cc
  src/copyright/agent/copyright.conf
  src/copyright/agent/copyscan.cc
  src/copyright/agent/copyscan.hpp
  src/copyright/ui/CopyrightView.php
  src/copyright/ui/HistogramBase.php
  src/copyright/ui/Xpview.php
  src/copyright/ui/ajax-copyright-hist.php
  src/copyright/ui/copyright-hist.php
  src/copyright/ui/list.php
  src/lib/php/Dao/CopyrightDao.php
  src/lib/php/Dao/test/CopyrightDaoTest.php
  src/lib/php/Report/XpClearedGetter.php
  src/lib/php/common-agents.php
  src/reso/agent/ResoAgent.php
  src/reso/ui/ResoAgentPlugin.php
  src/spdx2/agent/spdx2.php
  src/www/ui/ui-export-list.php
Labels: ready, GSoC-22

#2305 feat(oidc): allow user to configure token
  src/lib/php/common-sysconfig.php
  src/www/ui/page/HomePage.php
Labels: ready

#2311 fix(lint): openapi lint corrected
  src/www/ui/api/documentation/openapi.yaml
Labels: needs code review, needs test

#2304 fix(reportImport): remove dual check for access and fix array warning
  src/reportImport/agent/ReportImportAgent.php
  src/reportImport/ui/ReportImportPlugin.php
Labels: ready

#2320 docs(openapi): fix spectral lint warnings/errors
  src/www/ui/api/documentation/openapi.yaml
Labels: ready

#2300 feat(ubuntu): support ubuntu jammy 22.04 for fossology
  .github/workflows/release-publish.yml
  debian/control
  src/copyright/mod_deps
  src/lib/c/fossconfig.c
  src/lib/php/libschema.php
  src/nomos/mod_deps
  src/ojo/mod_deps
  src/scancode/mod_deps
  utils/fo-installdeps
Labels: enhancement, needs code review, needs test
