Repository fossology/fossology, pull requests merged in 2022-11, with the labels that each got.

#2339 fix(debian): prevent duplication of bootstrap
  src/Makefile
  utils/fo-debuild
  utils/utils.sh
Labels: ready

#2340 chore(release): release 4.2.0 changelog
  CHANGELOG.md
  debian/changelog
Labels: needs code review

#2337 feat(user-edit): make use of retention period to display expired tokens
  src/www/ui/user-edit.php
Labels: ready

#2346 fix(conf): add escape string and fetch raw content
  .github/workflows/build-test.yml
  src/www/ui/ui-report-conf.php
Labels: needs test
