Repository fossology/fossology, pull requests merged in 2022-10, with the labels that each got.

#2325 chore(Dockerfile): add OCI annotations
  .github/workflows/docker-build.yml
  .github/workflows/release-publish.yml
  Dockerfile
Labels: enhancement, needs code review, needs test

#2312 feat(reuse): Detect LICENSES folder and generate REUSE summary
  src/lib/php/BusinessRules/DetectLicensesFolder.php
  src/lib/php/BusinessRules/ReuseReportProcessor.php
  src/lib/php/Dao/SearchHelperDao.php
  src/lib/php/services.xml.in
  src/www/ui/ajax-notice-files.php
  src/www/ui/api/Controllers/SearchController.php
  src/www/ui/async/AjaxReuseReport.php
  src/www/ui/scripts/license.js
  src/www/ui/search-helper.php
  src/www/ui/search.php
  src/www/ui/template/browse_license-lic_hist.js.twig
  src/www/ui/template/browse_license-summary.html.twig
Labels: needs code review, needs test, GSoC-22

#2326 feat(changelog): add changelog for release 4.2.0-rc1
  CHANGELOG.md
  debian/changelog
Labels: ready

#2328 fix(licenseView): fix missing comment select
  src/www/ui/scripts/change-license-common.js
  src/www/ui/template/ui-clearing-view_bulk.html.twig
Labels: needs code review, needs test

#2331 feat(composer): update composer dependencies
  .github/workflows/static-checks.yml
  src/composer.json
  src/composer.lock
Labels: ready

#2332 chore(php-jwt): use new features from v6.3.0
  src/composer.json
  src/composer.lock
  src/www/ui/api/Helper/AuthHelper.php
  src/www/ui/page/HomePage.php
Labels: ready

#2334 fix(oneShotMonk): convert value to int to fix php fatal
  src/monk/ui/oneshot.php
Labels: needs test

#2333 fix(unifiedReport): fix line break issue in libre office
  src/unifiedreport/agent/reportStatic.php
  src/unifiedreport/agent/unifiedreport.php
Labels: ready
