Repository fossology/fossology, pull requests merged in 2022-03, with the labels that each got.

#2123 feat(rest): oidc based authentication
  install/defconf/fossology.conf.in
  src/composer.json
  src/composer.lock
  src/lib/php/Auth/Auth.php
  src/lib/php/Dao/UserDao.php
  src/lib/php/UI/template/components/login-form.html.twig
  src/lib/php/common-sysconfig.php
  src/maintagent/agent/process.c
  src/www/ui/admin-config.php
  src/www/ui/api/Controllers/AuthController.php
  src/www/ui/api/Helper/AuthHelper.php
  src/www/ui/api/Helper/DbHelper.php
  src/www/ui/api/Helper/RestHelper.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/async/AjaxManageToken.php
  src/www/ui/core-auth.php
  src/www/ui/core-schema.dat
  src/www/ui/page/HomePage.php
  src/www/ui/template/home.html.twig
  src/www/ui/template/login.html.twig
  src/www/ui/template/user_edit.html.twig
  src/www/ui/user-edit.php
  src/www/ui_tests/api/Controllers/AuthControllerTest.php
  src/www/ui_tests/api/Helper/AuthHelperTest.php
Labels: enhancement, needs code review, needs test

#2159 chore(composer): update composer form 1.9.0 to 2.2.6 version
  utils/install_composer.sh
Labels: question, ready

#2169 feat(report): accept package URL
  src/clixml/agent/clixml.php
  src/clixml/agent/template/clixml-file.xml.twig
  src/clixml/ui/CliXmlGeneratorUi.php
  src/lib/php/Dao/SpashtDao.php
  src/lib/php/Data/Package/ComponentType.php
  src/lib/php/Util/PurlOperations.php
  src/spasht/ui/ui-spasht.php
  src/spdx2/agent/spdx2.php
  src/spdx2/agent/template/spdx2-package.xml.twig
  src/spdx2/agent/template/spdx2tv-package.twig
  src/unifiedreport/agent/reportSummary.php
  src/www/ui/core-schema.dat
  src/www/ui/template/ui-report-conf.html.twig
  src/www/ui/ui-report-conf.php
Labels: needs code review, needs test

#2177 test(ci): run docker tests in GitHub Actions
  .github/workflows/docker-test.yml
  debian/changelog
  src/testing/docker/test-cluster.sh
  src/testing/docker/test-standalone.sh
Labels: ready

#2179 hotfix(rest): fix file upload
  src/www/ui/api/Helper/AuthHelper.php
  src/www/ui/api/Helper/UploadHelper.php
Labels: ready

#2184 hotfix(rest): fix scope for oauth
  src/www/ui/api/Helper/AuthHelper.php
Labels: ready

#2174 fix(api): Return full uploadId
  src/www/ui/api/Controllers/UploadController.php
  src/www/ui/api/Helper/UploadHelper/HelperToUploadFilePage.php
  src/www/ui_tests/api/Controllers/UploadControllerTest.php
Labels: ready

#2189 fix(openapi.yaml): OpenAPI Description: Fixed typo in HeathInfo
  src/www/ui/api/documentation/openapi.yaml
Labels: ready

#2182 feat(nomos): add 'BSD-4-Clause-Shortened' license
  src/nomos/agent/STRINGS.in
  src/nomos/agent/parse.c
Labels: ready

#2183 fix(nomos): Improved nomos GPL detection
  src/nomos/agent/STRINGS.in
  src/nomos/agent/parse.c
Labels: ready

#2195 fix(API): Fixes FossologyUI CORS error for localhost
  src/lib/php/common-sysconfig.php
Labels: needs test
