Repository fossology/fossology, pull requests merged in 2022-08, with the labels that each got.

#2271 fix(reuser): add scancode as dependency if sched
  src/reuser/ui/agent-reuser.php
  src/scancode/ui/agent-scancode.php
Labels: needs test

#2286 fix(copyright): fix regex conf files
  install/defconf/Db.conf.in
  install/defconf/Db.conf.in.license
  install/defconf/fossology.conf.in
  install/src-install-apache-example.conf
  src/copyright/agent/copyright.conf
  src/copyright/agent/ecc.conf
Labels: needs code review, needs test

#2278 feat(ui): close banner for a session
  .gitignore
  src/copyright/ui/template/copyrighthist.html.twig
  src/copyright/ui/template/ui-cp-view.html.twig
  src/lib/php/UI/Component/Menu.php
  src/lib/php/UI/template/components/menu.html.twig
  src/lib/php/UI/template/include/foot.html.twig
  src/spasht/ui/template/agent_spasht.html.twig
  src/www/ui/core-auth.php
  src/www/ui/template/ui-browse.html.twig
  src/www/ui/template/ui-export-list.html.twig
  src/www/ui/template/ui-report-conf.html.twig
Labels: needs code review, needs test

#2247 feat(API): list groups that can be deleted
  src/www/ui/api/Controllers/GroupController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui_tests/api/Controllers/GroupControllerTest.php
Labels: ready, GSoC-22

#2262 feat(api): Added `users/{id}` PUT route to modify user details
  src/lib/php/common-agents.php
  src/www/ui/api/Controllers/UserController.php
  src/www/ui/api/Helper/DbHelper.php
  src/www/ui/api/Helper/UserHelper.php
  src/www/ui/api/Models/User.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui/user-edit.php
  src/www/ui_tests/api/Controllers/UserControllerTest.php
  src/www/ui_tests/api/Helper/DbHelperTest.php
  src/www/ui_tests/api/Models/UserTest.php
Labels: ready, GSoC-22

#2266 feat(api): added `/users/tokens` POST Route and `/users/tokens/{type}` GET Route
  src/www/ui/api/Controllers/UserController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui/async/AjaxManageToken.php
  src/www/ui/user-edit.php
Labels: ready, GSoC-22

#2256 feat(API): `users/` post route for adding a new user
  src/www/ui/api/Controllers/UserController.php
  src/www/ui/api/Helper/DbHelper.php
  src/www/ui/api/Helper/UserHelper.php
  src/www/ui/api/Models/User.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui/template/user_add.html.twig
  src/www/ui/user-add.php
  src/www/ui_tests/api/Controllers/UserControllerTest.php
  src/www/ui_tests/api/Helper/DbHelperTest.php
Labels: enhancement, needs test, GSoC-22
