Repository fossology/fossology, pull requests merged in 2022-05, with the labels that each got.

#2212 fix(copyright): do not update empty copyrights
  install/db/Makefile
  install/db/dbmigrate_3.7-3.8.php
  install/db/dbmigrate_4.0-4.1.php
  install/db/instance_uuid.php
  install/fossinit.php
  src/copyright/ui/ajax-copyright-hist.php
  src/lib/php/Dao/CopyrightDao.php
Labels: ready

#2216 fix(jwt): explicitly declare jwk algorithm
  src/composer.json
  src/composer.lock
  src/lib/php/common-sysconfig.php
  src/www/ui/api/Helper/AuthHelper.php
  src/www/ui/page/HomePage.php
Labels: needs test, dependencies

#2221 fix(scancode): move python dependencies
  Dockerfile
  install/fo-install-pythondeps
  src/scancode/agent/scancode_wrapper.cc
  src/scancode/mod_deps
  src/scancode/ui/agent-scancode.php
Labels: ready

#2220 chore(release): release 4.1.0
  CHANGELOG.md
  debian/changelog
Labels: needs test

#2219 fix(ui): restore license text for bulk modal
  src/www/ui/scripts/ui-clearing-view_bulk.js
Labels: ready

#2218 fix(reuser): reuse all report columns
  src/lib/php/Dao/UploadDao.php
Labels: enhancement, ready

#2217 chore(component-id): use package-url instead purl
  src/clixml/agent/clixml.php
  src/lib/php/Dao/SpashtDao.php
  src/lib/php/Data/Package/ComponentType.php
  src/lib/php/Report/ObligationsGetter.php
  src/spdx2/agent/spdx2.php
  src/www/ui/core-schema.dat
  src/www/ui/template/ui-report-conf.html.twig
  src/www/ui/ui-report-conf.php
Labels: ready

#2224 fix(uploadPermission):introduced error on changing upload permissions
  src/www/ui/page/UploadPermissionPage.php
Labels: ready

#2209 fix(default_group): exposed deafult_group in /users/self
  src/www/ui/api/Controllers/UserController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui_tests/api/Controllers/UserControllerTest.php
Labels: ready

#2227 fix(ci): update spectral-action to fix ci test
  .github/workflows/static-checks.yml
Labels: needs test
