Repository fossology/fossology, pull requests merged in 2022-01, with the labels that each got.

#2132 feat(nomos): See file regex to include view
  src/nomos/agent/STRINGS.in
  src/nomos/agent_tests/testdata/LastGoodNomosTestfilesScan
  src/nomos/agent_tests/testdata/NomosTestfiles/See-file/ContainerRuntimeLoaderTest.php
Labels: ready

#2131 feat(nomos): New see-url pattern
  src/nomos/agent/STRINGS.in
  src/nomos/agent/parse.c
Labels: enhancement, ready

#2138 Feat/user details read only2
  src/lib/php/common-sysconfig.php
  src/www/ui/template/user_edit.html.twig
  src/www/ui/user-edit.php
Labels: ready

#2133 feat(reports): Add new CSV report type
  pbconf/fossology/rpm/fossology.spec
  src/spdx2/Makefile
  src/spdx2/agent/Makefile
  src/spdx2/agent/spdx2.php
  src/spdx2/agent/template/spdx2csv-document.twig
  src/spdx2/agent/template/spdx2csv-file.twig
  src/spdx2/agent/template/spdx2csv-package.twig
  src/spdx2/spdx2csv.conf
  src/spdx2/ui/Makefile
  src/spdx2/ui/SpdxTwoCommaSeparatedValuesAgentPlugin.php
  src/spdx2/ui/SpdxTwoGeneratorUi.php
  src/www/ui/async/AjaxShowJobs.php
Labels: enhancement, ready

#2141 fix(ui): Fix bulk modal with selectable bg
  src/www/ui/scripts/change-license-browse.js
  src/www/ui/scripts/change-license-common.js
  src/www/ui/scripts/change-license-view.js
  src/www/ui/template/ui-clearing-view_bulk.html.twig
  src/www/ui/template/ui-clearing-view_rhs.html.twig
Labels: needs code review, needs test

#2122 feat(upload): make global decisions configurable in all upload pages
  src/cli/cp2foss.php
  src/lib/php/Dao/ClearingDao.php
  src/lib/php/Dao/UploadDao.php
  src/lib/php/Proxy/UploadTreeProxy.php
  src/lib/php/Test/testdata.sql
  src/lib/php/UI/template/include/upload.html.twig
  src/lib/php/common-job.php
  src/monk/agent_tests/Functional/bulkTest.php
  src/reuser/agent_tests/Functional/schedulerTest.php
  src/www/ui/api/Controllers/UploadController.php
  src/www/ui/api/Helper/UploadHelper.php
  src/www/ui/api/Middlewares/RestAuthMiddleware.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/core-schema.dat
  src/www/ui/page/UploadFilePage.php
  src/www/ui/page/UploadSrvPage.php
  src/www/ui/page/UploadUrlPage.php
  src/www/ui/page/UploadVcsPage.php
  src/www/ui/template/ui-report-conf.html.twig
  src/www/ui/ui-report-conf.php
  src/www/ui_tests/api/Controllers/UploadControllerTest.php
  src/www/ui_tests/api/Helper/AuthHelperTest.php
Labels: needs test

#2143 feat(changelog): add changelog for release 4.0.0
  CHANGELOG.md
  debian/changelog
Labels: needs code review

#2142 Changed tool tip description for "Do not use."
  src/www/ui/template/ui-clearing-view_rhs.html.twig
Labels: ready, needs code review
