Repository fossology/fossology, pull requests merged in 2023-06, with the labels that each got.

#2448 fix(bulkReuse): concider folder level and package level bulk
  src/decider/agent/BulkReuser.php
  src/decider/agent_tests/Functional/schedulerTest.php
Labels: ready

#2396 fix(user-add.php): Fixed email can be blank but required
  src/www/ui/user-add.php
Labels: ready, needs squash

#2398 fix(user-edit.php): Fixed editing emails allows for duplicate emails …
  src/www/ui/user-edit.php
Labels: ready

#2489 feat(changelog): add changelog for release 4.3.0
  CHANGELOG.md
  debian/changelog
Labels: needs test

#2407 feat(delete-job-endpoint): Added a delete job endpoint to the Fossolo…
  src/www/ui/api/Controllers/JobController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
Labels: ready

#2417 fix(clixml.php): Fixed the issue of PHP 8 Warning
  src/clixml/agent/clixml.php
Labels: ready

#2419 fix(eyeButtonForPasswords): removed external css usage
  src/lib/php/Plugin/DefaultPlugin.php
  src/lib/php/Plugin/FO_Plugin.php
  src/lib/php/UI/template/components/login-form.html.twig
  src/www/ui/css/bootstrap-icons.css
  src/www/ui/images/eyes.png
  src/www/ui/scripts/togglePasswords.js
  src/www/ui/template/home.html.twig
  src/www/ui/template/login.html.twig
  src/www/ui/template/user_add.html.twig
  src/www/ui/template/user_edit.html.twig
  src/www/ui/user-add.php
Labels: ready

#2458 refactor(copyright): Refactored some redundant code.
  src/decider/agent/copyrightDeactivationClutterRemovalScript.py
Labels: ready, GSOC-23

#2474 feat(api): openapi.yaml exposed through API
  src/www/ui/api/Controllers/InfoController.php
  src/www/ui/api/Middlewares/RestAuthMiddleware.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui_tests/api/Controllers/InfoControllerTest.php
Labels: ready, GSOC-23

#2456 feat(api): get the contents of the file
  src/www/ui/api/Controllers/UploadTreeController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui/ui-view.php
  src/www/ui_tests/api/Controllers/UploadTreeControllerTest.php
Labels: ready, GSOC-23

#2430 feat(api): add pagination to license browser
  src/www/ui/api/Controllers/UploadController.php
  src/www/ui/api/Helper/UploadHelper.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui_tests/api/Controllers/UploadControllerTest.php
Labels: ready

#2460 feat(api): set the clearing decision for a particular item
  src/www/ui/api/Controllers/UploadTreeController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui/ui-clearing-view.php
  src/www/ui_tests/api/Controllers/UploadTreeControllerTest.php
Labels: ready, GSOC-23
