Repository fossology/fossology, pull requests merged in 2023-10, with the labels that each got.

#2551 feat(api): Get removable folder contents
  src/www/ui/api/Controllers/FolderController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui/async/AjaxFolderContents.php
Labels: ready, GSOC-23

#2552 feat(api): Unlink folder contents
  src/lib/php/Dao/FolderDao.php
  src/www/ui/api/Controllers/FolderController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
Labels: ready, GSOC-23

#2553 feat(api): Get banner message
  src/lib/php/Dao/SysConfigDao.php
  src/www/ui/api/Controllers/CustomiseController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
Labels: ready, GSOC-23

#2555 feat(api): Get all contents of a specific folder
  src/www/ui/api/Controllers/FolderController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui/async/AjaxFolderContents.php
Labels: needs code review, needs test, GSOC-23

#2559 feat(api): api to get the list of obligations
  src/lib/php/services.xml.in
  src/www/ui/admin-obligation-file.php
  src/www/ui/api/Controllers/ObligationController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
Labels: needs code review, needs test, GSOC-23

#2562 feat(api): The REST API to export licenses-list as CSV
  src/www/ui/api/Controllers/LicenseController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
Labels: needs code review, needs test, GSOC-23

#2564 feat(api): get details of a particular obligation using id
  src/lib/php/BusinessRules/ObligationMap.php
  src/www/ui/api/Controllers/ObligationController.php
  src/www/ui/api/Models/Obligation.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
Labels: needs code review, needs test, GSOC-23

#2565 feat(api): Get details of all obligations
  src/www/ui/api/Controllers/ObligationController.php
  src/www/ui/api/Models/Obligation.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
Labels: ready, GSOC-23

#2569 perf(scancode):Improve scanning speed of scancode agent
  src/scancode/agent/CMakeLists.txt
  src/scancode/agent/runscanonfiles.py
  src/scancode/agent/scancode_template.html
  src/scancode/agent/scancode_utils.cc
  src/scancode/agent/scancode_utils.hpp
  src/scancode/agent/scancode_wrapper.cc
  src/scancode/agent/scancode_wrapper.hpp
Labels: ready, GSOC-23

#2563 feat(api): Import obligation list from CSV
  src/www/ui/api/Controllers/LicenseController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui/page/AdminObligationFromCSV.php
Labels: ready, GSOC-23

#2568 feat(api): Delete obligation using id
  src/lib/php/BusinessRules/ObligationMap.php
  src/www/ui/admin-obligation-file.php
  src/www/ui/api/Controllers/ObligationController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
Labels: needs code review, needs test, GSOC-23

#2586 fix(test): fix wrong test according to comment
  src/buckets/ui/bucket-diff.php
  src/nomos/agent_tests/testdata/NomosTestfiles/GPL/nomos-diff-GPLv2.php
  src/nomos/ui/nomos-diff.php
Labels: ready

#2574 feat(api): Export Obligation list as CSV
  src/lib/php/Application/ObligationCsvExport.php
  src/www/ui/api/Controllers/LicenseController.php
  src/www/ui/api/Controllers/ObligationController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
Labels: ready, GSOC-23

#2590 feat(schedule agent): add select2 to search for uploads with name
  src/www/ui/template/agent_adder.html.twig
Labels: ready

#2595 feat(api): add 'topitem' endpoint to Upload API
  src/www/ui/api/Controllers/UploadController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
Labels: ready

#2600 fix(php) Optional parameter declared before required parameter
  src/readmeoss/agent/readmeoss.php
  src/testing/lib/fossologyTestCase.php
  src/testing/lib/libTestDB.php
Labels: ready

#2601 fix(php): Using ${var} in strings is deprecated
  src/lib/php/common-active.php
  src/www/ui/upload-instructions.php
Labels: ready

#2598 refactor(api): introduce error handling
  src/lib/php/common-sysconfig.php
  src/www/ui/api/Controllers/AuthController.php
  src/www/ui/api/Controllers/BadRequestController.php
  src/www/ui/api/Controllers/ConfController.php
  src/www/ui/api/Controllers/CopyrightController.php
  src/www/ui/api/Controllers/CustomiseController.php
  src/www/ui/api/Controllers/FileInfoController.php
  src/www/ui/api/Controllers/FileSearchController.php
  src/www/ui/api/Controllers/FolderController.php
  src/www/ui/api/Controllers/GroupController.php
  src/www/ui/api/Controllers/InfoController.php
  src/www/ui/api/Controllers/JobController.php
  src/www/ui/api/Controllers/LicenseController.php
  src/www/ui/api/Controllers/MaintenanceController.php
  src/www/ui/api/Controllers/ObligationController.php
  src/www/ui/api/Controllers/OverviewController.php
  src/www/ui/api/Controllers/ReportController.php
  src/www/ui/api/Controllers/RestController.php
  src/www/ui/api/Controllers/SearchController.php
  src/www/ui/api/Controllers/UploadController.php
  src/www/ui/api/Controllers/UploadTreeController.php
  src/www/ui/api/Controllers/UserController.php
  src/www/ui/api/Exceptions/HttpBadRequestException.php
  src/www/ui/api/Exceptions/HttpConflictException.php
  src/www/ui/api/Exceptions/HttpErrorException.php
  src/www/ui/api/Exceptions/HttpForbiddenException.php
  src/www/ui/api/Exceptions/HttpInternalServerErrorException.php
  src/www/ui/api/Exceptions/HttpNotFoundException.php
  src/www/ui/api/Exceptions/HttpPreconditionFailException.php
  src/www/ui/api/Exceptions/HttpServiceUnavailableException.php
  src/www/ui/api/Exceptions/HttpTooManyRequestException.php
  src/www/ui/api/Helper/AuthHelper.php
  src/www/ui/api/Helper/CorsHelper.php
  src/www/ui/api/Helper/RestHelper.php
  src/www/ui/api/Helper/UploadHelper.php
  src/www/ui/api/Helper/UserHelper.php
  src/www/ui/api/Middlewares/FossologyInitMiddleware.php
  src/www/ui/api/Middlewares/RestAuthMiddleware.php
  src/www/ui/api/Models/ScanOptions.php
  src/www/ui/api/index.php
  src/www/ui/user-edit.php
  src/www/ui_tests/api/Controllers/AuthControllerTest.php
  src/www/ui_tests/api/Controllers/FolderControllerTest.php
  src/www/ui_tests/api/Controllers/GroupControllerTest.php
  src/www/ui_tests/api/Controllers/InfoControllerTest.php
  src/www/ui_tests/api/Controllers/JobControllerTest.php
  src/www/ui_tests/api/Controllers/LicenseControllerTest.php
  src/www/ui_tests/api/Controllers/MaintenanceControllerTest.php
  src/www/ui_tests/api/Controllers/ReportControllerTest.php
  src/www/ui_tests/api/Controllers/UploadControllerTest.php
  src/www/ui_tests/api/Controllers/UploadTreeControllerTest.php
  src/www/ui_tests/api/Controllers/UserControllerTest.php
  src/www/ui_tests/api/Helper/AuthHelperTest.php
  src/www/ui_tests/api/Helper/RestHelperTest.php
Labels: ready

#2588 feat(unifiedreport): support json format for rows and also html break
  src/lib/php/common-sysconfig.php
  src/unifiedreport/agent/reportStatic.php
Labels: ready

#2606 fix(php): replace deprecated split by explode
  src/testing/lib/TestRun.php
  src/testing/lib/fossologyTest.php
  src/testing/lib/reportClass.php
  src/testing/utils/createUIUsers.php
  src/testing/utils/simpleUi-users.php
Labels: ready

#2604 fix(php): add missing semicolon
  src/nomos/agent_tests/testdata/NomosTestfiles/GPL/Autoload.php
Labels: needs code review, needs test

#2605 fix(php): remove & to be compatible with PHP 8
  utils/freshmeat/Classes/FreshmeatRdfs.php
  utils/freshmeat/lib_projxml.h.php
  utils/freshmeat/tests/runGp.php
Labels: ready

#2607 fix(php): Factor common code
  src/cli/acme_review.php
  src/clixml/agent/clixml.php
  src/copyright/ui/TextFindingsAjax.php
  src/copyright/ui/ajax-copyright-hist.php
  src/copyright/ui/library.php
  src/copyright/ui/oneshot.php
  src/cyclonedx/agent/reportgenerator.php
  src/debug/ui/core-debug-menus.php
  src/delagent/ui/delete-helper.php
  src/lib/php/Application/ObligationCsvImport.php
  src/lib/php/Dao/AgentDao.php
  src/lib/php/Dao/AllDecisionsDao.php
  src/lib/php/Dao/CopyrightDao.php
  src/lib/php/Dao/HighlightDao.php
  src/lib/php/Dao/LicenseDao.php
  src/lib/php/Dao/ShowJobsDao.php
  src/lib/php/Dao/UploadDao.php
  src/lib/php/Proxy/UploadBrowseProxy.php
  src/lib/php/Test/Agent/AgentTestMockHelper.php
  src/lib/php/UI/Component/Menu.php
  src/lib/php/Util/DataTablesUtility.php
  src/lib/php/View/UrlBuilder.php
  src/lib/php/common-active.php
  src/lib/php/common-auth.php
  src/lib/php/common-cli.php
  src/lib/php/common-dir.php
  src/lib/php/common-sysconfig.php
  src/lib/php/common-ui.php
  src/lib/php/fossdash-config.php
  src/lib/php/libschema.php
  src/lib/php/tests/test_common_active.php
  src/maintagent/ui/maintagent.php
  src/nomos/ui/ajax-filelic.php
  src/reuser/agent/ReuserAgent.php
  src/spasht/ui/ui-spasht.php
  src/testing/fo_integration.php
  src/ununpack/ui/ui-reunpack.php
  src/www/ui/admin-dashboard-general.php
  src/www/ui/admin-tag.php
  src/www/ui/ajax-clearing-view.php
  src/www/ui/async/AjaxBrowse.php
  src/www/ui/core-smauth.php
  src/www/ui/page/BrowseLicense.php
  src/www/ui/page/UploadPermissionPage.php
  src/www/ui/search.php
  src/www/ui/showjobs.php
  utils/backup/fo-restore.php
  utils/freshmeat/get-projects.php
Labels: ready

#2608 fix(spdx): de-duplicate licenses with same SPDX ID
  src/cyclonedx/agent/cyclonedx.php
  src/lib/php/Data/Clearing/ClearingEvent.php
  src/lib/php/Data/License.php
  src/lib/php/Data/Report/FileNode.php
  src/lib/php/Data/Report/SpdxLicenseInfo.php
  src/lib/php/Report/ObligationsGetter.php
  src/lib/php/Report/ReportUtils.php
  src/spdx2/agent/spdx2.php
  src/spdx2/agent/template/listedlicense.xml.twig
  src/spdx2/agent/template/spdx2-document.xml.twig
  src/spdx2/agent/template/spdx2-file.xml.twig
  src/spdx2/agent/template/spdx2-package.xml.twig
  src/spdx2/agent/template/spdx2csv-file.twig
  src/spdx2/agent/template/spdx2tv-document.twig
  src/spdx2/agent/template/spdx2tv-file.twig
  src/spdx2/agent/template/spdx2tv-package.twig
  src/spdx2/agent_tests/Functional/fo_report.sql
  src/www/ui/page/AdminLicenseFromCSV.php
  src/www/ui/page/AdminObligationFromCSV.php
  src/www/ui/template/admin_license_from_csv.html.twig
Labels: ready

#2616 changed varchar(32) to text
  src/www/ui/core-schema.dat
Labels: ready

#2613 chore(ci): tag scanner image on release
  .github/workflows/release-publish.yml
Labels: ready

#2602 feat(dashboard): add new page for upload and folder dashboard
  src/www/ui/admin-folder-size.php
  src/www/ui/template/admin-folder-size-form.html.twig
Labels: ready

#2550 feat(nomos): add more regex to nomos to identify different licenses
  src/nomos/agent/generator/STRINGS.in
  src/nomos/agent/parse.c
  src/nomos/agent_tests/testdata/LastGoodNomosTestfilesScan
  src/nomos/agent_tests/testdata/NomosTestfiles/CC/perl-XML-Writer.spec
  src/nomos/agent_tests/testdata/NomosTestfiles/Nvidia/mix_transformer.py
  src/nomos/agent_tests/testdata/NomosTestfiles/See-file/segformer.py
Labels: ready

#2591 feat(conf): support CLIXML conf for a upload
  src/clixml/agent/clixml.php
  src/clixml/agent/template/clixml-file.xml.twig
  src/lib/php/Dao/UploadDao.php
  src/www/ui/core-schema.dat
  src/www/ui/template/ui-report-conf.html.twig
  src/www/ui/ui-report-conf.php
Labels: ready
