Repository fossology/fossology, pull requests merged in 2023-09, with the labels that each got.

#2581 doc(php): fix parameter docs
  src/cli/fo_tagfile.php
  src/clixml/ui/CliXmlGeneratorUi.php
  src/cyclonedx/agent/reportgenerator.php
  src/cyclonedx/ui/CycloneDXGeneratorUi.php
  src/lib/php/Dao/ClearingDao.php
  src/lib/php/Dao/CopyrightDao.php
  src/lib/php/Dao/PackageDao.php
  src/lib/php/Dao/ShowJobsDao.php
  src/lib/php/Dao/UploadDao.php
  src/lib/php/Db/DbManager.php
  src/lib/php/Plugin/AgentPlugin.php
  src/lib/php/Proxy/UploadTreeProxy.php
  src/lib/php/UI/Component/MicroMenu.php
  src/lib/php/common-plugin.php
  src/reportImport/agent/ReportImportSink.php
  src/spasht/agent/SpashtAgent.php
  src/testing/install/pkgConfig.php
  src/testing/install/test4packageinstall/testdata.php
  src/testing/lib/common-Test.php
  src/testing/lib/fossologyTestCase.php
  src/testing/lib/reportClass.php
  src/testing/lib/testClasses/parseFolderPath.php
  src/unifiedreport/agent/reportStatic.php
  src/unifiedreport/agent/reportSummary.php
  src/unifiedreport/agent/unifiedreport.php
  src/www/ui/api/Controllers/UploadTreeController.php
  src/www/ui/api/Middlewares/FossologyInitMiddleware.php
  src/www/ui/api/Models/FileInfo.php
  src/www/ui/page/AdviceLicense.php
  src/www/ui/page/UploadFilePage.php
  src/www/ui/page/UploadSrvPage.php
  src/www/ui/page/UploadVcsPage.php
  src/www/ui/ui-clearing-view.php
  src/www/ui/ui-download.php
  src/www/ui/ui-view.php
  utils/freshmeat/Classes/FreshmeatRdfs.php
  utils/freshmeat/lib_projxml.h.php
Labels: needs code review

#2578 feat(ununpack): support for Zstandard
  cmake/FoPackaging.cmake
  src/ununpack/agent/CMakeLists.txt
  src/ununpack/agent/externs.h
  src/ununpack/agent/traverse.c
  src/ununpack/agent/ununpack-zstd.c
  src/ununpack/agent/ununpack-zstd.h
  src/ununpack/agent/ununpack.c
  src/ununpack/agent/ununpack.h
  src/ununpack/agent/ununpack_globals.h
  src/ununpack/agent/utils.c
  src/ununpack/agent_tests/CMakeLists.txt
  src/ununpack/agent_tests/Functional/cliParamsTest4UnunpackNormal.php
  src/ununpack/agent_tests/Unit/run_tests.c
  src/ununpack/agent_tests/Unit/test_ununpack-zstd.c
  src/ununpack/agent_tests/testdata/testdata.tar.bz2
  src/ununpack/mod_deps
Labels: ready

#2518 feat(api): Add, Edit & toggle standard-license comment
  src/www/ui/api/Controllers/LicenseController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui_tests/api/Controllers/LicenseControllerTest.php
Labels: ready, GSOC-23

#2427 docs(README.md): adding more details about `docker-compose` cmd
  README.md
Labels: ready

#2528 feat(api): verify license as new or variant
  src/www/ui/api/Controllers/LicenseController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui/page/AdminLicenseCandidate.php
Labels: ready, GSOC-23

#2529 feat(api): Merge a license into an existing one
  src/www/ui/api/Controllers/LicenseController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui/page/AdminLicenseCandidate.php
Labels: ready, GSOC-23

#2530 feat(api): Get the database contents for the dashboard overview
  src/www/ui/admin-dashboard-general.php
  src/www/ui/api/Controllers/OverviewController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
Labels: ready, GSOC-23

#2534 feat(api): Get disk space usage overview
  src/www/ui/admin-dashboard-general.php
  src/www/ui/api/Controllers/OverviewController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
Labels: ready, has merge conflicts, GSOC-23

#2535 feat(api): Get PHP-Info for the Dasbhoard Overview
  src/www/ui/admin-dashboard-general.php
  src/www/ui/api/Controllers/OverviewController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
Labels: ready, GSOC-23

#2536 feat(api): Get all server jobs for Admin Dashboard
  src/www/ui/api/Controllers/JobController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui/async/AjaxAllJobStatus.php
Labels: ready, GSOC-23

#2476 feat(scanner): generate spdx report
  utils/automation/.github-workflow.yml
  utils/automation/.gitlab-ci.sample.yml
  utils/automation/Dockerfile.ci
  utils/automation/FoScanner/ApiConfig.py
  utils/automation/FoScanner/CliOptions.py
  utils/automation/FoScanner/RepoSetup.py
  utils/automation/FoScanner/Scanners.py
  utils/automation/FoScanner/SpdxReport.py
  utils/automation/FoScanner/__init__.py
  utils/automation/allowlist.sample.json
  utils/automation/allowlist.sample.json.license
  utils/automation/fossologyscanner.py
  utils/automation/requirements.txt
Labels: needs code review, needs test

#2524 feat(api): Search & suggest license from the reference text
  src/monk/ui/oneshot.php
  src/www/ui/api/Controllers/LicenseController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui/page/AdminLicenseCandidate.php
Labels: ready, GSOC-23

#2532 feat(api): Get database metrics overview for dashboard
  src/www/ui/admin-dashboard-general.php
  src/www/ui/api/Controllers/OverviewController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
Labels: ready, GSOC-23

#2533 feat(api): Get active queries for Dashboard overview
  src/www/ui/admin-dashboard-general.php
  src/www/ui/api/Controllers/OverviewController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
Labels: ready, GSOC-23

#2538 feat(api): Get scheduler options for a given operation
  src/www/ui/admin-scheduler.php
  src/www/ui/api/Controllers/JobController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui/async/AjaxAdminScheduler.php
Labels: ready, GSOC-23

#2539 feat(api): Run scheduler based on the given operation
  src/www/ui/admin-dashboard-general.php
  src/www/ui/admin-scheduler.php
  src/www/ui/api/Controllers/JobController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
Labels: ready, GSOC-23

#2545 feat(api): Update customise data
  src/lib/php/Dao/SysConfigDao.php
  src/www/ui/api/Controllers/CustomiseController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
Labels: ready, GSOC-23

#2549 feat(api): Update Conf data endpoint implemented
  src/lib/php/Dao/UploadDao.php
  src/www/ui/admin-dashboard-general.php
  src/www/ui/api/Controllers/ConfController.php
  src/www/ui/api/Models/Conf.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
Labels: needs code review, needs test, GSOC-23

#2592 chore(api): update API version 20230929
  src/www/ui/api/documentation/openapi.yaml
Labels: needs code review
