Repository fossology/fossology, pull requests merged in 2023-02, with the labels that each got.

#2373 fix(unifiedReport): fix table distortion for component link
  src/unifiedreport/agent/reportStatic.php
  src/unifiedreport/agent/reportSummary.php
  src/unifiedreport/agent/unifiedreport.php
Labels: ready

#2259 feat(API): change group member's permission
  .github/workflows/build-test.yml
  .github/workflows/static-checks.yml
  src/copyright/agent_tests/Functional/schedulerTest.php
  src/lib/php/Db/test/DbManagerTest.php
  src/lib/php/Db/test/ModernDbManagerTest.php
  src/lib/php/Db/test/SolidDbManagerTest.php
  src/lib/php/Html/test/SimpleElementTest.php
  src/lib/php/Plugin/test/DefaultPluginTest.php
  src/lib/php/Report/tests/ClearedGetterCommonTest.php
  src/monk/agent_tests/Functional/bulkTest.php
  src/monk/agent_tests/Functional/cliTest.php
  src/phpunit.xml
  src/spdx2/agent_tests/Unit/spdx2utilTest.php
  src/www/ui/api/Controllers/GroupController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui/page/AdminGroupUsers.php
  src/www/ui_tests/api/Controllers/GroupControllerTest.php
Labels: enhancement, ready, GSoC-22

#2288 feat(api): clearing status
  src/lib/php/Dao/LicenseDao.php
  src/www/ui/api/Helper/UploadHelper.php
  src/www/ui/api/Models/FileLicenses.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/ui-export-list.php
Labels: needs code review, needs test, GSoC-22

#2295 feat(API): get admin-license candidates
  src/www/ui/api/Controllers/LicenseController.php
  src/www/ui/api/Models/LicenseCandidate.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui/page/AdminLicenseCandidate.php
  src/www/ui_tests/api/Controllers/LicenseControllerTest.php
Labels: ready, GSoC-22

#2298 feat(API): delete admin-license candidate
  src/www/ui/api/Controllers/LicenseController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui/page/AdminLicenseCandidate.php
  src/www/ui_tests/api/Controllers/LicenseControllerTest.php
Labels: ready, GSoC-22
