Repository fossology/fossology, pull requests merged in 2023-07, with the labels that each got.

#2462 feat(api): add the new main license for the upload
  src/www/ui/api/Controllers/UploadController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui_tests/api/Controllers/UploadControllerTest.php
Labels: ready, GSOC-23

#2463 feat(api): Remove a particular main license from an upload
  src/www/ui/api/Controllers/UploadController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui_tests/api/Controllers/UploadControllerTest.php
Labels: ready, GSOC-23

#2451 feat(scanner): support github in scanner
  utils/automation/.github-workflow.yml
  utils/automation/fossologyscanner.py
Labels: ready

#2475 feat(api): copyright info for file
  src/copyright/ui/ajax-copyright-hist.php
  src/www/ui/api/Controllers/CopyrightController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
Labels: needs code review, has merge conflicts, needs test, GSOC-23

#2479 feat(api): API for updating File copyright content
  src/www/ui/api/Controllers/CopyrightController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
Labels: ready, GSOC-23

#2480 feat(api): API to handle three filters to get prev & next item
  src/www/ui/api/Controllers/UploadTreeController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui_tests/api/Controllers/UploadTreeControllerTest.php
Labels: ready, GSOC-23

#2481 feat(api): Get list of bulk-history API
  src/www/ui/api/Controllers/UploadTreeController.php
  src/www/ui/api/Models/BulkHistory.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui_tests/api/Controllers/UploadTreeControllerTest.php
Labels: ready, GSOC-23

#2477 feat(api): Get clearing-history API for an item
  src/lib/php/Data/DecisionTypes.php
  src/www/ui/api/Controllers/UploadTreeController.php
  src/www/ui/api/Models/ClearingHistory.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui_tests/api/Controllers/UploadTreeControllerTest.php
Labels: ready, GSOC-23

#2484 feat(api): REST API to get keywords and highlight-entries from content
  src/lib/php/Data/Highlight.php
  src/www/ui/api/Controllers/UploadTreeController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui/ui-clearing-view.php
  src/www/ui_tests/api/Controllers/UploadTreeControllerTest.php
Labels: ready, GSOC-23

#2486 feat(api): restore deleted copyrights
  src/www/ui/api/Controllers/CopyrightController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
Labels: ready, GSOC-23

#2494 feat(api): Get the clearing-progress info for an upload.
  src/lib/php/Proxy/UploadTreeProxy.php
  src/www/ui/api/Controllers/UploadController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui_tests/api/Controllers/UploadControllerTest.php
Labels: ready, GSOC-23

#2497 feat(api): get licenses histogram for an upload
  src/www/ui/api/Controllers/UploadController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
Labels: ready, GSOC-23

#2488 feat(api): API to return total number of copyrights for a file
  src/lib/php/Dao/CopyrightDao.php
  src/www/ui/api/Controllers/CopyrightController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
Labels: ready, GSOC-23

#2502 feat(api): get all agents for the upload
  src/www/ui/api/Controllers/UploadController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
Labels: ready, GSOC-23

#2499 feat(api): Update Upload Summary API to add more info
  src/www/ui/api/Controllers/UploadController.php
  src/www/ui/api/Models/UploadSummary.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/page/BrowseLicense.php
  src/www/ui_tests/api/Models/UploadSummaryTest.php
Labels: ready, GSOC-23

#2492 feat(api): get the license tree-view of the upload and item
  src/www/ui/api/Controllers/UploadTreeController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui/async/AjaxExplorer.php
Labels: ready, GSOC-23

#2498 feat(api): get edited licenses list for an upload
  src/www/ui/api/Controllers/UploadController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
Labels: ready, GSOC-23

#2512 feat(api): Get all licenses-admin acknowlegments
  src/www/ui/api/Controllers/LicenseController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui_tests/api/Controllers/LicenseControllerTest.php
Labels: ready, GSOC-23

#2496 feat(api): File info API
  src/www/ui/api/Controllers/FileInfoController.php
  src/www/ui/api/Models/FileInfo.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
Labels: ready, GSOC-23

#2470 feat(api): get list of license decisions for an item
  src/www/ui/ajax-clearing-view.php
  src/www/ui/api/Controllers/UploadTreeController.php
  src/www/ui/api/Models/LicenseDecision.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui_tests/api/Controllers/UploadTreeControllerTest.php
Labels: ready, GSOC-23

#2501 feat(api): Get licenses reuse summary API
  src/lib/php/BusinessRules/ReuseReportProcessor.php
  src/www/ui/api/Controllers/UploadController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui/async/AjaxReuseReport.php
  src/www/ui_tests/api/Controllers/UploadControllerTest.php
Labels: ready, GSOC-23

#2495 feat(api): get a list of scanned licenses for an upload
  src/www/ui/api/Controllers/UploadController.php
  src/www/ui/api/Models/ScannedLicense.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
Labels: ready, GSOC-23

#2507 feat(CycloneDX): Add new agent cyclonedx
  cmake/FoPackaging.cmake
  src/CMakeLists.txt
  src/cyclonedx/CMakeLists.txt
  src/cyclonedx/agent/CMakeLists.txt
  src/cyclonedx/agent/cyclonedx.php
  src/cyclonedx/agent/reportgenerator.php
  src/cyclonedx/agent/version.php.in
  src/cyclonedx/cyclonedx.conf
  src/cyclonedx/ui/CycloneDXAgentPlugin.php
  src/cyclonedx/ui/CycloneDXGeneratorUi.php
  src/fossy-ruleset.xml
  src/lib/php/Report/ReportUtils.php
  src/spdx2/agent/spdx2.php
  src/www/ui/async/AjaxShowJobs.php
Labels: ready, GSOC-23
