Repository fossology/fossology, pull requests merged in 2023-03, with the labels that each got.

#2385 fix(core-schema): fix index to match DB
  src/www/ui/core-schema.dat
Labels: needs code review, needs test

#2372 fix(unifiedreport): fix warnings of unified report agent
  src/lib/php/Report/ClearedGetterCommon.php
  src/lib/php/Report/ObligationsGetter.php
  src/unifiedreport/agent/reportStatic.php
Labels: needs test

#2386 fix(spdx-rdf): use CDATA for attributionText
  .github/workflows/build-test.yml
  .github/workflows/deploy-pages.yml
  .github/workflows/static-checks.yml
  src/lib/php/Proxy/UploadTreeProxy.php
  src/lib/php/View/HighlightRenderer.php
  src/spdx2/agent/template/spdx2-package.xml.twig
  src/www/ui/css/highlights.css
Labels: needs code review, needs test

#2383 fix(decisionImporter): Rename duplicate file DecisionImporter.php
  src/decisionimporter/agent/CMakeLists.txt
  src/decisionimporter/agent/DecisionImporterAgent.php
  src/decisionimporter/agent/decisionimporter.php
Labels: ready

#2307 feat(API): `/jobs/history?upload={id}` GET route to get the history of all the jobs queued based on an upload
  src/www/ui/api/Controllers/JobController.php
  src/www/ui/api/Controllers/ReportController.php
  src/www/ui/api/Models/JobQueue.php
  src/www/ui/api/Models/ShowJob.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui/async/AjaxShowJobs.php
  src/www/ui_tests/api/Controllers/ReportControllerTest.php
Labels: ready

#2388 feat(highlightRows):Highlighted deleted rows on copyright/URL/Author/…
  src/copyright/ui/ajax-copyright-hist.php
  src/copyright/ui/template/histTable.js.twig
Labels: ready

#2389 fix(manualCopyright):Made Disabled Manual Copyrights Visible in UI
  src/copyright/ui/template/ui-xp-view_rhs.html.twig
  src/lib/php/Dao/CopyrightDao.php
Labels: ready

#2382 Added inverse search in Email/ Url / Author Page
  src/copyright/ui/HistogramBase.php
  src/copyright/ui/ajax-copyright-hist.php
  src/copyright/ui/template/histTable.js.twig
Labels: needs code review

#2390 fix(search): fix search endpoint
  src/lib/php/Dao/SearchHelperDao.php
  src/www/ui/api/Controllers/SearchController.php
  src/www/ui/api/Helper/DbHelper.php
Labels: needs code review, needs test

#2317 feat(API): `POST report/import?upload={id}` route for initiating a reportImport job for a given upload
  src/reportImport/ui/ReportImportPlugin.php
  src/www/ui/api/Controllers/ReportController.php
  src/www/ui/api/documentation/openapi.yaml
Labels: needs code review, needs test, GSoC-22

#2387 feat(decision-dump): export and import IPRA agent's data
  src/decisionexporter/agent/decisionexporter.php
  src/decisionimporter/agent/DecisionImporterAgent.php
  src/decisionimporter/agent/DecisionImporterDataCreator.php
  src/decisionimporter/agent/DecisionImporterIdFetcher.php
  src/decisionimporter/agent/FoDecisionData.php
  src/lib/php/Dao/AllDecisionsDao.php
Labels: enhancement, ready

#2381 feat(deleteFileInBrowse):ability to delete file from browser
  src/delagent/ui/Page/AdminUploadDelete.php
  src/delagent/ui/delete-file-browse.php
  src/www/ui/scripts/browse.js
Labels: ready

#2400 fix(clixml): use license full name in clixml report
  src/clixml/agent/clixml.php
  src/clixml/agent/template/clixml-file.xml.twig
  src/lib/php/BusinessRules/LicenseMap.php
  src/lib/php/BusinessRules/test/LicenseMapTest.php
  src/lib/php/Data/LicenseRef.php
  src/lib/php/Report/LicenseMainGetter.php
  src/www/ui/admin-license-file.php
  src/www/ui/page/AdviceLicense.php
Labels: ready

#2401 feat(licenseCsv): export spdx id in license CSV
  src/lib/php/Application/LicenseCsvExport.php
  src/lib/php/Application/LicenseCsvImport.php
  src/lib/php/Application/test/LicenseCsvExportTest.php
  src/lib/php/Application/test/LicenseCsvImportTest.php
  src/www/ui/page/AdminLicenseFromCSV.php
Labels: ready

#2393 feat(viewPasswordInLogin): Eye button to view Password while logging in
  src/lib/php/UI/template/components/login-form.html.twig
  src/www/ui/template/user_add.html.twig
  src/www/ui/template/user_edit.html.twig
Labels: ready

#2405 feat(clixml): introduce LinkScanTool
  src/clixml/agent/clixml.php
  src/clixml/agent/template/clixml-file.xml.twig
  src/lib/php/Report/LicenseMainGetter.php
Labels: ready

#2408 fix(import): ignore missing utree in dump import
  src/decisionexporter/agent/decisionexporter.php
  src/decisionimporter/agent/DecisionImporterDataCreator.php
  src/decisionimporter/agent/DecisionImporterIdFetcher.php
Labels: needs code review, needs test

#2411 fix(rest): swap upload and folder id to create job
  src/www/ui/api/Controllers/JobController.php
Labels: needs code review, needs test

#2416 fix(adminLicensecandidate): replace while loop with foreach
  src/www/ui/page/AdminLicenseCandidate.php
Labels: ready
