Repository fossology/fossology, pull requests merged in 2023-01, with the labels that each got.

#2362 chore(cmake): do not cache git version
  .gitpod.Dockerfile
  CMakeLists.txt
  cmake/FoUtilities.cmake
  cmake/SetDefaults.cmake
  debian/control
  docker-compose.yml
  src/copyright/CMakeLists.txt
  src/copyright/agent/CMakeLists.txt
  src/copyright/agent_tests/CMakeLists.txt
  src/delagent/agent_tests/CMakeLists.txt
  src/lib/c/tests/CMakeLists.txt
  src/lib/cpp/tests/CMakeLists.txt
  src/mimetype/agent_tests/CMakeLists.txt
  src/monk/agent_tests/CMakeLists.txt
  src/nomos/agent/CMakeLists.txt
  src/nomos/agent_tests/CMakeLists.txt
  src/ojo/CMakeLists.txt
  src/ojo/agent/CMakeLists.txt
  src/ojo/agent_tests/CMakeLists.txt
  src/pkgagent/agent/CMakeLists.txt
  src/pkgagent/agent/pkgagent.h
  src/pkgagent/agent_tests/CMakeLists.txt
  src/scancode/CMakeLists.txt
  src/scancode/agent/CMakeLists.txt
  src/scheduler/agent_tests/CMakeLists.txt
  src/ununpack/agent/CMakeLists.txt
  src/wget_agent/agent_tests/CMakeLists.txt
  src/www/CMakeLists.txt
  utils/fo-installdeps
Labels: ready

#2358 fix(security) fix inaproppriate encoding for output context
  src/cli/acme_review.php
  src/lib/php/common-folders.php
  src/www/ui/acme_review.php
Labels: needs code review, needs test

#2356 fix(security) fix Reflected XSS vulnerability
  src/lib/php/common-db.php
  src/www/ui/admin-config.php
Labels: needs code review, needs test

#2355 fix(security) Sanitized external command parameter
  src/cli/cp2foss.php
  src/lib/php/common-repo.php
  src/testing/db/cleanup_test_databases.php
  src/www/ui/admin-fossdash-config.php
  src/www/ui/change-license-processPost.php
  utils/runBuild_v2.0.php
Labels: ready

#2347 fix(licenseRef): show only active licenses in bulk and user decisions
  src/lib/php/Dao/LicenseDao.php
Labels: ready

#2354 fix(security) Replaced cryptographically insecure PHP rand() function
  install/db/dbmigrate_2.1-2.2.php
  src/lib/php/common-cache.php
  src/reportImport/ui/ReportImportAgentPlugin.php
  src/www/ui/core-smauth.php
  src/www/ui_tests/foss_ui.php
Labels: ready

#2370 feat(copyright): add new keywords for ECC and keyword agent
  src/copyright/agent/ecc.conf
  src/copyright/agent/keyword.conf
Labels: ready

#2369 feat(copyright): add new agent IPRA to FOSSology
  .gitignore
  cmake/FoPackaging.cmake
  src/clixml/agent/clixml.php
  src/clixml/agent/template/clixml-file.xml.twig
  src/copyright/CMakeLists.txt
  src/copyright/agent/CMakeLists.txt
  src/copyright/agent/cleanEntries.cc
  src/copyright/agent/cleanEntries.hpp
  src/copyright/agent/copyright.cc
  src/copyright/agent/copyrightUtils.cc
  src/copyright/agent/copyrightUtils.hpp
  src/copyright/agent/copyscan.cc
  src/copyright/agent/database.cc
  src/copyright/agent/database.hpp
  src/copyright/agent/identity.hpp
  src/copyright/agent/ipra.conf
  src/copyright/agent_tests/Functional/schedulerTest.php
  src/copyright/agent_tests/Unit/test_scanners.cc
  src/copyright/ipra.conf
  src/copyright/ui/IpraView.php
  src/copyright/ui/agent-ipra.php
  src/copyright/ui/ajax-copyright-hist.php
  src/copyright/ui/ipra-hist.php
  src/copyright/ui/list.php
  src/lib/php/Dao/UploadDao.php
  src/lib/php/Data/Highlight.php
  src/lib/php/View/HighlightRenderer.php
  src/unifiedreport/agent/unifiedreport.php
  src/www/ui/ajax-clearing-view.php
  src/www/ui/core-schema.dat
  src/www/ui/css/highlights.css
Labels: enhancement, ready

#2368 feat(spdx): update reports to v-2.3
  .gitignore
  install/scripts/install-spdx-tools.sh
  src/composer.json
  src/composer.lock
  src/lib/php/Data/LicenseRef.php
  src/spdx2/CMakeLists.txt
  src/spdx2/agent/spdx2.php
  src/spdx2/agent/spdx2utils.php
  src/spdx2/agent/template/dep5-copyright-document.twig
  src/spdx2/agent/template/spdx2-document.xml.twig
  src/spdx2/agent/template/spdx2-file.xml.twig
  src/spdx2/agent/template/spdx2-package.xml.twig
  src/spdx2/agent/template/spdx2tv-document.twig
  src/spdx2/agent/template/spdx2tv-file.twig
  src/spdx2/agent/template/spdx2tv-package.twig
  src/spdx2/agent_tests/Functional/schedulerTest.php
  src/www/ui/admin-license-file.php
  src/www/ui/page/AdviceLicense.php
Labels: enhancement, needs code review, needs test

#2374 fix(ci): add missing dependency to runner image
  utils/automation/Dockerfile.ci
Labels: needs code review
