Repository fossology/fossology, pull requests merged in 2023-08, with the labels that each got.

#2505 feat(api): conf info for upload
  src/www/ui/api/Controllers/ConfController.php
  src/www/ui/api/Models/Conf.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
Labels: ready, GSOC-23

#2520 feat(api): Get Customise page data
  src/lib/php/Dao/SysConfigDao.php
  src/lib/php/services.xml.in
  src/www/ui/api/Controllers/CustomiseController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui/core-schema.dat
Labels: ready, GSOC-23

#2509 feat(api): Add, edit & delete license decision
  src/www/ui/ajax-clearing-view.php
  src/www/ui/api/Controllers/UploadTreeController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui_tests/api/Controllers/UploadTreeControllerTest.php
Labels: ready, GSOC-23

#2516 feat(api): Add, Edit & toggle admin license acknowledgement
  src/www/ui/api/Controllers/LicenseController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui_tests/api/Controllers/LicenseControllerTest.php
Labels: ready, GSOC-23

#2570 chore(api): update API version 20230811
  src/www/ui/api/documentation/openapi.yaml
Labels: needs code review

#2030 fix(delagent): Use bcrypt to check password
  src/delagent/agent/CMakeLists.txt
  src/delagent/agent/util.c
  src/delagent/agent_tests/CMakeLists.txt
  src/delagent/mod_deps
Labels: needs code review, needs test

#2577 chore(UploadTreeProxy): optimize license file query
  src/lib/php/Proxy/UploadTreeProxy.php
  src/www/ui_tests/api/Controllers/UploadControllerTest.php
Labels: needs code review, needs test

#2576 feat(SETUP-V2): Support Multiple Versions (V1 & V2)
  src/www/ui/api/Models/ApiVersion.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
Labels: ready, GSOC-23

#2567 refactor(browse): use join to fetch data from two tables
  src/lib/php/Dao/FolderDao.php
  src/www/ui/api/Helper/UploadHelper.php
  src/www/ui/async/AjaxBrowse.php
Labels: ready

#2483 feat(api): REST API to schedule the bulk-scan
  src/www/ui/api/Controllers/UploadTreeController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui/change-license-bulk.php
  src/www/ui_tests/api/Controllers/UploadTreeControllerTest.php
Labels: ready, GSOC-23

#2517 feat(api): Get all standard comments
  src/www/ui/api/Controllers/LicenseController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
  src/www/ui_tests/api/Controllers/LicenseControllerTest.php
Labels: ready, GSOC-23

#2537 feat(api): Get the summary statistics for all Jobs
  src/www/ui/admin-dashboard-stats.php
  src/www/ui/api/Controllers/JobController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/index.php
Labels: ready, GSOC-23

#2156 fix(cd): Fix release workflow for version
  .github/workflows/release-publish.yml
Labels: needs code review, needs test

#2580 Fix PHP Doc
  src/cyclonedx/agent/cyclonedx.php
  src/lib/php/Application/ObligationCsvExport.php
  src/lib/php/Dao/LicenseDao.php
  src/lib/php/Dao/ShowJobsDao.php
  src/lib/php/Dao/SpashtDao.php
  src/lib/php/Data/Clearing/ClearingLicense.php
  src/nomos/agent_tests/testdata/NomosTestfiles/BSD/ibm.php
  src/testing/install/migrateConfig.php
  src/testing/install/srcConfig.php
  src/testing/install/test4migrationinstall/testdata.php
  src/testing/lib/common-Test.php
  src/testing/lib/common-Ui.php
  src/testing/lib/fossologyTestCase.php
  src/ununpack/ui/ui-reunpack.php
  src/www/ui/admin-upload-edit.php
  src/www/ui/api/Helper/UploadHelper.php
  src/www/ui/api/Middlewares/RestAuthMiddleware.php
  src/www/ui/api/Models/Analysis.php
  src/www/ui/api/Models/Findings.php
  src/www/ui/ui-report-conf.php
Labels: needs code review
