Repository fossology/fossology, pull requests merged in 2023-12, with the labels that each got.

#2647 fix(action): Ensure proper handeling of enum values in argparse
  utils/automation/fossologyscanner.py
Labels: ready

#2649 fix(token): fix token generation for user
  src/www/ui/api/Controllers/UserController.php
  src/www/ui/api/Middlewares/RestAuthMiddleware.php
  src/www/ui/api/index.php
  src/www/ui/user-edit.php
Labels: needs code review, needs test

#2654 style(php):Corrected the SQL syntax error in AllDecisionsDao.php
  src/lib/php/Dao/AllDecisionsDao.php
Labels: ready

#2653 fix(api): do not check page for empty response
  src/www/ui/api/Controllers/CopyrightController.php
  src/www/ui/api/Controllers/LicenseController.php
Labels: needs code review, needs test

#2652 fix(view): check if ScanOSS is installed
  src/www/ui/ui-view-info.php
Labels: needs code review, needs test

#2660 fix(deb): fix dependencies for bookworm
  cmake/FoPackaging.cmake
Labels: needs code review, needs test

#2658 Fix(php) : Fix null pointer issue in createClearingDecisions()
  src/decisionimporter/agent/DecisionImporterDataCreator.php
Labels: needs code review, needs test, needs squash
