Repository fossology/fossology, pull requests merged in 2023-11, with the labels that each got.

#2597 feat(bulk): checkbox to select scan for findings only
  src/decider/agent/BulkReuser.php
  src/decisionimporter/agent/DecisionImporterDataCreator.php
  src/decisionimporter/agent/FoDecisionData.php
  src/lib/php/Dao/AllDecisionsDao.php
  src/lib/php/Dao/LicenseDao.php
  src/monk/agent/database.c
  src/monk/agent/database.h
  src/monk/agent/monkbulk.c
  src/monk/agent/monkbulk.h
  src/www/ui/api/Controllers/UploadTreeController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/change-license-bulk.php
  src/www/ui/core-schema.dat
  src/www/ui/scripts/change-license-common.js
  src/www/ui/template/ui-clearing-view_bulk.html.twig
  src/www/ui_tests/api/Controllers/UploadTreeControllerTest.php
Labels: ready

#2621 fix(user-edit): handle HttpForbiddenException
  src/www/ui/user-edit.php
Labels: ready

#2620 fix(user-edit): compare old email and skip email count check
  src/www/ui/user-edit.php
Labels: ready

#2618 feat(os): add support for Debian Bookworm (12)
  .github/workflows/build-test.yml
  .github/workflows/release-publish.yml
  .gitpod.Dockerfile
  cmake/FoPackaging.cmake
  debian/control
  pbconf/fossology/deb/control
  src/copyright/mod_deps
  src/lib/php/Dao/CopyrightDao.php
  src/lib/php/Dao/LicenseStdCommentDao.php
  src/nomos/mod_deps
  src/ojo/mod_deps
  src/scancode/mod_deps
  src/ununpack/agent/CMakeLists.txt
  src/ununpack/agent/ununpack_globals.h
  src/ununpack/mod_deps
  utils/fo-installdeps
Labels: needs code review, needs test

#2626 fix(api): default values of page and limit
  src/www/ui/api/Controllers/UploadController.php
Labels: ready

#2624 feat(menu): add new button to indicate system load in banner
  src/lib/php/UI/Component/Menu.php
  src/lib/php/UI/template/components/menu.html.twig
  src/lib/php/common-sysconfig.php
  src/www/ui/async/AjaxAllJobStatus.php
  src/www/ui/template/all_job_status.html.twig
Labels: ready

#2628 fix(documentation): update README.md with PHP version
  README.md
Labels: ready

#2631 fix(unifiedreport): replace single quotes with double to fix line breaks
  src/unifiedreport/agent/reportStatic.php
Labels: ready

#2627 fix(ci): fix build in Debian Buster
  src/lib/php/Dao/ClearingDao.php
  src/lib/php/Dao/CopyrightDao.php
  src/lib/php/Dao/UserDao.php
  src/lib/php/Dao/test/ClearingDaoTest.php
  src/lib/php/Report/XpClearedGetter.php
  src/lib/php/common-license-file.php
  src/maintagent/ui/maintagent.php
  src/scancode/agent/scancode_utils.cc
  src/www/ui/async/AjaxFileBrowser.php
  src/www/ui/page/BrowseLicense.php
Labels: needs code review, needs test

#2622 feat(upload): track assignee and closing events
  src/lib/php/Dao/UploadDao.php
  src/lib/php/Dao/test/UploadDaoTest.php
  src/lib/php/Data/Upload/UploadEvents.php
  src/lib/php/Proxy/UploadBrowseProxy.php
  src/lib/php/Proxy/test/UploadBrowseProxyTest.php
  src/lib/php/common-ui.php
  src/lib/php/services.xml.in
  src/www/ui/admin-folder-size.php
  src/www/ui/api/Helper/DbHelper.php
  src/www/ui/api/Models/Upload.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/documentation/openapiv2.yaml
  src/www/ui/core-schema.dat
  src/www/ui/template/admin-folder-size-form.html.twig
  src/www/ui_tests/api/Controllers/UploadControllerTest.php
  src/www/ui_tests/api/Helper/DbHelperTest.php
  src/www/ui_tests/api/Models/UploadTest.php
Labels: ready, needs test

#2635 fix(spdx2): accept null values for arrays
  src/lib/php/Data/Report/FileNode.php
  src/lib/php/Data/Report/SpdxLicenseInfo.php
  src/spdx2/agent/template/spdx2-file.xml.twig
Labels: ready

#2636 deps(composer): update composer/spdx-licenses
  src/composer.json
  src/composer.json.in
  src/composer.lock
Labels: ready

#2637 chore(release): release 4.4.0-rc1
  CHANGELOG.md
  debian/changelog
Labels: needs code review, needs test

#2639 fix(action): fix the declaration of sleep duration
  .github/workflows/release-publish.yml
Labels: needs code review
