Repository fossology/fossology, pull requests merged in 2024-01, with the labels that each got.

#2645 feat(api): make cyclonedx report available via the API
  src/www/ui/api/Controllers/ReportController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/documentation/openapiv2.yaml
Labels: needs code review, needs test

#2665 fix(api): read optional agentId, UploadController
  src/www/ui/api/Controllers/UploadController.php
Labels: needs code review, needs test

#2664 fix(postinstall): check status of a2ensite
  cmake/SetDefaults.cmake
  debian/web/postinst
  install/fo-postinstall.in
Labels: needs code review, needs test

#2669 chore(release): 4.4.0 release
  CHANGELOG.md
  debian/changelog
Labels: needs code review

#2671 fix(spdx_ref): use LicenseRef to check ref license
  src/lib/php/Data/LicenseRef.php
  src/lib/php/Data/test/LicenseRefTest.php
  src/lib/php/Report/ReportUtils.php
Labels: needs code review, needs test

#2633 feat(api): (1) Upgrade Upload APIs to Version 2
  src/www/ui/api/Controllers/FileInfoController.php
  src/www/ui/api/Controllers/UploadController.php
  src/www/ui/api/Helper/DbHelper.php
  src/www/ui/api/Helper/UploadHelper.php
  src/www/ui/api/Middlewares/RestAuthMiddleware.php
  src/www/ui/api/Models/FileInfo.php
  src/www/ui/api/Models/FileLicenses.php
  src/www/ui/api/Models/GroupPermission.php
  src/www/ui/api/Models/Permissions.php
  src/www/ui/api/Models/Upload.php
  src/www/ui/api/documentation/openapiv2.yaml
  src/www/ui/api/index.php
  src/www/ui_tests/api/Controllers/UploadControllerTest.php
  src/www/ui_tests/api/Models/UploadTest.php
Labels: ready

#2634 feat(api): (2) Upgrade upload APIs to Version 2
  src/www/ui/api/Controllers/UploadController.php
  src/www/ui/api/Controllers/UploadTreeController.php
  src/www/ui/api/Models/Agent.php
  src/www/ui/api/Models/EditedLicense.php
  src/www/ui/api/Models/ScannedLicense.php
  src/www/ui/api/Models/SuccessfulAgent.php
  src/www/ui/api/documentation/openapiv2.yaml
  src/www/ui/async/AjaxManageToken.php
  src/www/ui_tests/api/Controllers/UploadControllerTest.php
Labels: ready
