Repository fossology/fossology, pull requests merged in 2024-07, with the labels that each got.

#2783 deps(docker)!: update docker base to Debian 12
  .dockerignore
  Dockerfile
  docker-compose.yml
  utils/automation/Dockerfile.ci
Labels: needs code review, needs test, dependencies

#2717 feat(api): New endpoints to get/delete/restore/update user copyright findings
  src/copyright/ui/ajax-copyright-hist.php
  src/lib/php/Dao/CopyrightDao.php
  src/www/ui/api/Controllers/CopyrightController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/documentation/openapiv2.yaml
  src/www/ui/api/index.php
Labels: ready, GSOC-24

#2769 feat(automation) : Add custom keyword.conf file
  utils/automation/.github-workflow.yml
  utils/automation/FoScanner/CliOptions.py
  utils/automation/FoScanner/Utils.py
  utils/automation/fossologyscanner.py
Labels: ready, GSOC-24

#2778 feat(info): add assignee, assigned data and clearing duration in info…
  src/lib/php/Dao/UploadDao.php
  src/www/ui/admin-folder-size.php
  src/www/ui/template/ui-view-info.html.twig
  src/www/ui/ui-view-info.php
Labels: ready

#2775 feat(differential scans): Add differential scans to CI Scanner
  utils/automation/.github-workflow.yml
  utils/automation/.gitlab-ci.sample.yml
  utils/automation/FoScanner/CliOptions.py
  utils/automation/FoScanner/RepoSetup.py
  utils/automation/fossologyscanner.py
Labels: ready, GSOC-24

#2764 test(api): added more unit test cases for maintenance and upload tree…
  src/www/ui_tests/api/Controllers/MaintenanceControllerTest.php
  src/www/ui_tests/api/Controllers/UploadTreeControllerTest.php
Labels: ready

#2768 feat(api): Added OneShot analysis endpoints for license & copyright
  src/copyright/ui/oneshot.php
  src/lib/php/Data/Highlight.php
  src/nomos/ui/agent-nomos-once.php
  src/www/ui/api/Controllers/OneShotController.php
  src/www/ui/api/Models/OneShot.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/documentation/openapiv2.yaml
  src/www/ui/api/index.php
Labels: ready, GSOC-24

#2784 feat(automation): Add custom allowlist.json
  utils/automation/.github-workflow.yml
  utils/automation/FoScanner/CliOptions.py
  utils/automation/fossologyscanner.py
Labels: ready, GSOC-24

#2766 fix(spdx2): Mark duplicates correctly with LicenseRef prefix
  src/spdx2/agent/spdx2.php
Labels: needs test

#2734 feat(licenses): introduce JSON format export and import of licenses and obligations
  src/cli/fo_import_licenses.php
  src/lib/php/Application/LicenseCsvExport.php
  src/lib/php/Application/LicenseCsvImport.php
  src/lib/php/Application/ObligationCsvExport.php
  src/lib/php/Application/ObligationCsvImport.php
  src/lib/php/Application/test/LicenseCsvImportTest.php
  src/www/ui/page/AdminAllLicenseToJSON.php
  src/www/ui/page/AdminLicenseFromCSV.php
  src/www/ui/page/AdminLicenseToJSON.php
  src/www/ui/page/AdminObligationFromCSV.php
  src/www/ui/page/AdminObligationToJSON.php
  src/www/ui/template/admin_license_from_csv.html.twig
Labels: ready
