Repository fossology/fossology, pull requests merged in 2024-10, with the labels that each got.

#2840 Scanoss qg/2668/row number out of range
  src/scanoss/agent/main.c
  src/scanoss/agent/snippet_scan.c
  src/www/ui/ui-view-info.php
Labels: needs code review, needs test

#2857 chore(cmake): ignore anaconda paths
  CMakeLists.txt
Labels: ready

#2856 chore(package): add compatibility agent deb package
  cmake/FoPackaging.cmake
Labels: needs code review, needs test

#2842 docs(SCANOSS): updated documentation for the SCANOSS agent
  src/scanoss/README.MD
  src/scanoss/pics/screenshot1.png
  src/scanoss/pics/screenshot1.png.license
  src/scanoss/pics/screenshot2.png
  src/scanoss/pics/screenshot2.png.license
  src/scanoss/pics/screenshot3.png
  src/scanoss/pics/screenshot3.png.license
Labels: Documentation

#2843 fix(created_by): Add created by column to candidate license table
  src/www/ui/page/AdviceLicense.php
  src/www/ui/template/advice_license.html.twig
Labels: needs test

#2858 fix(ui): Add loader to upload permission and edit decision page
  src/www/ui/scripts/change-license-browse.js
  src/www/ui/scripts/change-license-common.js
  src/www/ui/template/change_license_modal.html.twig
  src/www/ui/template/upload_permissions.html.twig
Labels: needs code review, needs test

#2815 fix(import): Do not require an agent if the report has no related data
  src/decisionimporter/agent/DecisionImporterDataCreator.php
Labels: needs code review, needs test
