Repository fossology/fossology, pull requests merged in 2024-08, with the labels that each got.

#2780 feat(upload): add tooltips and description to individual agents
  src/buckets/ui/agent-bucket.php
  src/copyright/ui/agent-copyright.php
  src/copyright/ui/agent-ecc.php
  src/copyright/ui/agent-ipra.php
  src/copyright/ui/agent-keyword.php
  src/lib/php/common-agents.php
  src/mimetype/ui/agent-mimetype.php
  src/monk/ui/agent-monk.php
  src/nomos/ui/agent-nomos.php
  src/ojo/ui/agent-ojos.php
  src/pkgagent/ui/agent-pkgagent.php
  src/reso/ui/ResoAgentPlugin.php
  src/scanoss/ui/agent-scanoss.php
  src/softwareHeritage/ui/agent-shagent.php
  src/www/ui/ajax-upload-agents.php
Labels: ready

#2796 Fix issue 1868: SPDX import does not conclude licenses based on hash values but on file name
  src/reportImport/agent/ReportImportAgent.php
Labels: needs code review, needs test

#2754 feat(automation) : Add line numbers to keyword and copyright scanners
  utils/automation/FoScanner/FormatResults.py
  utils/automation/FoScanner/Scanners.py
  utils/automation/fossologyscanner.py
Labels: ready, GSOC-24

#2772 feat(api): New endpoints to get/delete/restore/update scancode copyright, email, author, url findings
  src/www/ui/api/Controllers/CopyrightController.php
  src/www/ui/api/documentation/openapi.yaml
  src/www/ui/api/documentation/openapiv2.yaml
  src/www/ui/api/index.php
Labels: ready, GSOC-24

#2785 feat(nomos): Add start, end, len to nomos JSON output.
  src/nomos/agent/json_writer.c
Labels: ready, GSOC-24

#2781 feat(api): modify /jobs and related endpoints
  src/lib/php/Dao/JobDao.php
  src/www/ui/api/Controllers/JobController.php
  src/www/ui/api/Models/Job.php
  src/www/ui/api/documentation/openapiv2.yaml
  src/www/ui/async/AjaxShowJobs.php
  src/www/ui_tests/api/Controllers/JobControllerTest.php
  src/www/ui_tests/api/Models/JobTest.php
Labels: ready, GSOC-24

#2806 hotfix(docker_test): Use docker compose (v2) instead of docker-compose (v1)
  .github/workflows/docker-test.yml
  src/testing/docker/test-cluster.sh
  src/testing/docker/test-standalone.sh
Labels: ready
