Repository fossology/fossology, pull requests merged in 2025-03, with the labels that each got.

#2964 fix(db): Migration Was failing due to Old views and Tables
  src/lib/php/libschema.php
Labels: needs test

#2934 feat(changelog): add change log for release 4.5
  CHANGELOG.md
  debian/changelog
Labels: ready

#2995 fix(docker): add missing dependency
  Dockerfile
Labels: needs code review, needs test

#3007 chore(docker): Removed version attribute from docker-compose.yml
  docker-compose.yml
Labels: needs code review, needs test

#3001 feat(import): Import Obligations From LicenseDB
  src/lib/php/Application/ObligationCsvImport.php
  src/lib/php/Util/HttpUtils.php
  src/lib/php/common-sysconfig.php
  src/www/ui/page/AdminLicenseFromCSV.php
  src/www/ui/page/AdminObligationFromCSV.php
  src/www/ui/template/admin_license_from_licensedb.html.twig
Labels: needs code review, needs test

#3012 feat(changelog): add changelog for release 4.5
  CHANGELOG.md
  debian/changelog
Labels: ready

#3013 fix(adminObligationsImport): undefined variable throwing warning
  src/www/ui/page/AdminObligationFromCSV.php
Labels: ready

#3014 feat(workflow): Commit Linting Stage in Static Checks
  .github/workflows/static-checks.yml
  commitlint.config.mjs
Labels: ready

#3022 fix(ci): dco check not running on push event on main
  .github/workflows/static-checks.yml
Labels: needs code review

#3023 feat(changelog): add change log for new release 4.5.1
  CHANGELOG.md
  debian/changelog
Labels: ready
