Repository fossology/fossology, pull requests merged in 2025-05, with the labels that each got.

#3039 fix(report): CLIXml Report Showing Incorrect License Type
  src/clixml/agent/clixml.php
Labels: needs code review, needs test

#3045 fix(ui): fix tooltip for reuse modal in file upload page
  src/www/ui/template/upload_file.html.twig
Labels: needs code review, needs test

#3046 fix(treeview): exclude scancode, reportimport and spasht from schedul…
  src/www/ui/template/browse_license-agent_selector.html.twig
Labels: ready

#3044 feat(group): add option to edit groupname
  src/lib/php/Dao/UserDao.php
  src/www/ui/page/AdminGroupEdit.php
  src/www/ui/template/admin_group_edit.html.twig
Labels: ready

#3048 fix(jsload) : Reuser agent not being scheduled
  src/decider/ui/DeciderAgentPlugin.php
  src/reuser/ui/agent-reuser.php
  src/reuser/ui/reuser-plugin.php
  src/reuser/ui/template/agent_reuser.js.twig
  src/scancode/ui/agent-scancode.php
  src/www/ui/agent-add.php
  src/www/ui/template/agent_adder.html.twig
Labels: ready

#3049 Do not consider global decisions for every bulk action
  src/monk/agent/database.c
Labels: ready

#2998 Fix(pkgagenterror): pkgagent printing html encoded characters
  src/www/ui/template/ui-view-info.html.twig
  src/www/ui/ui-view-info.php
Labels: ready

#3037 fix(agent-tests): modernize PHPUnit test for common-menu.php
  src/lib/php/tests/test_common_menu.php
Labels: ready

#2947 fix: prevent nomos CLI from connecting to DB when not required (#1299)
  src/lib/c/libfossscheduler.c
  src/nomos/agent/nomos_utils.c
Labels: needs test

#3060 fix(nomossa): define should_connect_to_db
  src/lib/c/libfossrepo.c
  src/lib/c/libfossscheduler.h
  src/nomos/agent/nomos_utils.c
  src/nomos/agent/standalone.c
  src/ununpack/agent/standalone.c
Labels: ready
