Repository fossology/fossology, pull requests merged in 2025-01, with the labels that each got.

#2827 test(api): Add more unit test cases for APIs including folder,upload,maintenance, license , and group.
  src/www/ui/api/Controllers/CopyrightController.php
  src/www/ui/api/documentation/openapiv2.yaml
  src/www/ui_tests/api/Controllers/CopyrightControllerTest.php
  src/www/ui_tests/api/Controllers/FolderControllerTest.php
  src/www/ui_tests/api/Controllers/LicenseControllerTest.php
  src/www/ui_tests/api/Controllers/MaintenanceControllerTest.php
  src/www/ui_tests/api/Controllers/UploadControllerTest.php
Labels: needs code review, needs test, GSOC-24

#2859 Fix(monk): Filter bulk scan files by agent for current upload
  src/monk/agent/database.c
Labels: needs code review, needs test

#2881 enhancement(ui): add server side pagination to compatibility rule page
  src/lib/php/Dao/CompatibilityDao.php
  src/www/ui/page/AdminLicenseCompatibilityRules.php
  src/www/ui/template/admin_license_compatibility_rules.html.twig
  src/www/ui/template/admin_license_compatibility_rules.js.twig
Labels: needs code review, needs test

#2860 refactor(report): Remove datetime from report names
  src/clixml/agent/clixml.php
  src/cyclonedx/agent/cyclonedx.php
  src/lib/php/Dao/ShowJobsDao.php
  src/lib/php/Report/ReportUtils.php
  src/readmeoss/agent/readmeoss.php
  src/spdx2/agent/spdx2.php
  src/unifiedreport/agent/unifiedreport.php
  src/www/ui/async/AjaxShowJobs.php
Labels: ready

#2907 fix: Internal Server Error in upload from file page
  src/www/ui/page/UploadFilePage.php
Labels: ready

#2811 feat(Dependecy Scan): Add Python Dependency Scan
  .gitignore
  utils/automation/FoScanner/CliOptions.py
  utils/automation/FoScanner/FormatResults.py
  utils/automation/ScanDeps/Downloader.py
  utils/automation/ScanDeps/Parsers.py
  utils/automation/ScanDeps/__init__.py
  utils/automation/fossologyscanner.py
Labels: ready, GSOC-24

#2909 fix(decider): parse multiple arguments correctly
  src/decider/agent/DeciderAgent.php
  src/scheduler/agent/agent.c
Labels: ready

#2809 feat(dir_scan): Scan a subdirectory inside CI
  utils/automation/FoScanner/CliOptions.py
  utils/automation/FoScanner/FormatResults.py
  utils/automation/fossologyscanner.py
Labels: ready, GSOC-24

#2876 Feat: Licenses import from LicenseDB
  src/lib/php/Application/LicenseCsvImport.php
  src/lib/php/Plugin/DefaultPlugin.php
  src/lib/php/Plugin/test/DefaultPluginTest.php
  src/lib/php/Util/HttpUtils.php
  src/lib/php/common-sysconfig.php
  src/softwareHeritage/agent/softwareHeritageAgent.php
  src/www/ui/page/AdminLicenseFromCSV.php
  src/www/ui/template/admin_license_from_licensedb.html.twig
Labels: needs test

#2912 fix(licensedb): remove redundant usage of LicenseDBSleep
  src/www/ui/page/AdminLicenseFromCSV.php
Labels: ready

#2910 feat(changelog): add changelog for release 4.5.0-rc1
  CHANGELOG.md
  debian/changelog
Labels: ready

#2919 feat(conclusionString): Update Conclusion String
  src/decider/agent/DeciderAgent.php
  src/lib/php/BusinessRules/ClearingDecisionProcessor.php
  src/lib/php/Data/Clearing/ClearingEventTypes.php
Labels: needs test

#2921 fix(api): Jobs no longer displayed wrongly as queued
  src/www/ui/api/Helper/DbHelper.php
Labels: needs code review, needs test

#2924 fix(ui): fixing the folder navigation collapse issue
  src/www/ui/template/ui-browse.html.twig
  src/www/ui/template/ui-browse.js.twig
Labels: ready

#2928 fix(packaging): add required yaml dependency
  cmake/FoPackaging.cmake
Labels: ready

#2930 fix(scanner): Fix broken Scanner Image
  utils/automation/Dockerfile.ci
  utils/automation/fossologyscanner.py
  utils/automation/requirements.txt
Labels: ready
